### ISSUE TITLE
8.10 parole au peuple?

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#10]
Cette mesure n'existe pas dans le programme détaillé d' « En Marche », ou ne figure seulement que la « mise en place des comités de vigilance associant des représentants d’associations et d’ONG » pour la négociation et l'application des accords commerciaux... A-t-elle déjà été supprimée ?

Quels pouvoirs auraient ces conventions ? Pourquoi l'Union Européenne (UE) et l'Allemagne accepteraient-elles ces conventions et leur « projet », [alors que l'UE est de moins en moins démocratique, et que les pouvoirs sont monopoliséss par la Commission Européenne et la Banque Centrale Européenne](http://www.monde-diplomatique.fr/2013/08/LORDON/49561) ? On a vu à quel point l'UE accordait de l'importance à la démocratie, en ignorant le rejet du projet de Traité Constitutionnel Européen lors du référendum de 2005, ou le [rejet des mesures d'austérité par le peuple grec en 2015](http://yetiblog.org/index.php?post/1453)...
Cette mesure nous semble donc totalement irréaliste, à moins de s'engager dans un conflit avec l'Allemagne et l'UE actuelle, ce qui est loin d'être l'ambition d'Emmanuel Macron, au contraire.

**Comment by LVAI** [comment]
@lucasgautheron corrections :
Cette mesure n'existe pas dans le programme détaillé d' « En Marche », **où** ne figure seulement que la « mise en place des comités de vigilance ... » : rajouté l'accent sur le "ou". J'enlèverai le "seulement" aussi sui fait doublon avec le "que"
