### ISSUE TITLE
Liens LAEC

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#100]
5.4 ?

~~.[Adoption d'une loi de programmation pluriannuelle pour la justice fixant l’objectif d’une nette augmentation du budget en cinq ans (+ 2,5 milliards d’euros ajoutés aux 6,9 milliards du budget prévu en 2017) afin de parvenir en 2022 au niveau des principaux pays de l’Union européenne (UE) en matière de moyens consacrés à la justice.](https://avenirencommun.fr/le-livret-justice/)~~

~~.[Augmentation de moitié des effectifs des services judiciaires afin de parvenir au nombre approprié de magistrats par habitant, en recrutant 18 000 magistrats, greffiers et personnels administratifs.](https://avenirencommun.fr/le-livret-justice/)~~

~~.[Fin de la politique du chiffre et suppression des primes aux résultats, notamment de l’indemnité de responsabilité et de performance des commissaires (IRP) et des primes de résultats exceptionnels (PRE). Les montants seront redistribués via une hausse des salaires de façon progressive aux différentes catégories d’agents.](https://avenirencommun.fr/le-livret-securite/)~~

~~.[Renforcement des politiques de prévention en évitant les phénomènes de mises en danger qu’ils soient sociaux, économiques, scolaires ou urbains, pour bloquer à la racine les parcours délinquants. La prévention suppose de renforcer les formations des professionnels, leur nombre et leur déploiement sur l’ensemble du territoire.](https://avenirencommun.fr/le-livret-securite/)~~

~~.[Refondation de la doctrine du maintien de l’ordre pour favoriser la désescalade et la prévention des actes violents. Nous devons démonter les engrenages de violence de deux camps qui s’affrontent. ](https://avenirencommun.fr/le-livret-securite/)~~

2.6 (supprimer le texte existant):

~~.[Un service public d’accompagnement des entrepreneurs indépendants et des petites entreprises sera créé, en ciblant en priorité les entreprises de moins de trois ans. Il sera composé d’experts accompagnateurs avec différents pôles de compétences : droit, gestion, ressources humaines, fiscalité, éco-responsabilité, innovation, etc. Il permettra aux entrepreneurs de lever les freins juridiques, commerciaux et administratifs de leurs projets et sera accessible gratuitement à toute personne souhaitant créer, reprendre, ou diriger une petite entreprise.](https://avenirencommun.fr/livret-produire-france/)~~

~~.[Soutenir la dématérialisation des services publics, dans une démarche de design pour tou·te·s, tout en maintenant les services physiques de proximité.](https://avenirencommun.fr/le-livret-numerique/)~~

~~.[Attribuer une part de responsabilité aux donneurs d'ordre dans l'emploi de sous-traitants, afin de stabiliser le remplissage des carnets de commande, et soulager les sous-traitants de responsabilités auxquels ils ne sont parfois pas à même de répondre seuls.](https://laec.fr/section/21/mobiliser-l-argent-pour-financer-les-petites-et-moyennes-entreprises-et-la-creation-d-emploi#mesure-5)~~

~~.[Suppression de la loi El Khomri: Les travailleur·euse·s des plates-formes seront présumé·e·s salarié·e·s, à l’inverse de ce que prévoit la loi El Khomri. Nous faciliterons la requalification du statut d’auto-entrepreneur·euse en contrat de travail salarié.](https://avenirencommun.fr/le-livret-travail/)~~

3.2 (+ garder "renforcer l'ISF")

~~.[Les entreprises qui réinvestissent en France paieront moins d'impôts, celles qui favorisent la rémunération de leurs actionnaires davantage. A court terme, le taux de l’impôt sur les sociétés sera porté à 25 %.](https://avenirencommun.fr/livret-produire-france/)~~

~~.[Mise en place d'un taux d'escompte à taux à 0%, permettant aux PME d'économiser sur les frais bancaires générés par les avances des banques aux entreprises qui attendent des paiements de la part de leurs clients, afin de disposer de liquidités.](https://laec.fr/s21m3)~~

~~.[Faciliter les crédits aux entreprises éco et socio-responsables, par la création d'un pôle bancaire public, accorder des facilités de crédit aux entreprises qui investissent et épousent une dynamique de création d'emplois par l'investissement.](https://laec.fr/s21m1)~~

~~.[Création d'un fond de solidarité interentreprises, permettant une meilleure répartition des coûts de la contribution sociale entre les entreprises, indexée sur un barème progressif, pour que les TPE ne payent quasiment rien et que les grands groupes cotisent pour l’essentiel.](https://laec.fr/s21m6)~~

~~.[Le Crédit d’impôt recherche (CIR) sera supprimé et l’aide publique, s’appuyant notamment sur le pôle public bancaire, sera dirigée exclusivement sur les vrais acteurs de la R&D, et en priorité les PME qui consacrent aujourd'hui énormément de temps et d’argent à la recherche de financements.](https://avenirencommun.fr/livret-produire-france/)~~

~~.[La contribution additionnelle concernant les versements de dividendes et les rachats d’actions sera doublée, et ce, dans le but d’imposer davantage les entreprises qui privilégient les actionnaires à l’économie réelle. Cela permettra notamment aux PME et aux TPE d’assumer la hausse de masse salariale à la suite de l’augmentation du Smic et de pouvoir anticiper les effets de relance et de hausse des commandes.](https://avenirencommun.fr/livret-produire-france/)~~

9-3:

~~.[Mise en place d'un service citoyen obligatoire de neuf mois rémunéré au smic pour les hommes et les femmes de moins de 25 ans, qui seront affectés à des tâches d’intérêt général, notamment au secours à la population, à la protection et la réparation de l’environnement, et à l'appui à des associations labellisées d’intérêt général.](https://avenirencommun.fr/le-livret-jeunesse/)~~

~~.[La collectivité proposera un « contrat coopératif » aux personnes en échec provisoire sur le marché du travail. La somme auparavant versée au titre de l’indemnisation chômage le sera désormais par l'Etat, et ces personnes pourront être orientées vers les besoins publics locaux ou les associations agrémentées, et disposeront d’un droit opposable à un contrat rémunéré au salaire minimum.](https://avenirencommun.fr/le-livret-pauvrete/)~~

~~.[Mettre les associations au coeur de l’action culturelle sur tout le territoire dans l'espace public, et leur donner les moyens financiers adaptés afin de faire reculer les déserts culturels.](https://avenirencommun.fr/le-livret-culture/)~~

~~.[Les associations qui assurent un accueil immédiat et sans condition des personnes en difficulté, seront soutenues.](https://avenirencommun.fr/le-livret-pauvrete/)~~

~~.[Soutenir les associations de médiation numérique et revaloriser le statut des médiateurs.](https://avenirencommun.fr/le-livret-numerique/)~~

**Comment by LVAI** [comment]
Committed
