### ISSUE TITLE
Livret santé p.18

### ISSUE THREAD

**Issue by 1964nadia** [Insoumis/programme-macron#103]
• La  création  d’un  corps  de  médecins  généralistes  fonctionnaires  rémuné-rés pendant leurs études, afin de pallier l'insuffisance de médecins dans cer-taines zones• Le statut de service public sera réservé aux établissements publics, tandis que les établissements privés à but non lucratif pourront y être associés. • La sortie du « tout T2A » (tarification à l’activité) et de la politique du chiffrequi met les établissements hospitaliers en situation de conflits d’intérêt avec la Sécurité sociale. La T2A sera réservée aux actes techniques, standardisés et  programmés  tandis  que  les  spécialités  ayant  à  traiter  des  maladies  chro-niques seront financées par la dotation globale. Enfin, pour les soins palliatifs, il faut revenir au prix de journée. • Le recrutement 62 500 soignants et médecins à l’hôpital afin que les per-sonnels ne soient plus la variable d’ajustement budgétaire. • Le médico-social doit cesser d’être un vide et médical et social servant de variable  d’ajustement  à  ces  deux  secteurs.  Au  contraire,  la  reconnaissance  de  la  spécificité  des  pratiques  professionnelles  qui  le  constituent  et  le  ren-forcement de sa dotation en moyens humains et financiers permettront à ce  secteur  de  relever  le  défi  des  maladies  chroniques  et  du  vieillissement.  Le financement du médico-social sera réalisé à la dotation globale et non à l’activité. •  Lors de la fin de vie, la dignité des patients devra être respectée. Le droit à décider de sa propre fin, y compris avec assistance, sera reconnu liberté fondamentale et inscrit dans la ConstitutionNos propositions : une santé accessible, publique

**Comment by LVAI** [comment]
Doublon
