### ISSUE TITLE
Liens LAEC 10.3

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#104]
Remplacer celui sur le site

.[Promulguer une loi de justice territoriale visant à enrayer la loi du marché, à permettre l’égalité d’accès des citoyen·ne·s aux services publics et promouvoir la coopération et le développement soutenable et juste de tous les territoires de la République.](https://avenirencommun.fr/livret-ruralite-amenagement-territoire/)

.[Abroger les lois de l’Acte 3 de la décentralisation (…) pour mettre en place une organisation
territoriale autour des communes et des départements. ](https://avenirencommun.fr/livret-ruralite-amenagement-territoire/)

.[Mise en place d'un commissariat à l’aménagement du territoire, doté de moyens d’analyse et de planification.](https://avenirencommun.fr/livret-ruralite-amenagement-territoire/)

.[Inscrire l’égalité d’accès aux services publics des habitants de tous les territoires de la République sur les missions essentielles de l’État inscrites dans la Constitution : santé, éducation, eau, énergie, transports, communications, accès à la culture et aux services sociaux.](https://avenirencommun.fr/livret-ruralite-amenagement-territoire/)

.[Moratoire sur les fermetures de services publics et un plan de redéploiement des services publics sur les territoires ruraux et périurbains : services postaux, gares de proximité, hôpitaux et services de
santé, écoles, palais de justice.](https://avenirencommun.fr/livret-ruralite-amenagement-territoire/)

.[Refuser les baisses de dotations aux collectivités mises en place par le gouvernement Hollande et garantir une dotation à la hauteur des missions transférées aux collectivités. Il sera également mis fin au remplacement des dotations de l’État par des fonds d’investissement (…).](https://avenirencommun.fr/livret-ruralite-amenagement-territoire/)

.[Refuser les traités de libre-échange : le traité trans-atlantique TAFTA entre l'UE et les États-Unis, CETA avec le Canada et le traité TISA de libéralisation des services.](https://laec.fr/s49m4)

**Comment by LVAI** [comment]
Committed
