### ISSUE TITLE
9.3 Accélérateur d'association

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#11]
Il existe déjà plusieurs organismes gouvernementaux qui s'occupent du domaine associatif, comme la [Direction Générale de la Cohésion Sociale (DGCS)](http://social-sante.gouv.fr/ministere/organisation/directions/article/dgcs-direction-generale-de-la-cohesion-sociale). Et surtout, la [Direction de la jeunesse, de l'éducation populaire et de la vie associative (DJEPVA)](http://www.jeunes.gouv.fr/ministere/missions-et-organisation/organisation-du-ministere/article/la-direction-de-la-jeunesse-de-l), qui dépend du ministère de la Ville, de la Jeunesse et des Sports, et le [Fonds pour le Développement de la Vie Associative (FDVA)](http://www.associations.gouv.fr/FDVA.html).

Le premier organisme « coordonne et évalue les politiques en faveur de la jeunesse, de l’éducation populaire et de la vie associative », tandis que le second est un dispositif financier de l’Etat, de soutien au développement de la vie associative. Quel interêt de créer une troisième structure ? On voit mal ce que cette structure apporterait de réellement nouveau, à part un peu plus de bureaucratie.

Et quel sera le budget de cette nouvelle structure ? Quelles associations seront concernées ? Nous n'avons pas plus d'informations sur cette structure, qui nous semble très floue.

**Comment by lucasgautheron** [comment]
Merci.
Tu as les liens vers les mesures de l'AEC associées ? (Liens laec.fr)

**Comment by sarah48** [comment]
Non, franchement je vois pas ou il pourrait y avoir une réponse dans le programme...D'ailleurs ça pourrait être une question pour la FAQ, je l'ai mise dans le salon dédié, meme si c'est trop tard...
