### ISSUE TITLE
9.5 Plan santé

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#12]
5 milliards, c'est une somme très faible pour notre système de santé qui est au bord de l'implosion, comme le montre l'actualité en Guyane  [ou les hôpitaux sont en grande difficulté dans tous les domaines](http://www.francetvinfo.fr/sante/politique-de-sante/guyane-l-hopital-au-bord-de-l-asphyxie_2118747.html), et ou « il n’y a que 47 médecins généralistes pour 100.000 habitants, contre 106 en métropole », [27 médecins spécialistes contre 94 en métropole, 28 chirurgiens dentistes contre 57 en France métropolitaine, 134 infirmiers en Guyane contre 174 dans l'Hexagone et 47 kinésithérapeutes contre 104](http://www.allodocteurs.fr/se-soigner/politique-sante/la-guyane-le-plus-grand-desert-medical-de-france_22013.html) ...
D'une manière générale, c'est plutôt en plusieurs dizaines de milliards que s'évaluent les besoins actuels, même si notre système de santé n'est pas confronté qu'à des problèmes budgétaires.
L’espérance de vie en bonne santé diminue depuis 2006, les dépassements d'honoraires se multiplient, comme les [déserts médicaux, surtout dans zones rurales et les banlieues](https://fr.wikipedia.org/wiki/D%C3%A9sertification_m%C3%A9dicale_(France)), 
 le nombre de médecins généralistes a diminué de 8,4 % entre
2007 et 2016. Pendant ce temps, on privatise progressivement le système de soins, et [en 2015, les firmes pharmaceutiques ont fait 47 milliards de bénéfices](https://avenirencommun.fr/le-livret-sante/)...
Des hôpitaux ferment, des lits sont supprimés... La [Tarification à l'activité (« T2A ») mise en place en 2007, qui amène des objectifs de rentabilité et augmente encore le poids des tâches administratives, les baisses de budget, et la réduction de l'objectif national d'assurances maladie (Ondam](http://www.liberation.fr/france/2016/11/06/l-hopital-malade-de-sa-logique-financiere_1526631)
 , amènent une grave surcharge de travail des personnels, qui a conduit à de nombreuses grèves récentes. [Grève de l'ensemble des personnels hospitaliers](http://www.liberation.fr/france/2017/03/07/le-personnel-de-sante-en-greve-ce-mardi-pour-denoncer-ses-conditions-de-travail_1553821), des infirmiers, 
[des étudiants en chirurgie dentaire](http://www.francetvinfo.fr/sante/politique-de-sante/greve-nationale-des-etudiants-en-chirurgie-dentaire_2027940.html), des personnels des hôpitaux psychiatriques...
A tout cela s'ajoutent des nouvelles dépenses nécessaires concernant les personnes âgées et la prévention. Dans le domaine de la santé, les investissements en matière de santé prévus par la France Insoumise s'élèvent à environ 25 milliards, soit 5 fois plus.

**Comment by lucasgautheron** [comment]
Merci
