### ISSUE TITLE
7.1 Laicité

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#26]
Concernant le diplôme universitaire, si il n'est pas question ici d'un enseignement religieux, c'est le fait de dispenser un enseignement à des religieux qui pose problème vis à vis du principe de laïcité. Le problème est : Qui va financer cette formation ? 

Le fait de dispenser un enseignement à l'école sur le fait religieux pose encore plus problème.
Cette mesure ressemble à ce qui se passe dans le cadre du [« concordat » dans les départements du Bas-Rhin, du Haut-Rhin et de la Moselle](https://fr.wikipedia.org/wiki/Concordat_en_Alsace-Moselle), ou ne s'applique pas la loi de séparation de l'Eglise et de l'Etat de 1905. L'Etat y reconnaît donc et organise 4 grands cultes, en particulier en salariant les ministres de ces cultes, et la religion y est enseignée à l'école primaire et au collège.
De plus, actuellement, et [depuis 2009, « l'enseignement du fait religieux »](https://fr.wikipedia.org/wiki/Enseignement_du_fait_religieux_en_France) s'effectue déja à l'école à travers les disciplines existantes, principalement l’histoire, les lettres et la philosophie, en contextualisant toujours les phénomènes religieux, et en ne considérant jamais les différentes religions comme des systèmes clos.

Dans les détails du programme, il est aussi question de créer une « Fédération nationale de l’islam de France regroupant des associations cultuelles locales (…) qui pourront recevoir des dons et legs dans des conditions fiscales avantageuses », pour « financer la rénovation et la construction de mosquées et la formation d’imams ». Le danger de cette mesure est d'[augmenter encore le nombre de niches fiscales qui existent déjà dans ce domaine du financement des cultes](http://bfmbusiness.bfmtv.com/france/l-etat-et-le-financement-religieux-une-separation-loin-d-etre-absolue-1022325.htm), ce qui fait que L'Etat et surtout [« certaines collectivités locales s’engouffrent dans ces failles juridiques pour financer la construction de lieux de cultes »](https://avenirencommun.fr/le-livret-laicite/).

Enfin, pour « appliquer strictement le principe de laïcité », il faudrait revenir sur un certain nombre de dispositions qui ont affaibli ce principe depuis 1905, comme [le financement public des écoles privées, avec la loi Debré de 1959](https://blogs.mediapart.fr/emancipation/blog/030413/financement-public-de-lenseignement-prive-lomerta-continue), ([7 milliards d'euros en 2013](https://avenirencommun.fr/le-livret-laicite/)), le concordat ([55 millions par an](https://avenirencommun.fr/le-livret-laicite/)), et d'autres exceptions à la laïcité dans certaines collectivités d'outre-mer. Il faudrait aussi que le président refuse de se faire ordonner chanoine de Latran au Vatican, comme l'ont été Nicolas Sarkozy et François Hollande.

**Comment by lucasgautheron** [comment]
Merci.
Je trouve ça bien, sauf que je supprimerais le dernier paragraphe pour l'intégrer dans l'AEC. (C'est ce que j'ai fait en attendant).

**Comment by sarah48** [comment]
Le problème c'est que en enlevant ça, on ne répond pas à l'affirmation initiale: "Nous appliquerons strictement le principe de laicité". C'est pour ça que j'avais fait ce dernier paragraphe, parce que c'est une affirmation globale.
Donc je propose qu'on mette: "Enfin, on ne peux pas dire qu' « En Marche » « appliquera strictement le principe de laïcité », puisqu'il ne revient pas sur d'importantes dispositions qui ont affaibli ce principe depuis 1905, comme on peux le voir ci-dessous dans le programme de la France Insoumise sur ce thème."
Pour faire une transition et répondre à l'affirmation.
D'ailleurs pour l'étiquette je verrais plutôt une étiquette du genre "C'est faux".
Aussi, dans les mesures de la FI il en manque une très importante je trouve, dans le livret: « Il est urgent de mettre fin au détournement de fonds publics attribués à l’enseignement confessionnel privé : il en a coûté 7 milliards d’euros au budget de l’Éducation en 2013 : L’abrogation de la [Loi Debré](https://blogs.mediapart.fr/emancipation/blog/030413/financement-public-de-lenseignement-prive-lomerta-continue) permettrait de faire cesser ce privilège. Tout en respectant la « liberté de l’enseignement » inscrite au code de l’Éducation (L.151.1) qui n’implique pas un financement public. »
Si y'a moyen de la mettre, avec le lien vers médiapart qui m'a l'air interessant, ce serait bien.
Le lien vers le livret laicité si besoin: https://avenirencommun.fr/le-livret-laicite/

**Comment by lucasgautheron** [comment]
Très bien, fait!

**Comment by sarah48** [comment]
J'ai modifié la fin du 2ème paragraphe, avec cette phrase: "L'Etat y reconnaît donc et organise 4 grands cultes, en particulier en salariant les ministres de ces cultes, et la religion y est enseignée à l'école primaire et au collège." (y'avait une répétition avant)
