### ISSUE TITLE
6.10 Nous construirons 80 000 logements pour les jeunes

### ISSUE THREAD

**Issue by LVAI** [Insoumis/programme-macron#31]
[insert] from Scalpi

# 6.10 Nous construirons 80 000 logements pour les jeunes

## GRANDE MEFIANCE

Macron propose la construction de 80 000 logements pour les jeunes, 60 000 pour étudiants et 20 000 pour les jeunes actifs. Quels types de logements, sociaux, publics, privés ? Nous prévoyons la construction de 1 million de logements publics en 5 ans soit, 18 milliards ce qui nous fait le logement à 180 000 €. Les modes de financement sont diverses et prévus, il y a également une part d’investissement. Macron avec ses 80 000 logements, il les finance comment ? Nous n’avons pas, sauf erreur, vu quelconque chiffrage sur ce projet et rien du tout dans les 50 milliards. Le projet de Macron coûterait 10,8 milliards sur la base de notre calcul. Ils n’y sont tout simplement pas dans son budget.

**Comment by Zedhyn** [comment]
lien LAEC : 
https://avenirencommun.fr/livret-de-lenseignement-de-recherche/

P.S : il n'y pas pas d'encart spécifique sur le site de LAEC, le contenu du programme de JLM concernant les logements étudiant est uniquement inscrit dans le livret thématique "Le choix du savoir", lien ci-dessus.
