### ISSUE TITLE
10.7 « Nous raccourcirons les délais de jugement pour les litiges inférieurs à 4000 euros.» 

### ISSUE THREAD

**Issue by ClaXus** [Insoumis/programme-macron#32]
## **10.7 « Nous raccourcirons les délais de jugement pour les litiges inférieurs à 4000 euros.»** 
La procédure les concernant sera entièrement dématérialisée et la décision sera rendue en ligne.

### Pourquoi pas mais...

Cette mesure part d’une bonne attention, car elle permet de désengorger les tribunaux de proximité et de faire en sorte que les litiges soient réglés plus rapidement. Mais le manque de moyens actuel risque bien d’empêcher sa bonne réalisation. Aujourd’hui, ce sont les juges de proximité qui s’occupent de ces litiges. Or, si ces derniers s'occupent des Tribunaux de Première Instance comme le laisse entendre la mesure précédente, qui fera ce travail supplémentaire ? Si l’on cumule cela au sous-effectif des juridictions, cette proposition apparaît comme difficilement tenable sans moyens supplémentaires mis en œuvre.

Extrait du livret justice :
Les juridictions sont en sous-effectif constant et souffrent d’une détérioration sans précédent de leurs locaux : les tribunaux croulent sous les dossiers entassés dans les couloirs et leurs équipements informatiques sont obsolètes.
 https://avenirencommun.fr/le-livret-justice/ 

CODE XML : 
      <engagement>Nous raccourcirons les délais de jugement pour les litiges inférieurs à 4000 euros.</engagement>
      <mesure>La procédure les concernant sera entièrement dématérialisée et la décision sera rendue en ligne.</mesure>
      <analyse tag="info" description="Pourquoi pas, mais...">Cette mesure part d’une bonne attention, 
        car elle permet de désengorger les tribunaux de proximité et de faire en sorte que les litiges soient réglés plus rapidement.
        Mais le manque de moyens actuel risque bien d’empêcher sa bonne réalisation. 
        Aujourd’hui, ce sont les juges de proximité qui s’occupent de ces litiges. 
        Or, si ces derniers s'occupent des Tribunaux de Première Instance comme le laisse entendre la mesure précédente, qui fera ce travail supplémentaire ? Si l’on cumule cela au sous-effectif des juridictions, cette proposition apparaît comme difficilement tenable sans moyens supplémentaires mis en œuvre.
      </analyse>

**Comment by lucasgautheron** [comment]
Validé (avec modifs)
