### ISSUE TITLE
7.3 Association intégristes

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#33]
C'est déjà le cas, [les associations coupables de « dérives sectaires » peuvent être dissolues par la voie judiciaire, et une dissolution administrative peut aussi être prononcée contre elles](http://www.associations.gouv.fr/1006-dissoudre-une-association.html#cas-8f2a79-4). Et [Plusieurs associations cultuelles ont d'ailleurs été dissolues ces dernières années](http://www.la-croix.com/Religion/Islam/Dissolution-de-trois-associations-cultuelles-liees-a-la-mosquee-de-Lagny-2016-01-13-1404007). 

C'est aussi déjà le cas pour la fermeture des lieux de culte, [dont au moins une quinzaine ont été fermés au cours de l'année dernière](http://www.rtl.fr/actu/societe-faits-divers/terrorisme-etat-d-urgence-operation-sentinelle-un-bilan-mitige-pour-des-mesures-critiquees-7783973780).

Par ailleurs, le fait de retenir comme motif le fait de « s'attaquer à la République » peut amener certaines dérives, et « s'attaquer à la République »  n'est pas du tout la même chose que de faire « l'apologie du terrorisme ». Il faut aussi faire attention à respecter [l'article 10 de la déclaration des droits de l'Homme et du citoyen](http://www.jurizine.net/2005/09/01/33-articles-10-et-11-ddhc-liberte-dopinion-et-liberte-dexpression) sur la liberté d'opinions.

Les détails du programme parlent aussi de conditionner « les différentes formes de partenariats publics (…) au respect strict des principes républicains ». Si ça peux sembler logique, il faut aussi faire attention aux dérives possibles, comme dans le cas de [« chartes de la laïcité » adoptées récemment par certaines collectivités locales et rejetées par la justice](http://www.droitpublic.net/spip.php?article5596).
Il est aussi question de conditionner « le soutien des communes à la construction de mosquées » aux mêmes principes, mais il faut rappeler que [le financement des lieux de cultes par l'Etat ou les collectivité est interdit](http://www.slate.fr/story/121757/infographie-lieux-de-culte-france), à l'exception [ de l'Alsace-Moselle, qui sont sous concordat](https://fr.wikipedia.org/wiki/Concordat_en_Alsace-Moselle) ([voir à ce sujet le point 7.1](http://analysons-macron.fr/#c7m1)).

**Comment by LVAI** [comment]
Done
