### ISSUE TITLE
1.3 Nous rétablirons les exonérations de cotisations sociales sur les heures supplémentaires

### ISSUE THREAD

**Issue by LVAI** [Insoumis/programme-macron#35]
[update] from Lutine (liens laec)

https://laec.fr/s28m2

**Comment by lucasgautheron** [comment]
vide ?

**Comment by LVAI** [comment]
Bah oui Monsieur Lucas : je crée vide pour dire que je suis dessus et j'update ^^ C'est votre proposition je vous rappelle ;)
