### ISSUE TITLE
8.2 Arrangements fiscaux entre États et entreprises multinationales

### ISSUE THREAD

**Issue by Gaspard5** [Insoumis/programme-macron#40]
Dites-moi ce que vous en pensez ?

8.2
Nous lutterons contre les arrangements fiscaux entre États et entreprises multinationales.»
Ils faussent la concurrence en Europe, comme celui entre Apple et l’Irlande qui a été sanctionné. La France se montrera exemplaire en ce domaine.

Méfiance

   [Le dernier rapport réalisé par Eurodad](http://ccfd-terresolidaire.org/IMG/pdf/rapporteurodad2016_la_lutte_contre_levasion_fiscale_en_europe.pdf) (Réseau Européen sur la Dette et le Développement) en 2016 décrit un **[bilan français en demi-teinte](http://ccfd-terresolidaire.org/infos/partage-des-richesses/paradisfiscaux/lutte-contre-l-evasion-5714)**. Le **[nombre de rescrits fiscaux en Europe a triplé](https://www.lesechos.fr/07/12/2016/lesechos.fr/0211570754632_evasion-fiscale---l-europe-multiplie-les-arrangements-avec-les-multinationales.htm)** entre 2013 et 2015. Et ce, malgré les récentes révélations du Luxleaks qui ont dévoilé les pratiques de **dumping fiscal** pratiquées en Europe, notamment par le Luxembourg. Pire encore, le président de la Commission Européenne avoue être [« politiquement responsable »](http://www.lemonde.fr/evasion-fiscale/article/2014/11/12/luxleaks-jean-claude-juncker-promet-de-lutter-contre-l-evasion-fiscale_4522432_4862750.html) d’un tel système alors que les lanceurs d’alerte se sont vus [condamnés par la justice du Grand-Duché](https://twitter.com/jlmelenchon/status/748208012163227648).

   En France, les politiques fiscales du gouvernement sont particulièrement **[critiquées](http://ccfd-terresolidaire.org/infos/partage-des-richesses/paradisfiscaux/lutte-contre-l-evasion-5714)**. Le CIR (Crédit Impôt Recherche) et le CICE (Crédit d’Impôt pour la Compétitivité et l’Emploi) coûtent plus de 25 milliards d’euros par an aux caisses de l’État. Ces dispositifs, devenus des [**allègements de charges**](http://www.latribune.fr/economie/france/emmanuel-macron-confirme-la-transformation-du-cice-en-allegements-de-charges-485428.html) offerts aux entreprises, [n’ont pas démontré leur efficacité.](http://www.lemonde.fr/economie/article/2017/03/22/l-efficacite-du-cice-continue-de-faire-debat_5098813_3234.html)
	
   [Impulsé par Macron en 2013](http://lelab.europe1.fr/Qui-est-Emmanuel-Macron-le-nouveau-ministre-de-l-Economie-16140) alors conseiller de l’Élysée, le CICE s’est révélé [**sans effet** sur l’investissement](http://www.lemonde.fr/economie/article/2017/03/22/l-efficacite-du-cice-continue-de-faire-debat_5098813_3234.html). En 2016, l’entreprise Sanofi annonce la **[suppression de 600](http://www.liberation.fr/futurs/2016/02/02/chez-sanofi-les-salaries-ont-moins-la-sante-que-les-actionnaires_1430614)** postes dans les années à venir, malgré les 17 millions du CICE et les 125 millions du CIR qu’elle reçoit chaque année. Résultat ? 7 milliards de bénéfices et 3,8 milliards de dividendes pour ses actionnaires. Alors, qui fait des cadeaux fiscaux aux multinationales ?

Que dit LAEC ?

[Obliger les entreprises à déclarer leurs résultats pays par pays et taxer les bénéfices des entreprises là où ils sont réalisés](https://laec.fr/s37m2)

[Réévaluation des niches fiscales inutiles](https://laec.fr/s36m2)

[Agir contre l'évasion fiscale au niveau international, notamment en organisant le blocus des paradis fiscaux](https://laec.fr/s37m4)

[Allouer les 41 milliards du CICE au financement de la transition écologique](http://www.capital.fr/a-la-une/politique-economique/programme-de-jean-luc-melenchon-relance-economique-emploi-retraite-ses-idees-pour-2017-1215004)

**Comment by lucasgautheron** [comment]
Salut !

Je pense que le CICE et le CIR sont HS : la question ici est plutôt celle par exemple des rescrits type luxleaks. On pensait aussi parler du CETA/TAFTA : Macron leur est favorable, mais ils prévoient des tribunaux arbitraux, ce qui rendre caduque cette lutte (il faudrait une référence à ce sujet)

Merci pour ta proposition

**Comment by LVAI** [comment]
"accords" fiscaux plutôt que "rescrits", non ?
Macron veut supprimer le CICE oui voilà comme dit lucas du coup ça n'appuie pas la thèse.

**Comment by sarah48** [comment]
Salut, j'ai mis des liens sur CETA/TAFTA sur le salon macroverdose si ça t'interesse, je pensais que c'était la bonne mesure pour en parler. Sinon ça me semble super :) Je mettrais juste "E.Macron" ou "Emmanuel Macron" plutot que juste "Macron"

**Comment by Gaspard5** [comment]
Merci pour vos messages. Je vais reprendre ça et faire un paragraphe sur le CETA/TAFTA.

Les CIR/CICE me paraissent être dans le sujet puisque c'est de l'optimisation fiscale qui ne dit pas son nom mais vous avez déjà fait un bon gros paragraphe sur le CICE (qui est presque un peu gentil en omettant tout l'argent qui a été détourné de la recherche publique par ce procédé censé favoriser la R&D des entreprises). Je vais réduire ça et détailler la question des rescrits fiscaux.

**Comment by LVAI** [comment]
@Gaspard5 à la limite coupe / colle ton paragraphe CIR / CICE sur l'issue #30

**Comment by ClaXus** [comment]
Il faudrait aussi parler de l'harmonisation fiscale européenne parmi nos réponses selon moi !
J'ajouterai aussi que l'UE non renégociée empêche la remise en cause de tout ce système, car les lobbys sont surpuissants et disposent encore de bien des possibilités sans l'Irlande (voire https://www.bruno-leprince.fr/politique-a-gauche/148-le-grand-trafic-neoliberal-les-lobbys-en-europe-9782364880931.html )

**Comment by sarah48** [comment]
Dans l'article du diplo sur les tribunaux d'arbitrage ( http://www.monde-diplomatique.fr/2014/06/BREVILLE/50487 ), y'a deux citations qui concernent l'évasion fiscale:

(note de moi: dans le cadre de ce genre de traités qui amènent des tribunaux d'arbitrage, les gouvernements doivent garantir) "la liberté pour l’entreprise de transférer son capital (une société peut sortir des frontières avec armes et bagages, mais un Etat ne peut pas lui demander de partir !). "

Et (la il s'agit d'empêcher une forme de contrôle des capitaux): "Les mesures prises par Buenos Aires pour faire face à la crise de 2001 (contrôle des prix, limitation de sortie des capitaux...) ont été systématiquement dénoncées devant les cours d’arbitrage. "

Après, à voir si ça correspond vraiment au sujet de cette mesure.

**Comment by lucasgautheron** [comment]
oui tout à fait à mon avis.

**Comment by LVAI** [comment]
@Gaspard5 tu peux nous dire ou t'en es sur cette issue ?

**Comment by Gaspard5** [comment]
Voilà, j'ai repris dans un autre sens. J'aurais plus de temps pour corriger/sourcer ce soir ! J'attends vos avis.


Version non sourcée

## **Méfiance**
	
Cette déclaration d’intention du programme d'Emmanuel Macron s’inscrit dans la politique européenne de lutte contre la fraude fiscale, démarrée après les révélations du « Luxleaks » en 2014. Au coeur du scandale ? Des accords fiscaux avec les Etats qui permettent aux multinationales d’échapper en partie ou totalement à l’impôt dans les pays européens où elles sont installées.

Si de facade la transparence est de mise, dans les faits, les rescrits fiscaux ont été multipliés par trois entre 2013 et 2016. Face à l’augmentation de ces pratiques fiscales agressives, Emmanuel Macron ne précise pas du tout comment il compte mener cette lutte. 

Par ailleurs, E. Macron s’étant prononcé en faveur du traité de libre-échange CETA, il se pose un problème de taille : les tribunaux d’arbitrage. Ceux-ci protègent les sociétés étrangères contre toute décision publique (loi, règlement, norme) qui pourrait nuire à leurs investissements. Concernant l’evasion fiscale, une entreprise pourra désormais transférer son capital librement sans qu’un État, à l’inverse, puisse lui demander de partir. De manière générale, cela signifie la fin du contrôle des capitaux, même en cas de crise. Dans un tel contexte, toute politique publique de lutte contre l’évasion fiscale sera vouée à l’échec. La loi des multinationales et des investisseurs se placerait au-dessus des Etats, au détriment des droits sociaux et environnementaux.

Enfin, il apparaît aujourd’hui une question cruciale pour lutter contre l’évasion fiscale : l’harmonisation fiscale entre les pays de l’Euro. Tant que les membres continueront de mener entre eux une guerre fiscale et fratricide, aucune politique de lutte contre l’exil fiscal ne sera efficace.

**Comment by sarah48** [comment]
Ca m'a l'air très bien, en rajoutant les liens.
Pour illustrer le soutien de Macron au CETA, tu pourrais mettre ce lien:
http://www.liberation.fr/elections-presidentielle-legislatives-2017/2017/02/15/le-ceta-un-accord-decrie-par-la-plupart-des-candidats-a-la-presidence_1548434

Sinon, peut etre, juste mettre une estimation du montant de l'évasion fiscale, si tu trouves, pour marquer un peu plus les esprits.

**Comment by Gaspard5** [comment]
## **Méfiance**

Cette déclaration d’intention du programme d'Emmanuel Macron s’inscrit dans la politique européenne de lutte contre la fraude fiscale, démarrée après [les révélations du « Luxleaks » en 2014](http://www.liberation.fr/futurs/2014/11/05/luxleaks-les-avantages-fiscaux-du-luxembourg-denonces_1137297). Au coeur du scandale ? Des accords fiscaux avec les Etats qui permettent aux multinationales d’échapper en partie ou totalement à l’impôt dans les pays européens où elles sont installées. Résultat ? La fraude fiscale en France coûte chaque année entre [60 et 100 milliards d'euros](http://www.capital.fr/a-la-une/interviews/la-fraude-fiscale-fait-perdre-a-la-france-entre-60-et-100-milliards-d-euros-par-an-1135842) à l'Etat, [l'équivalent de son déficit budgétaire.](http://www.lefigaro.fr/flash-eco/2017/01/17/97002-20170117FILWWW00081-france-deficit-budgetaire-en-baisse-a-689-milliards-d-euros-en-2016.php)

Si de facade la transparence est désormais de mise, dans les faits, [les rescrits fiscaux ont été multipliés par trois entre 2013 et 2016](http://ccfd-terresolidaire.org/infos/partage-des-richesses/paradisfiscaux/lutte-contre-l-evasion-5714). Face à l’augmentation de ces pratiques fiscales agressives, Emmanuel Macron ne précise pas du tout comment il compte mener cette lutte.

Par ailleurs, E. Macron s’étant prononcé [en faveur du traité de libre-échange CETA](http://www.lemonde.fr/les-decodeurs/article/2017/02/13/emmanuel-macron-seul-candidat-a-la-presidentielle-ouvertement-favorable-au-ceta_5078997_4355770.html), il se pose un problème de taille : les [tribunaux d’arbitrage](http://www.monde-diplomatique.fr/2016/02/BARLOW/54744). Ceux-ci protègent les sociétés étrangères contre toute décision publique (loi, règlement, norme) qui pourrait nuire à leurs investissements. Concernant l’évasion fiscale, une entreprise pourra désormais transférer son capital librement sans qu’un État, à l’inverse, puisse lui demander de partir. De manière générale, cela signifie la fin du contrôle des capitaux, même en cas de crise. Dans un tel contexte, toute politique publique de lutte contre l’évasion fiscale sera vouée à l’échec. La loi des multinationales et des investisseurs se placerait au-dessus des Etats, au détriment des droits sociaux et environnementaux.

Enfin, il apparaît aujourd’hui une question cruciale pour lutter contre l’évasion fiscale : [l’harmonisation fiscale entre les pays de l’Euro](https://www.lesechos.fr/06/10/2015/lesechos.fr/021383742289_impots---la-concurrence-fiscale-europeenne-couterait-15-milliards-a-la-france.htm). Tant que les membres continueront de mener entre eux une guerre fiscale et fratricide, aucune politique de lutte contre l’exil fiscal ne sera efficace.

## **Que dit LAEC ?**

[Obliger les entreprises à déclarer leurs résultats pays par pays et taxer les bénéfices des entreprises là où ils sont réalisés](https://laec.fr/s37m2)

[Agir contre l'évasion fiscale au niveau international, notamment en organisant le blocus des paradis fiscaux](https://laec.fr/s37m4)

[Allouer les 41 milliards du CICE au financement de la transition écologique](http://www.capital.fr/a-la-une/politique-economique/programme-de-jean-luc-melenchon-relance-economique-emploi-retraite-ses-idees-pour-2017-1215004)

[Réguler la finance internationale](https://laec.fr/section/19/mettre-au-pas-la-finance)

[Pour une politique volontariste d'harmonisation sociale et fiscale en Europe](https://laec.fr/s51m7)
