### ISSUE TITLE
6.9 Nous demanderons à chaque lycée professionnel et université de publier ses résultats

### ISSUE THREAD

**Issue by Zedhyn** [Insoumis/programme-macron#41]
[insert] from Zedhyn

# 6.9 Nous demanderons à chaque lycée professionnel et université de publier ses résultats

(Débouchés, salaires, etc) sur les 3 dernières années.

## MÉFIANCE
La publication des résultats engendre une mise en concurrence entre les établissements ou universités comme aux USA. Le risque que cela provoque des "niches universitaires" pour prendre le cas des facultés est évident, c'est à dire des universités qui excellent dans certaines filières et en délaissent d'autres. 
Avec cette conception des lycées professionnels  et de l'enseignement supérieur, avant même le début de leur cursus universitaire, les étudiants sauront si le lycée ou la faculté qu'ils auront choisi leur donnera un avantage ou, au contraire, un handicap lors de la recherche d'emploi.
On peut également se questionner sur l'intérêt de cette mesure qui n'évoque pas la finalité de ces publications. 

Un autre système bien plus vertueux est possible grâce à une indépendance accrue des chercheurs, un dialogue renouvelé entre le savoir et la société et la reconnaissance du caractère collectif de la recherche qui implique justement une sortie de la "compétition généralisée".

 Qu'en dit l'Avenir en Commun ?
- [https://laec.fr/s75]

**Comment by Zedhyn** [comment]
(Débouchés, salaires, etc) sur les 3 dernières années.

**Comment by lucasgautheron** [comment]
[01:10] lucasgautheron: haha, je dirais Orange, méfiance
[01:10] lucasgautheron: pour deux raisons : difficultés techniques, et aussi l'idéologie derrière, évaluation, concurrence, mais pas + de moyens

**Comment by Zedhyn** [comment]
Je suis d'accord avec toi. La question de la concurrence étant prépondérante dans cette proposition,il cherche à mettre en oeuvre un système à l'américaine qui va sectariser les filières et les universités entre elles

**Comment by Zedhyn** [comment]
Analyse terminée, en attente de validation par Lucas

**Comment by lucasgautheron** [comment]
* "niches universitaires" est entre guillemets : cela fait référence à une notion reconnue ? si oui, un lien serait nécessaire. sinon, à expliciter.
 *  > Avec cette conception des lycées professionnels et de l'enseignement supérieur, avant même le début de leur cursus universitaire, les étudiants sauront si le lycée ou la faculté qu'ils auront choisi leur donnera un avantage ou, au contraire, un handicap lors de la recherche d'emploi.

   ? cela semble positif, formulé de cette façon. C'est un peu le but de la mesure aussi?
 * > On peut également se questionner sur l'intérêt de cette mesure qui n'évoque pas la finalité de ces publications.

 Ben ça justement ? Savoir quel établissement est le plus adapté à un projet scolaire.
 * > Un autre système bien plus vertueux est possible grâce à une indépendance accrue des chercheurs, un dialogue renouvelé entre le savoir et la société et la reconnaissance du caractère collectif de la recherche qui implique justement une sortie de la "compétition généralisée".

Un peu HS selon moi. Le vrai problème est le dogme libéral de la concurrence et de l'évaluation; C'est un pb philosophique. Mais je suis mal renseigné sur le sujet

**Comment by Zedhyn** [comment]
- Niche universitaire est un terme que j'ai vu : soit dans le programme de JLM soit dans un article web je me rappelle plus :/ mais il n'était pas défini, il est sous entendu des universités privilégiées par les étudiants, en raison de leur classement national.

- Ce que je voulais exprimer c'est le fait qu'avec cette logique de "compétition" des facultés ou des lycées seront stéréotype en "ceux qui sortent de là bas sont des gros nuls" donc ça dévalorise l'image de la faculté qui aurait un mauvais classement, de mauvais résultat. C'est la fin de la phrase qui compte. Le but de la mesure est davantage, comme les ricains, de faire de certaines universités des pôles d'excellence qui seraient alors, dommageable à toutes les autres fac ayant le même cursus et qui seraient moins bien classé (à l'image de la carte scolaire, on prend les meilleurs et les plus nuls vont dans les autres fac)

- C'est une remarque de Lutine qui m'a dit après avoir lu mon analyse qu'il manquait  une phrase pointant du doigt le fait que cette proposition ne dit pas ce qu'elle est censé créer en retour. en gros "publier ses résultats pour ???" 

- Au départ j'hésitais à écrire cela, c'était pour faire transition avec le programme de JLM et je voulais mettre en avant le fait que l'on propose une approche plus globalisée, systémique.
Du coup j'ai fait une phrase tiré d'un extrait de notre programme pour faire liaison, page 10/24 du livret **https://avenirencommun.fr/livret-de-lenseignement-de-recherche/**
==> Il reste cependant accessoire (le dernier point). on peut, soit mettre uniquement "un autre système bien plus vertueux est possible" (histoire de susciter la curiosité du lecteur). ou carrément enlever la phrase.

**Comment by Zedhyn** [comment]
Le risque que cela provoque des "niches universitaires" [...] c'est à dire des universités qui excellent dans certaines filières et en délaissent d'autres

=> on peut remplacer "et en délaissent d'autres" par "au détriment de toutes les autres"
