### ISSUE TITLE
9.6 Service sanitaire

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#44]
Cette mesure pose plusieurs problèmes.
Tout d'abord, ces étudiants continueront-ils à suivre leurs études pendant cette période, alors qu'on sait que les études de médecines sont particulièrement exigeantes ?
Ensuite, seront-ils rémunérés ? On sait que beaucoup d'étudiants actuellement sont déjà obligés de travailler pour financer leur études, d'autant plus en médecine, ou «[ il est très difficile, voire pratiquement impossible de réussir le concours sans suivre, parallèlement aux cours de première année, une préparation spécifique (…) dont le coût se chiffre généralement en milliers d’euros](http://www.la-croix.com/Famille/Education/Ce-que-coutent-des-etudes-en-France-2014-03-18-1122131) ».

Quant aux domaines de la « prévention dans les écoles et les entreprises », ce sont les domaines de la médecine scolaire et de la médecine du travail. Il faut noter que dans le programme d' « En Marche », il n'y a **aucune** mesure concernant ces deux secteurs (à part une [vague mesure sur les AVS](http://analysons-macron.fr/#c9m9)). Il n'y a donc rien de prévu pour soutenir les médecins, infirmiers, psychologues scolaires et assistants sociaux de la médecine scolaire, ni la [Protection Maternelle et Infantile]( https://fr.wikipedia.org/wiki/Protection_maternelle_et_infantile) qui peut être amenée à intervenir en milieux scolaire.

Pour la médecine du travail, la question de la souffrance au travail est totalement évacuée, alors que  «[ chaque jour, une personne se suicide en France à cause de son travail](http://www.psychologies.com/Travail/Souffrance-au-travail/Stress-au-travail/Articles-et-Dossiers/Quand-le-travail-fait-mal/Travail-pourquoi-tant-de-suicides) ».
Dans ce domaine,[ la loi El Khomri soutenue par « En Marche »](http://analysons-macron.fr/#c2m4) aggrave encore les choses : [Plus de visite médicale à l'embauche, visite médicale tous les 5 ans au lieu de 2 avant](http://www.20minutes.fr/sante/1989123-20170103-loi-travail-change-texte-sante-salaries)...

« En Marche » n'envisage non plus aucune aide pour les inspecteurs du travail, chargés d'assurer l’application effective du droit du travail, alors qu['il 'y a maintenant moins de 2000 inspecteurs pour contrôler presque 2 millions d'entreprises, après la loi Sapin de 2014](http://www.lemonde.fr/emploi/article/2014/02/03/qui-veut-la-mort-de-l-inspection-du-travail_4359281_1698637.html), imposée alors que[ E.Macron était le principal conseiller économique de F.Hollande](http://www.huffingtonpost.fr/2017/01/19/emmanuel-macron-assume-de-moins-en-moins-son-bilan-de-conseiller/)...

**Comment by lucasgautheron** [comment]
Super ! Quelle mention plus couleur ?

**Comment by sarah48** [comment]
Je dirais "C'est flou et très insuffisant" en orange
