### ISSUE TITLE
9.9 AVS

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#45]
Il n'y aucun détail de plus concernant cette mesure très floue. Suite à la [réforme de 2016](http://www.europe1.fr/societe/auxiliaires-de-vie-scolaire-polyhandicapes-le-plan-de-francois-hollande-sur-le-handicap-2749379), les Auxiliaires de Vie Scolaire (AVS) sont devenus des Accompagnants des Elèves en Situation de Handicap (AESH). Alors qu'il y a aujourd'hui environ 80 000 AESH pour environ [280 000 élèves handicapés dans l'Education nationale (privée et publique)](http://www.education.gouv.fr/cid207/la-scolarisation-des-eleves-en-situation-de-handicap.html), [ce plan prévoit 32 000 recrutements d'ici 2021](http://www.20minutes.fr/societe/1848519-20160519-contrats-aides-auxiliaires-vie-scolaire-avs-vont-etre-transformes-cdi).

Mais le plus gros problème concernant ces travailleurs est leur grande précarité. Suite à la loi de 2016, il sont embauchés pour des CDD d'un an minimum (mais ils peuvent ne pas être reconduits après le 1er mois de période d'essai), qui ne se transforment en CDI que si ils sont reconduits six ans de suite. 
Comme l'explique [ce témoignage édifiant](http://leplus.nouvelobs.com/contribution/1517828-auxiliaire-de-vie-scolaire-et-en-cdd-depuis-6-ans-je-suis-une-travailleuse-precaire.html), « la grande majorité des AVS » ne travaillent qu'à mi-temps.

La loi 2016 prévoyait qu'en 2021, « [ce seront 50.000 professionnels (en équivalents temps-plein) qui seront disponibles](http://www.20minutes.fr/societe/1848519-20160519-contrats-aides-auxiliaires-vie-scolaire-avs-vont-etre-transformes-cdi) ». Avec actuellement environ 1 AESH à temps plein pour 6 élèves handicapés scolarisés, [même si tous les élèves handicapés (mais la plupart) n'ont pas besoin d'un accompagnement, et que ceux qui en ont besoin n'en ont pas forcément besoin à plein temps](http://cache.media.education.gouv.fr/file/2013/10/5/2012-162_rapport_244105.pdf), les besoins restent élevés, et on imagine mal « En Marche » les combler, étant donné la faiblesse des investissements prévus en matière d'éducation. Nous ne savons pas non plus ce que signifie un« emploi stable » pour eux ...

De plus, les AESH ne bénéficient d'aucune formation spécifique, alors qu'ils font face à de nombreux types de maladies différentes qui nécessitent une connaissance préalable et un comportement adapté. [Ceci est aussi vrai pour les enseignants](http://blog.francetvinfo.fr/l-instit-humeurs/2016/05/21/handicap-a-lecole-lenvers-du-decor.html).

A cela s'ajoute [des équipements insuffisants concernant l'accessibilité à l'école](http://blog.francetvinfo.fr/l-instit-humeurs/2016/05/21/handicap-a-lecole-lenvers-du-decor.html), problème qui n'est pas évoqué dans le programme d' « En Marche ».

**Comment by LVAI** [comment]
qui **ne** se transforment en CDI **que** si ils sont reconduits six ans de suite ?
Je rajouterai aussi une ligne sur ce que peut bien signifier "les enfants qui en ont besoin" : tous les enfants handicapés ou pas ? Comment se fait la sélection ?

**Comment by sarah48** [comment]
J'ai corrigé pour le 1er
J'ai reformulé le 3ème paragraphe sans trop rentrer dans les détails
