### ISSUE TITLE
7.4 Langue française et nationalité

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#47]
"C'est déja le cas", orange? ou vert

La maitrise de la langue française est [déjà un des principaux critères d'obtention de la nationalité française](https://www.service-public.fr/particuliers/vosdroits/F2213). Depuis [2006](http://www.vie-publique.fr/actualite/dossier/integration/contrat-accueil-integration-parcours-obligatoire-condition-installation-durable.html), un [Contrat d'Accueil et d'Intégration (CAI)](http://www.edrh-sophiaantipolis.com/public/docs/page/souspage/53.pdf) est obligatoire pour tout nouvel arrivant désireux d'acquérir la nationalité française. Suite à un test de langue française, si nécessaire, [le candidat devait suivre une formation linguistique gratuite, pour finalement décrocher le diplôme initial de langue française (DILF), qui valide le 1er niveau identifiable en français (niveau A1.1)](http://www.superprof.fr/blog/integration-par-les-cours-de-fle/).

En 2012, l'exigence linguisitique s'est élevée, avec la mise en place d'un [Test de Connaissance du Français (TCF, ou Test d'Evaluation du Français, TEF)](http://www.ciep.fr/tcf-anf) pour les candidats à la nationalité, exigeant le niveau B1 pour l'obtenir.
En 2016, la formation linguisitique est renforcée, puisqu'un [Contrat d’Intégration Républicaine (CIR)](https://www.service-public.fr/particuliers/vosdroits/F17048) a remplacé le CAI, mettant en place pour le candidat un [« parcours personnalisé d’intégration républicaine »](http://www.immigration.interieur.gouv.fr/Accueil-et-accompagnement/Le-parcours-personnalise-d-integration-republicaine) d’une durée de cinq ans. Le CIR prescrit une formation linguistique pour mener l'étranger au niveau A1. [Si le candidat valide ce niveau et satisfait aux autres exigences, il obtiendra un titre de séjour pluriannuel](http://normandie.drdjscs.gouv.fr/sites/normandie.drdjscs.gouv.fr/IMG/pdf/genese_de_la_politique_d_accompagnement_linguistique_des_etrangers_en_france_.pdf). Une nouvelle formation est alors prévue pour atteindre le niveau A2. Au bout de 5 ans, il pourra prétendre à une carte de résident si il atteint ce niveau.[ Une autre formation est prévue pour atteindre le niveau B1](http://www.ofii.fr/tests_197/envie_d_approfondir_vos_connaissances_linguistiques_en_langue_francaise_1349.html?preview=oui). Ces formations sont gratuites.

On peut donc s'étonner de la promesse de donner un « droit à une formation linguistique suffisante pour atteindre le niveau B1 » dans les détails du programme d' « En Marche », alors que ce droit existe déjà...

Quant aux mineurs, ils sont inscrits dans des établissements scolaires, et il existe des classes pour non francophones (dits « [allophones ](https://fr.wikipedia.org/wiki/Allophone_(sociolinguistique))» ) destinées aux élèves nouvellement arrivés. Néanmoins, ces classes (dites « UPE2A ») [manquent de moyens](http://www.sudeducation.org/Pour-une-reelle-prise-en-charge.html), et « En Marche » ne prévoit pas de les soutenir.

**Comment by lucasgautheron** [comment]
Je pense qu'il faut comprendre la mesure comme le fait que d'autres critères s'effaceront. 
Sinon merci, ajouté, en attendant peut être une nuance à cause de ça :)

**Comment by sarah48** [comment]
Y'a rien qui dit dans le programme que les autres critères s'effaceront. A mon avis, comme souvent, cette mesure, ce sont des paroles en l'air, rien d'autre. J'ai pas envie de sur-interpreter ses propos en lui pretant des intentions positives qu'à mon avis, il n'a sans doute pas. Si il veux effacer les autres critères, qu'il le dise au moins dans les détails de son programme. En plus il était au gouvernement en quand il y a eu la réforme de 2016, qui n'a pas du tout assoupli les autres critères.

**Comment by lucasgautheron** [comment]
Haha, ok, je dis juste que je le comprends ainsi.
