### ISSUE TITLE
5.3 "Nous donnerons aux policiers et aux gendarmes un nouveau pouvoir" 

### ISSUE THREAD

**Issue by NightGlow24** [Insoumis/programme-macron#62]

**Comment by NightGlow24** [comment]
MÉFIANCE 

Dans le cadre d'un [contrôle judiciaire](http://www.justice.gouv.fr/justice-penale-11330/les-decisions-judiciaires-pour-les-mineurs-12123/les-mesures-de-probation-et-les-peines-21093.html), il est possible d'astreindre la personne mise en examen à plusieurs obligations dont celle de ne pas se rendre dans certains lieux. 

Afin que cette proposition ne soit pas inconstitutionnelle, le policier ne pourra pas prendre seul ce pouvoir d'injonction. En effet, la mise en oeuvre de ce nouveau pouvoir se fera nécessairement sous le contrôle du juge des libertés et de la détention (JLD) : c'est donc le juge qui décidera ou non d'appliquer cette astreinte aux personnes qui lui seront signalées par la police. 

La création d'un tel pouvoir nécessite un aménagement de la procédure pénale et cela implique donc une loi votée par le Parlement. Cette mesure demeure imprécise puisque son objectif premier est d'accélérer la mise en oeuvre des astreintes prévues par l'injonction policière mais cette même injonction doit être réalisée sous le contrôle du juge ce qui suppose une procédure rigoureuse qui nuirait à l'immédiateté souhaitée initialement.

**Comment by sarah48** [comment]
Juste quelques virgules dans la dernière phrase: ->"Cette mesure demeure imprécise, puisque son objectif premier est d'accélérer la mise en oeuvre des astreintes prévues par l'injonction policière, mais cette même injonction doit être réalisée sous le contrôle du juge, ce qui suppose une procédure rigoureuse qui nuirait à l'immédiateté souhaitée initialement."

**Comment by LVAI** [comment]
commited
