### ISSUE TITLE
3.6 « Nous ferons de la France le leader mondial de la recherche sur la transition environnementale.»

### ISSUE THREAD

**Issue by plapla-fi** [Insoumis/programme-macron#63]
Les spécialistes étrangers bénéficieront de formalités d’accueil accélérées.

**Comment by Scalpi** [comment]
POURQUOI PAS MAIS 
Nous avons vu qu'EN MARCHE souhaite consacrer 15 milliards à la transition énergétique. Rappelons à ce propos qu'il souhaite fermer les 4 centrales à charbon existant encore sur les 5 ans (on parle ici de convertir 3 TW de capacité en ER) et limiter la part du nucléaire de 75% à 50% d'ici 2025. Nous savons qu'il faut consacrer plus de 30 milliards par an en moyenne pour faire une transition efficace (selon différents scénarii, Negawatt, Afterres, etc). On voit donc à quel point le projet d'EM n'est pas crédible avec 15 milliards sur 5 ans.
Ensuite, il propose ici de faire de la France le leader de la recherche sur la transition environnementale. Sauf erreur, nous n’avons pas vu de chiffrage de montant qui serait consacré à ce point précis. Par contre, nous lisons qu’il facilitera l’arrivée de spécialistes étrangers sur la question. Pourquoi pas mais nous savons que nous avons les compétences nécessaires en France. Par conséquent, c'est en se mettant réellement en action que nous montrerons aux autres qu'avec un plan crédible et sérieusement chiffré, on y arrive.  
La réalité, c’est qu’une telle ambition quand elle n’est pas chiffrée est une déclaration d’intention, sans plus.

**Comment by lucasgautheron** [comment]
je pense la remarque sur les travailleurs détachés hors de propos.
sinon je pense qu'il faut expliquer le problème en montrant par exemple, que pour les énergies renouvelables, les projets sont ralentis etc. abandonnés et dégager les raisons en montrant que les propositions précises de Macron sontinsuffisantes pour y remédier. TU corriges @Scalpi  ?

**Comment by Scalpi** [comment]
ok, je corrige


Le 4 avril 2017 à 12:03, Lucas Gautheron <notifications@github.com> a écrit
:

**Comment by LVAI** [comment]
@Scalpi contre-proposition (un peu rapide mais pour montrer l'idée - et avec un ajout sur les formalité d'accueil...)

### Insuffisant et dangereux

Nous avons vu **qu' "En Marche"** souhaite consacrer 15 milliards à la transition énergétique.

Rappelons à ce propos qu'il souhaite fermer **[les 4 centrales à charbon encore en activité](https://fr.wikipedia.org/wiki/Liste_des_centrales_thermiques_%C3%A0_flamme_en_France#Centrales_.C3.A0_charbon)** sur les 5 ans et limiter la part du nucléaire de 75% à 50% d'ici 2025.Il s'agit donc de convertir 3 **térawatt** de capacité en en **énergie renouvelables** **rien que pour les centrales à charbon**. Or ~~Nous savons qu'~~il faut consacrer plus de 30 milliards par an en moyenne pour faire une transition efficace (selon différents **scénarii comme [Negawatt](https://www.negawatt.org/IMG/pdf/synthese_scenario-negawatt_2017-2050.pdf) ou [Afterres](http://afterres2050.solagro.org/wp-content/uploads/2015/11/Solagro_afterres2050-v2-web.pdf)**). On voit donc à quel point le projet d'EM n'est pas crédible avec 15 milliards sur 5 ans. **Ce qui représente un investissement de 150 milliards sur le quinqunnat et 240 d'ici 2025.**

Ensuite, il propose ~~ici~~ de faire de la France le leader de la recherche sur la transition environnementale. Sauf erreur, nous n’avons pas vu de chiffrage de montant qui serait consacré à ce point précis. Par contre, nous lisons qu’il facilitera l’arrivée de spécialistes étrangers sur la question. **Cette démarche comporte de nombreux points négatifs. Premièrement,** nous avons en France les compétences nécessaires. **C'est une richesse qu'il faut développer et encourager. Ensuite, l'emmigration est rarement un choix. Elle se fait le plus souvent sous contrainte et représente une épreuve. Le devoir d'un pays comme la France est d'offrir une possibilité de répis pour ces réfugiés. Mettre en place une discrimination à l'immigration basée sur les compétences est une mesure inhumaine. Enfin, promouvoir l'émmigration des spécialistes étrangers vers la France c'est apauvrir les pays d'origine de ces mêmes spécialites et donc ralentir leur développement.**

La réalité, c’est qu’une telle ambition quand elle n’est pas chiffrée est une déclaration d’intention, sans plus. **Il serait plus intéresant à tous les niveaux de capitaliser sur nos compétences en France et se mettre** réellement en action **pour montrer l'exemple** aux autres ~~qu'~~avec un plan crédible et sérieusement chiffré~~, on y arrive~~.

**Comment by Scalpi** [comment]
Il y a un pb de calcul : "Ce qui représente un investissement de 150 milliards sur le quinqunnat et 240 d'ici 2025". C'est 15 milliards pour le quinquennat donc en moyenne 3 par an. S'il garde cette tendance, ça nous fait 24 milliards en tout. Pour info, le coût brut Negawatt c'est 1106 milliards entre 2017 et 2050. Après je pense que la partie concernant l'émigration et autres sujets sur les réfugiés, c'est pas vraiment le sujet ici.

**Comment by sarah48** [comment]
Je propose d'ajouter ça:
"Le programme d' « En marche » propose aussi de renforcer l'autonomie des universités, alors que [ce processus déjà à l'oeuvre depuis plus d'une décennie est loin d'être positif pour la recherche](http://analysons-macron.fr/#c6m8). Le [nombre d'ouverture de poste est en forte baisse](http://blog.educpros.fr/guillaume-miquelard-et-paul-francois/2015/11/10/evolution-des-effectifs-a-luniversite-personnels-et-etudiants/) , et [à peine 30% des laboratoires publics sont financés](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/). A travers les frais d'inscription,[ ce sont surtout les étudiants qui compensent le désengagement de l'Etat](http://analysons-macron.fr/#c6m8), tandis que les promesses d'augmentation du budget de la recherche d'« En marche » sont très vagues.

Son programme n'évoque pas du tout non plus les problèmes de la bureaucratie et de la mise en concurrence (à travers l'Agence Nationale de la Recherche notamment) dans la recherche, et l'inefficacité de la niche fiscale du Crédit Impôt Recherche (CIR), qui nuisent aussi fortement à ce domaine."

**Comment by LVAI** [comment]
Nouvelle proposition

### Insuffisant et dangereux

Nous avons vu qu' "En Marche" souhaite consacrer 15 milliards à la transition énergétique.

Rappelons à ce propos qu'il souhaite fermer [les 4 centrales à charbon encore en activité](https://fr.wikipedia.org/wiki/Liste_des_centrales_thermiques_%C3%A0_flamme_en_France#Centrales_.C3.A0_charbon) sur les 5 ans et limiter la part du nucléaire de 75% à 50% d'ici 2025.Il s'agit donc de convertir 3 térawatt de capacité en en énergie renouvelables rien que pour les centrales à charbon. Or Nous savons qu'il faut consacrer plus de 30 milliards par an en moyenne pour faire une transition efficace (selon différents scénarii comme [Negawatt](https://www.negawatt.org/IMG/pdf/synthese_scenario-negawatt_2017-2050.pdf) ou [Afterres](http://afterres2050.solagro.org/wp-content/uploads/2015/11/Solagro_afterres2050-v2-web.pdf)). On voit donc à quel point le projet d'EM n'est pas crédible avec **75 milliards** sur 5 ans. Ce qui représente un investissement de **120 milliards** sur le quinquennat et 240 d'ici 2025.

Ensuite, il propose ici de faire de la France le leader de la recherche sur la transition environnementale. Sauf erreur, nous n’avons pas vu de chiffrage de montant qui serait consacré à ce point précis. Par contre, nous lisons qu’il facilitera l’arrivée de spécialistes étrangers sur la question. Cette démarche comporte de nombreux points négatifs. Premièrement, nous avons en France les compétences nécessaires. C'est une richesse qu'il faut développer et encourager. Ensuite, **Emmanuel Macron pense-t-il à certains pays en particulier pour ces recrutement ? S'il pense à des pays développé tels que les Etats-Unis alors c'est un favoritisme qui est ainsi mis en place aux frontière à l'encontre des citoyens en réel besoin d’accueil. S'il s'adresse à des pays émergeant, la discrimination élitiste et à en parallèle l'effet d'appauvrir ces pays de leur meilleures ressources intellectuelles**.

**Le programme d' « En marche » propose aussi de renforcer l'autonomie des universités, alors que [ce processus déjà à l'oeuvre depuis plus d'une décennie est loin d'être positif pour la recherche](http://analysons-macron.fr/#c6m8). Le [nombre d'ouverture de poste est en forte baisse](http://blog.educpros.fr/guillaume-miquelard-et-paul-francois/2015/11/10/evolution-des-effectifs-a-luniversite-personnels-et-etudiants/) , et [à peine 30% des laboratoires publics sont financés](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/). A travers les frais d'inscription,[ ce sont surtout les étudiants qui compensent le désengagement de l'Etat](http://analysons-macron.fr/#c6m8), tandis que les promesses d'augmentation du budget de la recherche d'« En marche » sont très vagues.**

**Son programme n'évoque pas du tout non plus les problèmes de la bureaucratie et de la mise en concurrence (à travers l'Agence Nationale de la Recherche notamment) dans la recherche, et l'inefficacité de la niche fiscale du Crédit Impôt Recherche (CIR), qui nuisent aussi fortement à ce domaine.**

La réalité, c’est qu’une telle ambition quand elle n’est pas chiffrée est une déclaration d’intention, sans plus. Il serait plus intéressant à tous les niveaux de capitaliser sur nos compétences en France et se mettre réellement en action pour montrer l'exemple aux autres qu'avec un plan crédible et sérieusement chiffré, on y arrive.

**Comment by Scalpi** [comment]
Déjà dit à LVAI, cette partie là n'est pas correct : On voit donc à quel
point le projet d'EM n'est pas crédible avec *75 milliards* sur 5 ans. Ce
qui représente un investissement de *120 milliards* sur le quinquennat et
240 d'ici 2025.

**Comment by sarah48** [comment]
Je suis d'accord avec la remarque de Scalpi, c'est bien 15 milliards sur le quinquennat.
Donc à la place des deux dernières phrases du 1er paragraphe je propose : "On voit donc à quel point le projet d'EM n'est pas crédible avec 15 milliards sur 5 ans, ce qui représenterait un investissement de 24 milliards d'ici 2025."

Et je propose ça pour le 2ème paragraphe, pour réduire un peu, en mettant le lien vers la vidéo dont je parlais :

"Ensuite, nous n’avons pas vu, sauf erreur, de chiffrage du montant qui serait consacré à ce point précis. Par contre, nous lisons qu’il facilitera l’arrivée de spécialistes étrangers sur la question. [E. Macron semble penser particulièrement aux Etats-Unis](http://www.rtl.fr/actu/politique/vid-eo-l-appel-in-english-d-emmanuel-macron-a-l-entrepreneuriat-et-a-la-recherche-7787197617), ce qui risque d'être du favoritisme au détriment des citoyens en réel besoin d’accueil. S'il s'adresse à des pays **émergents**, ça serait une sorte de discrimination élitiste qui appauvrirait ces pays de leur meilleures ressources intellectuelles, alors que nous avons déjà en France les compétences nécessaires, et qu'il faudrait les développer et les encourager."

Et comme c'est déja assez long, je pense qu'on peut supprimer le dernier paragraphe qui répète des choses déjà dites.

**Comment by Scalpi** [comment]
ok pour moi

**Comment by LVAI** [comment]
commited

**Comment by LVAI** [comment]
Nouvelle proposition

### Insuffisant et dangereux

Nous avons vu qu' "En Marche" souhaite consacrer 15 milliards à la transition énergétique. Rappelons à ce propos qu'il souhaite fermer [les 4 centrales à charbon encore en activité](https://fr.wikipedia.org/wiki/Liste_des_centrales_thermiques_%C3%A0_flamme_en_France#Centrales_.C3.A0_charbon) **d'ici** 5 ans et limiter la part du nucléaire de 75% à 50% **pour** 2025. Il s'agit donc de convertir 3 térawatt de capacité ~~en~~ en énergie renouvelables rien que pour les centrales à charbon.
Or nous savons qu'il faut consacrer plus de 30 milliards par an en moyenne pour faire une transition efficace (selon différents scénarii comme [Negawatt](https://www.negawatt.org/IMG/pdf/synthese_scenario-negawatt_2017-2050.pdf) ou [Afterres](http://afterres2050.solagro.org/wp-content/uploads/2015/11/Solagro_afterres2050-v2-web.pdf)). On voit donc à quel point **les 15 milliards d'« En Marche » sur 5 ans, soit un investissement de 24 milliards d'ici 2025, ne sont pas crédibles.**

Ensuite**, sauf erreur,**  nous n’avons pas vu de chiffrage **de ce montant**. Par contre, nous lisons qu'**« En Marche »** facilitera l’arrivée de spécialistes étrangers sur la question. [E. Macron semble penser ~~particulièrement~~ aux Etats-Unis](http://www.rtl.fr/actu/politique/vid-eo-l-appel-in-english-d-emmanuel-macron-a-l-entrepreneuriat-et-a-la-recherche-7787197617), ce qui **serait un** favoritisme au détriment des citoyens en réel besoin d’accueil. **A l'inverse, s'il** s'adresse à des pays émergents, **il ferait preuve de**  discrimination élitiste **et** appauvrirait ces pays de leur meilleures ressources intellectuelles, alors que nous avons déjà en France les compétences nécessaires **qu'il faut développer et encourager**.

Le programme d' « En marche » propose aussi de renforcer l'autonomie des universités, alors que [ce processus déjà à l'oeuvre depuis plus d'une décennie est loin d'être positif pour la recherche](http://analysons-macron.fr/#c6m8). Le [nombre d'ouverture de poste est en forte baisse](http://blog.educpros.fr/guillaume-miquelard-et-paul-francois/2015/11/10/evolution-des-effectifs-a-luniversite-personnels-et-etudiants/) , et [à peine 30% des laboratoires publics sont financés](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/). A travers les frais d'inscription,[ ce sont surtout les étudiants qui compensent le désengagement de l'Etat](http://analysons-macron.fr/#c6m8), tandis que les promesses d'augmentation du budget de la recherche d'« En marche » sont très vagues.

Son programme n'évoque pas du tout non plus les problèmes de la bureaucratie et de la mise en concurrence (à travers l'Agence Nationale de la Recherche notamment) dans la recherche, et l'inefficacité de la niche fiscale du Crédit Impôt Recherche (CIR), qui nuisent aussi fortement à ce domaine.

~~La réalité, c’est qu’une telle ambition quand elle n’est pas chiffrée est une déclaration d’intention, sans plus. Il serait plus intéressant à tous les niveaux de capitaliser sur nos compétences en France et se mettre réellement en action pour montrer l'exemple aux autres qu'avec un plan crédible et sérieusement chiffré, on y arrive.~~

**Comment by sarah48** [comment]
Ok pour moi

**Comment by LVAI** [comment]
Committed
