### ISSUE TITLE
8.9 Nous créerons un marché unique de l'énergie en Europe

### ISSUE THREAD

**Issue by Thalassin** [Insoumis/programme-macron#65]
- Il y a déjà un système européen qui permet de fixer les coûts du carbone : le marché européen des quotas d'émission, au sein duquel l'UE fournit aux entreprises des droits à émettre du carbone qu'elles peuvent ensuite échanger entre elles en cas de surplus. Instaurer un prix plancher se heurterait donc à deux limites. Premièrement, puisque M. Macron se refuse à réformer en profondeur le fonctionnement de l'UE, l'instauration d'un prix plancher dans le marché des quotas d'émissions pourrait être bloquée par l'Union Européenne en invoquant que l'implication de l'UE dans ce marché ne respecte pas les principes de concurrence libre et non faussée. De plus,  M. Macron devra également convaincre l'ensemble des pays de l'Union Européenne de prendre la même décision pour la voir s'appliquer enfin.
 - M. Macron au-delà de cela, prétend vouloir mettre en place une politique commune européenne de l'énergie alors même qu'il se refuse à laisser l'État investir lourdement dans les énergies renouvelables, au profit des start-ups, alors même que les investissements en capital nécessaires sont immenses pour des entreprises naissantes. Comment croire qu'il laissera l'Union Européenne investir là où il refuse l'interventionnisme de la République qu'il vise à diriger ?

**Comment by sarah48** [comment]
Je connais pas vraiment le sujet, mais j'ai l'impression que le côté "marché unique de l'énergie" n'est pas assez abordé, puisque c'est quand même différent du marché des quotas d'émission (même si c'est bien d'en parler). Il me semble que c'est cette volonté d'un marché unique de l'énergie qui a amené à la privatisation d'EDF/Engie par exemple

**Comment by Scalpi** [comment]
Je pense que le post de Thalassin n'est pas vraiment dans le sujet. Je propose ceci:
"TRÈS DANGEREUX"
Notons pour commencer que cette intention n'est pas détaillée dans le programme d'EM de sorte qu'il est impossible de comprendre l'intention réelle et ce qui se cache derrière. Rappelons une loi européenne, la loi NOME, entrée en vigueur le 1er juillet 2011 et "fortement inspirée" par la Commission Européenne. Cette loi oblige une entreprise (privée comme publique), dans le monde de la concurrence libre et non faussée, à céder une partie de ses atouts à des concurrents, nationaux ou européens, qui produisent peu ou pas du tout d’électricité. Cette loi est également à la base de l'injonction qui nous est faite par la CE, de vendre / privatiser une partie de nos barrages hydroélectriques. Cette loi est une étape supplémentaire vers la déstructuration complète du secteur électrique, sous le prétexte fallacieux de permettre la sacro-sainte concurrence, qui dans le domaine de l'électricité, tout le monde le constate désormais, fait augmenter les prix. En effet, les prix ont soit augmenté, soit stagné mais en aucun cas diminué puisque quel que soit le prix de rachat, tous les acteurs entrés sur le marché cherchent à faire de la marge par tous les moyens possibles. Comment pensez-vous que la France, dans un contexte pareil, puisse investir dans les infrastructures alors que la plupart des recettes sont perçues par des sociétés et des investisseurs privés. Comment allons-nous assurer l'équilibre du réseau électrique dans de telles conditions ? Puis il y a la clause de destination : la loi stipule que les fournisseurs accédant à la « rente nucléaire » devront justifier d’un portefeuille de clients équivalent sur le territoire national. 
Tout le monde sait pertinemment que cette clause ne tient pas juridiquement, et qu’au moment opportun elle sera remise en cause et permettra à n’importe quel fournisseur d’aller spéculer partout en Europe. Soyons clairs, cette loi, Macron aurait pu la voter. Voilà selon nous et bien d'autres commentateurs et spécialistes éclairés savent ce qu'il y a derrière, je cite : "Nous créerons un marché unique de l'énergie en Europe". Cette loi, nous l'abrogerons immédiatement.

**Comment by sarah48** [comment]
Je suis d'accord sur le fond. J'ai fait quelques petites modifications de forme. J'ai supprimé la fin, je trouve que c'est redondant, et l'aborgation prévue par la FI sera dans la partie "que propose la FI".
J'ai rajouté deux liens qui me semblaient pertinents. 
Sinon je trouve que le passage sur la "clause de destination" n'est pas très clair, je ne comprends pas trop en quoi ça consiste et pourquoi elle aurait ces conséquences. Ma proposition:

"Notons pour commencer que cette intention n'est pas détaillée dans le programme d'EM de sorte qu'il est impossible de comprendre l'intention réelle et ce qui se cache derrière. Rappelons une loi européenne, la [loi NOME, entrée en vigueur le 1er juillet 2011 et "fortement inspirée" par la Commission Européenne](http://www.poursavoir.fr/accueil.php). Cette loi oblige une entreprise (privée comme publique), dans le monde de la concurrence libre et non faussée, à céder une partie de ses atouts à des concurrents, nationaux ou européens, qui produisent peu ou pas du tout d’électricité. Cette loi est également **l'expression de** l'injonction qui nous est faite par la CE, de vendre / privatiser une partie de nos barrages hydroélectriques. **C'est** une étape supplémentaire vers la déstructuration complète du secteur électrique, sous le prétexte fallacieux de permettre la sacro-sainte concurrence, qui, dans le domaine de l'électricité, tout le monde le constate désormais, fait augmenter les prix. **En effet, [ceux-ci ont augmenté](http://www.capital.fr/finances-perso/actualites/la-verite-sur-la-facture-edf-elle-a-augmente-de-plus-de-37-en-10-ans-1138729)** puisque quel que soit le prix de rachat, tous les acteurs entrés sur le marché cherchent à faire de la marge par tous les moyens possibles. 

Comment pensez-vous que la France, dans un contexte pareil, puisse investir dans **des** infrastructures, alors que la plupart des recettes sont perçues par des sociétés et des investisseurs privés. Comment allons-nous assurer l'équilibre du réseau électrique dans de telles conditions ? Puis il y a la clause de destination : la loi stipule que les fournisseurs accédant à la « rente nucléaire » devront justifier d’un portefeuille de clients équivalent sur le territoire national. Tout le monde sait pertinemment que cette clause ne tient pas juridiquement, et qu’au moment opportun elle sera remise en cause et permettra à n’importe quel fournisseur d’aller spéculer partout en Europe. Soyons clairs, cette loi, Macron aurait pu la voter."

**Comment by Scalpi** [comment]
La clause de destination, c'est une stratégie qui consiste à définir un
prix différent pour chaque pays d'exportation alors que cette clause est
habituellement combattue par la CE qui souhaite éliminer les distorsions de
concurrence. Donc juridiquement, il y a un problème potentiel. Si un
concurrent potentiel d'EDF vend sur le marché européen et tire bénéfice de
l'écart, et si la commission de "régulation" lui imposait de revoir son
prix, cette société privée pourrait se retourner contre elle et obtenir
(via un tribunal d'arbitrage) gain de cause.
Voilà c'est un peu compliqué je te l'accorde mais tout cet environnement
européen qui est devenu si complexe...

**Comment by sarah48** [comment]
Nouvelle proposition en essayant d'éclaircir le point sur la clause de destination. J'ai juste remplacé une bonne partie de ce passage par tes explications sans y toucher, puisque du coup c'est plus clair pour moi, j'espère que ça te convient.

"Notons pour commencer que cette intention n'est pas détaillée dans le programme d'EM de sorte qu'il est impossible de comprendre l'intention réelle et ce qui se cache derrière. Rappelons une loi européenne, la loi NOME, entrée en vigueur le 1er juillet 2011 et "fortement inspirée" par la Commission Européenne. Cette loi oblige une entreprise (privée comme publique), dans le monde de la concurrence libre et non faussée, à céder une partie de ses atouts à des concurrents, nationaux ou européens, qui produisent peu ou pas du tout d’électricité. Cette loi est également l'expression de l'injonction qui nous est faite par la CE, de vendre / privatiser une partie de nos barrages hydroélectriques. C'est une étape supplémentaire vers la déstructuration complète du secteur électrique, sous le prétexte fallacieux de permettre la sacro-sainte concurrence, qui, dans le domaine de l'électricité, tout le monde le constate désormais, fait augmenter les prix. En effet, ceux-ci ont augmenté puisque quel que soit le prix de rachat, tous les acteurs entrés sur le marché cherchent à faire de la marge par tous les moyens possibles.

Comment pensez-vous que la France, dans un contexte pareil, puisse investir dans des infrastructures, alors que la plupart des recettes sont perçues par des sociétés et des investisseurs privés. Comment allons-nous assurer l'équilibre du réseau électrique dans de telles conditions ? Puis il y a la clause de destination, **qui consiste à définir un prix différent pour chaque pays d'exportation,  alors que l'UE fait habituellement tout pour éliminer les distorsions de concurrence. Si un concurrent potentiel d'EDF vend sur le marché européen et tire bénéfice de l'écart, et si la commission de "régulation" lui imposait de revoir son prix, cette société privée pourrait se retourner contre elle et obtenir (via un tribunal d'arbitrage) gain de cause.**  Soyons clairs, cette loi, Macron aurait pu la voter."

**Comment by Scalpi** [comment]
Hello, ça me va

**Comment by LVAI** [comment]
Commited
