### ISSUE TITLE
8.7 Brexit

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#66]
Cet engagement semble tout à fait logique. D'après ses déclarations, E.Macron, qui pense que la tenue du référendum anglais a été une [« erreur »]( http://www.lefigaro.fr/politique/le-scan/2016/06/25/25001-20160625ARTFIG00177-apres-le-brexit-emmanuel-macron-propose-un-nouveau-projet-europeen.php),  [envisage aussi de retirer aux entreprises du Royaume-Uni le « passeport financier »](https://leftfootforward.org/2017/02/what-would-a-french-president-macron-mean-for-brexit/), qui permet à une entreprise de vendre des produits financiers à travers toute l’Union européenne, ce qui semble aussi tout à fait logique.

En parallèle, il ne se cache pas de vouloir attirer en France les investisseurs de la [« city »](https://fr.wikipedia.org/wiki/Cit%C3%A9_de_Londres#Un_centre_.C3.A9conomique_et_financier%20de%20Londres), une des principales places financières mondiales. Mais il faut rappeler que la « city » est aussi considérée comme le[ premier paradis fiscal au monde](http://www.lemonde.fr/evasion-fiscale/article/2013/04/09/premier-paradis-fiscal-au-monde-la-city-beneficie-d-un-solide-reseau-extraterritorial_3156385_4862750.html). Pour attirer les investisseurs, E.Macron envisage-t-il de créer un paradis fiscal en plein cœur de la France ? Lors d'un récent voyage à Londres, il s'est en tout cas [permis de fustiger le « système fiscal » français](http://www.france24.com/fr/20170222-brexit-macron-may-Londres-sortie-hard-dure-union-europenne) ... Face à la menace de retirer le passeport financier à ses entreprises,[ le Royaume-Uni menaçait à son tour de déréglementer encore plus sa fiscalité](http://www.lemonde.fr/europe/article/2017/01/16/brexit-le-chantage-de-londres_5063258_3214.html) (!). Au final, le risque serait d'amener une course au dumping fiscal entre les places financières françaises et anglaises, qui plomberait les finances publiques de la France, tout en accentuant sa soumission à la finance...

D'autant plus qu' E.Macron déclarait aussi que « si les Britanniques ne veulent plus contribuer et souhaitent juste un traité commercial (…) il faudra formaliser une relation comme celle que l'on a avec le Canada ». Cette relation avec le Canada se fait maintenant à travers le traité de libre-échange [ CETA, qu' E.Macron soutient](http://www.liberation.fr/elections-presidentielle-legislatives-2017/2017/02/15/le-ceta-un-accord-decrie-par-la-plupart-des-candidats-a-la-presidence_1548434), qui comporte de grands dangers en matière de déréglementation fiscale, sociale et [écologique](http://www.foodwatch.org/fr/s-informer/topics/traites-ceta-et-tafta/actustraitetransatlantique/tafta-et-ceta-leurope-prete-a-brader-le-principe-de-precaution/), surtout à travers la mise en place de [tribunaux d'arbitrages](http://www.monde-diplomatique.fr/2016/02/BARLOW/54744), qui permettent à des entreprises d'attaquer des Etats qui auraient adopté des dispositions nuisant à leurs intérêts.

**Comment by sarah48** [comment]
Juste pour info, un petit paragraphe que j'ai enlevé sur l'article 50 cher aux UPRistes (rien d'exceptionnel si on fait une recherche un peu approfondie, mais des choses interessantes quand meme. Surtout le texte sur agoravox, à lire, meme si le groupe qui l'a écris ne m'inspire guère, son analyse m'a l'air convaincante):

Enfin, concernant le brexit, Macron considère qu'[« Il n’y a pas d’autre sortie possible que par l’article 50 »](http://vision-macron.fr/ ). [Cet article 50 a été adopté avec le traité de Lisbonne](https://fr.wikipedia.org/wiki/Article_50_du_trait%C3%A9_sur_l%27Union_europ%C3%A9enne), qui a été imposé en dépit du « Non » au réferendum sur le TCE de 2005.
Ca n'est pas l'avis de tout le monde. La sortie de l'UE par l'utilisation de l'article 50 est une sorte de [« parcours du combattant », fait de « procédures juridiques interminables et incompréhensibles »](http://www.agoravox.fr/actualites/europe/article/la-sortie-par-l-article-50-est-178170).
Même le diplomate britannique Lord Kerr of Kinlochard qui est à l’origine de cet article considère que [« vous n’avez pas besoin d’un article pour faire sécession » ](http://www.slate.fr/story/142394/auteur-article-50-brexit).

[Joël Rideau professeur de droit constitutionnel spécialiste de l'Union Européenne estime que, avant le traité de Lisbonne, « il n'était […] pas imaginable qu'un État désireux de se retirer […] puisse se voir opposer le caractère définitif de ses engagement » ](https://fr.wikipedia.org/wiki/Retrait_de_l%27Union_europ%C3%A9enne)

**Comment by lucasgautheron** [comment]
Merci!
