### ISSUE TITLE
10.6 - TPI dans départements

### ISSUE THREAD

**Issue by ClaXus** [Insoumis/programme-macron#67]
10.6 - « Nous établirons dans chaque département un tribunal de première instance qui sera le guichet unique permettant un accès facilité au juge.»

Nous ne fermerons aucun site.

Pourquoi pas, mais... 

Permettre une justice plus proche des gens paraît aller dans le bon sens. Mais la suite de cette mesure que l’on peut observer dans le programme complet : “Ce tribunal traitera l’ensemble des matières dans des pôles dédiés : pénal, social, affaires familiales, commercial, civil…. Les justiciables n’auront plus à chercher leur juge.” laisse clairement entendre une multiplication des responsabilités et des connaissances nécessaires pour les juges, qui sont déjà surchargés. Un rapport complet du sénat interrogeant les parties prenantes du processus ont effectivement abouti au même constat : on ne peut pas mettre cette mesure en place sans les ressources indispensables.

https://www.senat.fr/rap/r13-054/r13-0545.html#toc35

Lien vers le programme complet justice : https://en-marche.fr/emmanuel-macron/le-programme/justice
Lien LAEC justice surchargée : + lien https://avenirencommun.fr/le-livret-justice/
"Les juridictions sont en sous-effectif constant et souffrent d’une détérioration sans précédent de leurs locaux : les tribunaux croulent sous les dossiers entassés dans les couloirs et leurs équipements informatiques sont obsolètes. Les lieux de détention sont à ce point délabrés qu’ils sont envahis par les rats ou les punaises de lits – le scandale récent de la prison de Fresnes en est l’un des tristes exemples."
LAEC : 
Mettre fin à la paupérisation de la justice [...]
https://laec.fr/s11m2

**Comment by LVAI** [comment]
commited

**Comment by LVAI** [comment]
Commited
