### ISSUE TITLE
10.3 Préfets réorganisateurs des services publics

### ISSUE THREAD

**Issue by ClaXus** [Insoumis/programme-macron#68]
10.3 « Nous donnerons aux préfets la capacité d’adapter l’organisation des services de l’État aux besoins de chaque région et département.»

C’est flou et contradictoire

On peut d’abord souligner que le programme parle explicitement de supprimer des départements. Il sera donc complexe pour ces départements de s’adapter à leur spécificités. Ensuite, les préfets suivent les directives Étatiques et l’on peut donc se demander si cette mesure n’est pas simplement l’ouverture vers une déstructuration complète des collectivités locales organisées autour des préfectures, comme le prévoit le programme long : “Nous donnerons accès aux services publics en développant les maisons de services publics qui regrouperont dans un même lieu (sous-préfectures notamment) tous les services essentiels à la vie quotidienne (poste, prestations sociales, accès à l’emploi...)”. Cela nous parait donc contradictoire avec le fait d'être plus près du quotidien de tous et de répondre aux besoins particuliers de chacun.
Lien vers le programme long concerné : https://en-marche.fr/emmanuel-macron/le-programme/territoires 

LAEC : 
“Notre programme n'est pas compatible avec les règles des traités européens qui imposent l'austérité budgetaire, le libre-échange et la destruction des services publics.”
https://laec.fr/s9m2

**Comment by Scalpi** [comment]
On devrait parler du TISA ici

**Comment by sarah48** [comment]
Je propose de reformuler comme ça pour l'instant:
"On peut d’abord souligner que le programme **propose** explicitement de supprimer des départements, **départements qui ne seront donc pas concernés**. Ensuite, les préfets suivent les directives Étatiques et l’on peut donc se demander si cette mesure n’est pas simplement l’ouverture vers une déstructuration complète des collectivités locales organisées autour des préfectures, comme le prévoit le programme long : **«** Nous donnerons accès aux services publics en développant les maisons de services publics qui regrouperont dans un même lieu (sous-préfectures notamment) tous les services essentiels à la vie quotidienne (poste, prestations sociales, accès à l’emploi...) **»**. 
**Le fait de déstructurer les collectivités locales ne nous semble donc pas répondre aux besoins quotidiens de chacun.**"

Après la fin laisse un peu à désirer je trouve. Est ce que la mesure évoquée entre guillemets est simplement une "destructuration" des collectivités locales? "destructuration" me parait un peu flou. Désorganisation plutot? Et j'ai l'impression que c'est aussi une volonté de centralisation des services publics. Il n'y a pas tant que ça de sous préfectures, qui correspondent à des arrondissements: "[En 2013, il y avait en France 342 arrondissements](https://fr.wikipedia.org/wiki/Arrondissement_fran%C3%A7ais)", soit 3-4 par départements. Ce qui à mon avis pose le problème de l'éloignement des services publics, pour les gens qui vivent en périphérie. Tu pourrais donc peut être rajouter des trucs par rapport à ça.

et Scalpi: Je connais pas trop [TISA](http://www.lemonde.fr/les-decodeurs/article/2014/07/09/tisa-quand-le-liberalisme-revient-par-la-porte-de-derriere_4452691_4355770.html), mais e vois pas de rapport direct entre ça et cette mesure, tu peux expliquer?

**Comment by Scalpi** [comment]
Quand Le TISA (Trade In Services Agreement) ou son acronyme en français, ACS (Accord sur le Commerce des Services, ne dit pas son nom. Les négociations ont démarré en 2013 entre une cinquantaine d'états dont les 27 de l'UE. Ce nouveau traité dont on parle peu dans la presse officielle, 
vise à libéraliser les services, ce qui est très vague, mais lorsqu'on découvre ce qu'a révélé Wikileaks en mai 2016, on comprend beaucoup mieux que les Services Publiques sont également visés. Je cite l'Internationale des Services Publiques : "(L'ACS) s’inscrit dans cette nouvelle vague inquiétante d’accords commerciaux et d’investissement, reposant sur des pouvoirs juridiquement contraignants qui institutionnalisent les droits des investisseurs et interdisent toute intervention des États dans un large éventail de secteurs indirectement liés au commerce » et que l'accord subvertit le concept même de service public au profit des entreprises, alors même que les services publics ont pour but de fournir aux populations des services essentiels et distribués équitablement, chose que la logique de régulation du marché par le marché ne permet pas de faire".

@sarah48 : c'est pourquoi il est important de parler du TISA dans ce 10.3 car on comprend que cette mesure Macron vise à préparer le terrain et l'organisation à la mise en oeuvre du TISA.



https://wikileaks.org/tisa-financial/press.html

**Comment by sarah48** [comment]
"On peut d’abord souligner que le programme propose explicitement de supprimer des départements, **qui** ne seront donc pas concernés. Ensuite, les préfets **suivant** les directives Étatiques, **il nous semble que cette mesure mènera à une déstructuration des collectivités locales**, comme le prévoit le programme long : « Nous donnerons accès aux services publics en développant les maisons de services publics qui regrouperont dans un même lieu (sous-préfectures notamment) tous les services essentiels à la vie quotidienne (poste, prestations sociales, accès à l’emploi...) ».
De plus, cette volonté de centraliser les services publics nous parait poser un vrai problème en terme de proximité des services publics. [Il n'y a en moyenne qu'entre 3 et 4 sous-préfectures par départements](https://fr.wikipedia.org/wiki/Arrondissement_fran%C3%A7ais). Cette réforme risquerait de poser un vrai problème d'éloignement des services publics pour les personnes vivant en périphérie des sous-préfectures
Il nous semble aussi que cette réforme, ainsi que beaucoup d'autres mesures prévues par « En Marche », préparerait le terrain à l'[Accord sur le Commerce des Services (ACS ou TISA)](https://fr.wikipedia.org/wiki/Accord_sur_le_commerce_des_services), [actuellement en cours de négociation au niveau mondial](https://wikileaks.org/tisa-financial/press.html) par 50 Etats, dont les pays de l'UE, qui aurait un [effet dévastateur sur de nombreux services publics](http://www.humanite.fr/laccord-top-secret-qui-doit-depecer-les-services-publics-545491)..."

**Comment by Scalpi** [comment]
Ok, tu peux mettre le lien wikileaks ?

**Comment by sarah48** [comment]
J'ai mis le lien wikileaks

**Comment by LVAI** [comment]
Commited
