### ISSUE TITLE
10.2 « Nous passerons à la vitesse supérieure en ce qui concerne la numérisation de l’administration.»

### ISSUE THREAD

**Issue by ClaXus** [Insoumis/programme-macron#69]
10.2 « Nous passerons à la vitesse supérieure en ce qui concerne la numérisation de l’administration.»
Tous les renouvellements de documents officiels (carte d’identité, passeport, carte grise, etc.) devront pouvoir se faire en ligne, sans nécessité de se déplacer. Les horaires d’ouverture des services publics seront par ailleurs élargis aux soirées et au samedi pour s’adapter aux nouveaux modes de vie des Français.

Ça commençait bien mais c’est populiste !

 Evidemment, les démarches effectuées en ligne sont une bonne chose tant que la qualité du service ne diminue pas, car cela permet également une diminution de notre responsabilité écologique.  Ensuite, à chaque présidentielle, le candidat de droite propose cette mesure d’ouverture plus large des services publics. Mais cela coûte cher et n’est pas adéquat au rythme de vie personnel des fonctionnaires. Ce n’est donc au final jamais mis en place.

Enfin, on peut noter la contradiction entre la volonté de supprimer 120 000 postes et avec eux certains départements, et vouloir une ouverture plus large pour tous.

LAEC : "Soutenir la dématérialisation des services publics, dans une démarche de design pour tou·te·s, tout en maintenant les services physiques de proximité"
https://avenirencommun.fr/le-livret-numerique/

**Comment by lucasgautheron** [comment]
populiste ce n'est pas le mot, plutôt démagogue.
je pense que le vrai pb c'est la contradiction c'est le nombre de postes, avec la volonté d'en supprimer 120 000 dans la fonction publique et territoriale

**Comment by LVAI** [comment]
[updated]

**Comment by Scalpi** [comment]
Je ne comprends pas le terme "design" dans LAEC, y a pas une erreur ?

**Comment by sarah48** [comment]
Sur la forme: "n’est pas adéquat au rythme de vie **personnel** des fonctionnaires" -> "n'est pas **adapté** au rythme de vie des fonctionnaires"

Je crois qu' il faudrait aussi dire que les syndicats sont opposés, et que ça impliquerait de faire face à de nombreuses grèves.

Aussi certains services publics sont déja ouverts les samedi et parfois les dimanche, je pense aux bibliothèques et bibliothèques universitaires. 

Pour la contradiction par rapport à la suppression de 120000 fonctionnaires, je dirais pas tant que ça. Je crois que cette volonté de numériser l'administration serait un moyen d'affaiblir l'accueil du public et donc de supprimer des postes en disant " y' a moins besoin de fonctionnaires pour accueillir le public puisque les gens font leurs démarches par internet". je crois qu'on pourrait garder l'argument des 120000 suppressions, en rajoutant celui ci.

On peut aussi dire que ça créerait un problème pour les personnes plus âgées qui ne maitrisent pas forcément l'outil internet. Et pour les personnes qui n'ont pas internet (et peut etre voir par rapport à ce qu'il propose pour l'accès à internet de tous).

**Comment by sarah48** [comment]
ClaXus, pour rajouter un lien, tu selectionnes le passage ou tu veux mettre le lien, puis tu cliques sur la chaine dans la barre d'édition en haut ("Add a link") et la, à la place de "url", tu mets le lien.
Pour mettre un passage en gras, tu selectionnes le passage et tu cliques sur "add bold text" dans la barre d'édition.

**Comment by sarah48** [comment]
Nouvelle proposition:

"10.2 « Nous passerons à la vitesse supérieure en ce qui concerne la numérisation de l’administration.»
Tous les renouvellements de documents officiels (carte d’identité, passeport, carte grise, etc.) devront pouvoir se faire en ligne, sans nécessité de se déplacer. Les horaires d’ouverture des services publics seront par ailleurs élargis aux soirées et au samedi pour s’adapter aux nouveaux modes de vie des Français.


Evidemment, les démarches effectuées en ligne sont une bonne chose tant que la qualité du service ne diminue pas, car cela permet également une diminution de notre responsabilité écologique. Ensuite, à chaque présidentielle, le candidat de droite propose cette mesure d’ouverture plus large des services publics, **qui n'est au final jamais mise en place.** Mais cela coûte cher et n’est pas adapté au rythme de vie personnel des fonctionnaires**, ce qui risque donc de provoquer de nombreuses grèves dans la fonction publique.**
**De plus, certains services publics sont déjà ouverts les samedi et parfois les dimanche, comme les bibliothèques et les bibliothèques universitaires.**

**Cette volonté de numériser l'administration pourrait aussi être un moyen d'affaiblir l'accueil du public en supprimant des postes, ce qui va dans le sens de la volonté d'« En Marche » de [supprimer 120 000 postes de fonctionnaires](http://www.huffingtonpost.fr/2017/02/23/60-milliards-deconomies-120-000-fonctionnaires-en-moins-macron-programme-economique/). Ce qui créerait aussi un problème pour les personnes plus âgées qui ne maitrisent pas forcément l'outil internet, ainsi que pour les personnes qui n'ont pas accès à internet.**

**Enfin, on voit mal aussi comment il sera possible d'élargir les services publics aux soirs et aux week-ends, avec un nombre moins important de fonctionnaires ...**"



LAEC : "Soutenir la dématérialisation des services publics, dans une démarche de design pour tou·te·s, tout en maintenant les services physiques de proximité"
https://avenirencommun.fr/le-livret-numerique/

**Comment by LVAI** [comment]
Ok pour moi
Quelques corrections :

Evidemment, les démarches effectuées en ligne sont une bonne chose tant que la qualité du service ne diminue pas, car cela **permet d'augmenter** notre responsabilité écologique. Ensuite, à chaque présidentielle, le candidat de droite propose cette mesure d’ouverture plus large des services publics, qui n'est au final jamais mise en place. Mais cela coûte cher et n’est pas adapté au rythme de vie personnel des fonctionnaires, ce qui risque donc de provoquer de nombreuses grèves dans la fonction publique.
De plus, certains services publics sont déjà ouverts les samedi et parfois les dimanche, comme les bibliothèques et les bibliothèques universitaires.

Cette volonté de numériser l'administration pourrait aussi être un moyen d'affaiblir l'accueil du public en supprimant des postes, ce qui va dans le sens de la volonté d'« En Marche » de [supprimer 120 000 postes de fonctionnaires](http://www.huffingtonpost.fr/2017/02/23/60-milliards-deconomies-120-000-fonctionnaires-en-moins-macron-programme-economique/). Ce qui créerait aussi un problème pour les personnes plus âgées qui ne **maîtrisent** pas forcément l'outil internet, ainsi que pour les personnes qui **n'y ont pas accès**.

Enfin, on voit mal aussi comment il sera possible d'élargir les services publics aux soirs et aux week-ends, avec un nombre moins important de fonctionnaires ...

**Comment by sarah48** [comment]
Ok, donc en prenant en compte les corrections:

10.2 « Nous passerons à la vitesse supérieure en ce qui concerne la numérisation de l’administration.»
Tous les renouvellements de documents officiels (carte d’identité, passeport, carte grise, etc.) devront pouvoir se faire en ligne, sans nécessité de se déplacer. Les horaires d’ouverture des services publics seront par ailleurs élargis aux soirées et au samedi pour s’adapter aux nouveaux modes de vie des Français.

"Evidemment, les démarches effectuées en ligne sont une bonne chose tant que la qualité du service ne diminue pas, car cela permet d'augmenter notre responsabilité écologique. Ensuite, à chaque présidentielle, le candidat de droite propose cette mesure d’ouverture plus large des services publics, qui n'est au final jamais mise en place. Mais cela coûte cher et n’est pas adapté au rythme de vie personnel des fonctionnaires, ce qui risque donc de provoquer de nombreuses grèves dans la fonction publique. De plus, certains services publics sont déjà ouverts les samedi et parfois les dimanche, comme les bibliothèques et les bibliothèques universitaires.

Cette volonté de numériser l'administration pourrait aussi être un moyen d'affaiblir l'accueil du public en supprimant des postes, ce qui va dans le sens de la volonté d'« En Marche » de supprimer 120 000 postes de fonctionnaires. Ce qui créerait aussi un problème pour les personnes plus âgées qui ne maîtrisent pas forcément l'outil internet, ainsi que pour les personnes qui n' y ont pas accès.

Enfin, on voit mal aussi comment il sera possible d'élargir les services publics aux soirs et aux week-ends, avec un nombre moins important de fonctionnaires ..."

LAEC : "Soutenir la dématérialisation des services publics, dans une démarche de design pour tou·te·s, tout en maintenant les services physiques de proximité"
https://avenirencommun.fr/le-livret-numerique/

**Comment by LVAI** [comment]
Commited
