### ISSUE TITLE
6.8 Autonomie des universités

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#7]
L'autonomie des universités est un processus à l'oeuvre depuis une dizaine d'année en France, qui découle du processus de Bologne entamé en 1988 par l'Union Européenne.
Elle a commencé avec la [LRU, dite loi d'autonomie des universités, imposée par Valerie Pécresse en 2007](https://fr.wikipedia.org/wiki/Loi_relative_aux_libert%C3%A9s_et_responsabilit%C3%A9s_des_universit%C3%A9s).

Ce processus vise comme son nom l'indique à rendre les universités plus autonomes. En particulier au niveau de ses financements. Plutôt que de dépendre des financements de l'Etat, l'autonomie cherche à les ouvrir à des financements locaux, et surtout privés. C'est en fait un début de privatisation des universités, que « En Marche » cherche à « renforcer ».
Ce processus amène donc une territorialisation des universités : Depuis [2013 et la loi Fioraso](https://fr.wikipedia.org/wiki/Loi_relative_%C3%A0_l%27enseignement_sup%C3%A9rieur_et_%C3%A0_la_recherche), les [établissements doivent se regrouper dans des consortiums locaux](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/), ce qui met les universités au service des intérêts économiques et politiques locaux.
Le processus d'autonomie, c'est aussi une mise en concurrence des universités, qui amène un affaiblissement du cadre national des diplômes : Ceux-ci voient leurs valeurs changer suivant l'université.

Elle s'accompagne d'un recul de la démocratie au sein des établissements, en particulier par le renforcement du pouvoir du président et d'un Conseil d'Administration ouvert à des décideurs du privé, et d'un recul des pouvoirs des étudiants ou des personnels. Une démocratie qui devrait encore reculer avec « En Marche », qui propose plus de « souplesse » au dans les directions d'universités.

Dans l'Enseignement Supérieur et la Recherche, les recrutements ont plongé et presque la moitié des salariés sont précaires, tandis qu'à peine 30% des laboratoires publics sont financés, [ce que la loi Sauvadet de 2012 n'a pas du tout résolu](http://www.collectif-papera.org/spip.php?article1454).

Finalement, ce sont surtout les étudiants qui compensent le désengagement de l'Etat, les universités ont vu leurs frais d'inscription fortement augmenter au cours de la dernière décennie, et une flambée de ces frais est déjà programmée: [Un rapport récent de l'IGF recommendait une multiplication par 5 de leur montant](http://www.sudouest.fr/2015/07/01/bientot-une-forte-hausse-des-frais-d-inscription-a-l-universite-1980933-705.php). Ce désengagement amène aussi souvent des [difficultés financières d'universités](http://www.liberation.fr/societe/2013/12/22/autonomie-ces-universites-a-la-rue-a-cause-de-la-loi-lru_968473).

Pour les « 80 000 places dans les filières professionnalisantes », c'est à dire principalement les licences et masters professionnels, avec le désengagement de l'Etat et la baisse des budgets des universités, on voit mal comment ce serait possible, sauf en poursuivant le logique de privatisation des universités, en augmentant leur ouverture aux financements privés, ou en augmentant encore les frais d'inscription.

**Comment by lucasgautheron** [comment]
Merci
