### ISSUE TITLE
7.5 Droit d'asile

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#70]
Actuellement, les demandeurs d'asile déposent une demande en préfecture, qui statue sur leurs conditions de séjour en France. Ensuite c'est l'[OFPRA](https://fr.wikipedia.org/wiki/Office_fran%C3%A7ais_de_protection_des_r%C3%A9fugi%C3%A9s_et_apatrides) qui étudie les motifs de la demande. En cas de refus, la grande majorité déposent un recours auprès de la [CNDA](https://fr.wikipedia.org/wiki/Cour_nationale_du_droit_d%27asile), un tribunal administratif. En 2016, [le délai moyen d’instruction par l'OFPRA a été de 5 mois](http://www.psmigrants.org/site/ofpra-bilan-provisoire-de-lasile-en-2016/). « En Marche » veut réduire ce délai à 8 semaines, ce qui semble peu crédible, alors qu' E.Macron promet de [supprimer 120 000 fonctionnaires, et que les priorités annoncées sont ailleurs (sécurité, hôpitaux et enseignants de CP-CE1)](http://www.lagazettedescommunes.com/492750/ce-que-propose-emmanuel-macron-pour-les-fonctionnaires-et-les-collectivites/). L'idée proposée de mettre dans chaque centre d'accueil une délégation de l'OFPRA est bonne, mais ne devrais pas réduire de beaucoup ce délais. 

Surtout, le principal problème se situe avant, avec le manque de moyens des préfectures. Alors que [les demandes d'asile augmentent](http://www.lemonde.fr/immigration-et-diversite/article/2016/09/09/forte-hausse-des-demandes-d-asile_4995135_1654200.html), [le manque de personnels bloque le processus de traitement des dossiers, en particulier à Paris ](http://www.lemonde.fr/immigration-et-diversite/article/2016/06/08/asile-les-modestes-records-de-la-france_4942871_1654200.html). La aussi, la réduction du nombre de fonctionnaires ne risque par d'arranger les choses. 
Concernant la CNDA, actuellement, le délai de traitement des recours est de [6 mois (6 semaines en procédure accélérée)](https://www.senat.fr/commission/fin/pjlf2017/np/np06/np061.html). L'idée avancée de faire en sorte que cette cour, qui se trouve à Montreuil, « puisse statuer dans les centres d’accueil » parait bonne. Mais [si les délais de traitement par la CNDA ont baissé durant le dernier quinquennat, c'est en grande partie grâce à la hausse des effectifs de fonctionnaires et de magistrats](https://www.senat.fr/commission/fin/pjlf2017/np/np06/np061.html). Et « En Marche » ne prévoit pas non plus d'augmentation du nombre de magistrats ...

Réduire à 6 mois le total du délai d'examen semble donc peu réaliste, d'autant plus que la tendance à l'augmentation du nombre de demandes d'asile devrait se poursuivre. La seule manière de le faire, en l'absence de recrutements, serait d'augmenter le nombre de procédures accélérées et d'écarter plus de demandes (la réforme de 2015 va en partie dans ce sens). Ce qui risque fort de réduire la défense des demandeurs d'asile, qui ont besoin de temps pour constituer les dossiers, demander de l'aide, ou recourir à l'aide juridictionnelle. La volonté de reconduire « sans délai » les demandeurs qui ont vu leurs demandes refusées va dans le même sens, alors qu'actuellement ils ont un délai d'un mois pour effectuer un recours.

**Comment by Scalpi** [comment]
Je comprends pas le "réduire à 6 mois" alors que plus haut on dit délai moyen de 5 mois ?

**Comment by LVAI** [comment]
@sarah48 Corrections proposées :

Actuellement, les demandeurs d'asile déposent une demande en préfecture, qui statue sur leurs conditions de séjour en France. Ensuite c'est **l'office français de protection des réfugiés et apatrides ([OFPRA](https://fr.wikipedia.org/wiki/Office_fran%C3%A7ais_de_protection_des_r%C3%A9fugi%C3%A9s_et_apatrides))** qui étudie les motifs de la demande. En cas de refus, la grande majorité déposent un recours auprès de la **cour nationale du droit d'asile ([CNDA](https://fr.wikipedia.org/wiki/Cour_nationale_du_droit_d%27asile))**, un tribunal administratif. En 2016, [le délai moyen d’instruction par l'OFPRA a été de 5 mois](http://www.psmigrants.org/site/ofpra-bilan-provisoire-de-lasile-en-2016/). « En Marche » veut réduire ce délai à 8 semaines, ce qui semble peu crédible, alors **qu'E. Macron** promet de [supprimer 120 000 fonctionnaires, et que les priorités annoncées sont ailleurs (sécurité, hôpitaux et enseignants de CP-CE1)](http://www.lagazettedescommunes.com/492750/ce-que-propose-emmanuel-macron-pour-les-fonctionnaires-et-les-collectivites/). L'idée proposée de mettre dans chaque centre d'accueil une délégation de l'OFPRA est bonne, mais **ne devrait pas** réduire de beaucoup ce délais. 

**Par ailleurs, le principal problème se situe en amont** avec le manque de moyens des préfectures. Alors que [les demandes d'asile augmentent](http://www.lemonde.fr/immigration-et-diversite/article/2016/09/09/forte-hausse-des-demandes-d-asile_4995135_1654200.html), [le manque de **personnel** bloque le processus de traitement des dossiers, en particulier à Paris](http://www.lemonde.fr/immigration-et-diversite/article/2016/06/08/asile-les-modestes-records-de-la-france_4942871_1654200.html). La aussi, la réduction du nombre de fonctionnaires **risque de ne pas arranger** les choses. 
Concernant la CNDA, actuellement, le délai de traitement des recours est de [6 mois (6 semaines en procédure accélérée)](https://www.senat.fr/commission/fin/pjlf2017/np/np06/np061.html)**, ajoutés aux 5 mois de l'OFPR**A. L'idée ~~avancée~~ de **permettre** que cette cour~~, qui se trouve à Montreuil,~~ « puisse statuer dans les centres d’accueil » parait bonne. Mais [si les délais de traitement par la CNDA ont baissé durant le dernier quinquennat, c'est en grande partie grâce à la hausse des effectifs de fonctionnaires et de magistrats](https://www.senat.fr/commission/fin/pjlf2017/np/np06/np061.html) **et** « En Marche » ne prévoit **aucune augmentation du nombre de magistrats.**

Réduire à 6 mois le total du délai d'examen semble donc peu réaliste, d'autant ~~plus~~ que la tendance à l'augmentation du nombre de demandes d'asile devrait se poursuivre. La seule manière de le faire, en l'absence de recrutements, serait d'augmenter le nombre de procédures accélérées et **d'écarter un plus grand nombre** de demandes (la réforme de 2015 va en partie dans ce sens). Ce qui risque fort de réduire la défense des demandeurs d'asile, qui ont besoin de temps pour constituer les dossiers, demander de l'aide ou recourir à l'aide juridictionnelle. La volonté de reconduire « sans délai » les demandeurs qui ont vu leurs demandes refusées va dans le même sens, alors qu'actuellement ils ont un délai d'un mois pour effectuer un recours.

**Comment by LVAI** [comment]
@Scalpi j'ai essayé de clarifier mais on parle de 2 organismes différents

**Comment by Scalpi** [comment]
plus clair pour moi.

**Comment by LVAI** [comment]
Commited
