### ISSUE TITLE
8.3 Nous réserverons l'accès aux marchés publics européens aux entreprises...

### ISSUE THREAD

**Issue by Zedhyn** [Insoumis/programme-macron#71]
[insert] from Zedhyn

# 8.3 Nous réserverons l'accès aux marchés publics européens aux entreprises...
### ...qui localisent au moins la moitié de leur production en Europe dans le cadre d'un Buy European Act.

Une proposition qui date de 1993 !

En 1993, Elisabeth Guigou, alors Ministre des Affaires Européennes sous François Mitterrand, avait déjà évoqué cette mesure jamais mise en oeuvre. Vint ensuite le tour de Ségolène ROYAL qui en avait fait une idée forte de son programme lors de la campagne de 2007. Et pour finir, c'est Nicolas Sarkozy qui, en Mars 2012, proposait à nouveau une mesure du même type ! 
En représailles à cette mesure, de nombreux pays seront tentés d'adopter, à leur tour, des barrières protectionnistes contre les pays membres de l'UE. C'est un risque énorme pour les entreprises dont les marchés sont en dehors de l'UE.
L'autre barrière juridique reste bien sûr l'OMC. Pour mettre en place un "Buy European Act", il faudrait faire comme les Etats-Unis, c'est-à-dire obtenir une dérogation de l'organisation internationale. Mais cela représenterait un travail de titan, qui demanderait de renégocier tous les accords bilatéraux avec les pays tiers !
Il ne faut oublier non plus qu'en 2008, avec l'aide d'Angela Merkel, le chef de l'Etat français de l'époque avait réussi à convaincre Bruxelles de mettre en place un "Small Business Act" européen. Mais en raison de l'opposition de nombreux pays nordiques, le texte s'est borné à proposer des mesures de soutien financier aux PME plutôt qu'à leur réserver une part des marchés publics européens. 

## Qu'en dit l'Avenir en Commun ?
- Plan A : https://laec.fr/section/51/plan-a-proposer-une-refondation-democratique-sociale-et-ecologique-des-traites-europeens-par-la-renegociation
- Plan B : https://laec.fr/section/52/appliquer-un-plan-b-en-cas-d-echec-des-negociations

@lucas : source de l'argumentation : http://www.lexpress.fr/actualite/politique/buy-european-act-faut-il-copier-les-etats-unis_1376283.html

**Comment by lucas** [comment]
@Zedhyn you have the wrong @lucas

**Comment by sarah48** [comment]
Le problème, ce que la FI avec le protectionnisme solidaire, dans le cadre du plan A, propose aussi du protectionnisme, le protectionnisme solidaire. Donc les arguments se retournent contre nous.

Le dernier paragraphe me semble plus pertinent.

**Comment by sarah48** [comment]
Nouvelle proposition:

C'est peu probable

"Actuellement, les marchés publics de l'Union Européenne sont très ouverts : [En 2014 l’UE ouvrait 90% de ses besoins à des fournisseurs non européens (contre 32% pour les USA, 28% pour le Japon, 16% pour le Canada...)](http://www.slate.fr/economie/87259/commerce-exterieur-union-europeenne-protectionnisme). L'idée proposée par « En Marche » est très ancienne puisqu'en 1993 déjà, E. Guigou l'évoquait, comme S. Royal en 2007. En 2012, [N.Sarkozy la proposait, sans succès](http://www.lexpress.fr/actualite/politique/buy-european-act-faut-il-copier-les-etats-unis_1376283.html). 

L'ouverture excessive des marchés publics européens remonte aux années 1990 avec une [très mauvaise négociation ](http://confrontations.org/la-revue/ttip-la-bataille-de-lacces-aux-marches-publics) de l’[Accord sur les Marchés Publics (AMP) ](https://fr.wikipedia.org/wiki/Accord_sur_les_march%C3%A9s_publics) avec l'OMC, accord qu'il faudrait remettre en cause. [La loi de réciprocité dans l'accès aux marchés publics adoptée au niveau européen en 2014](http://www.slate.fr/economie/87259/commerce-exterieur-union-europeenne-protectionnisme), et l'adoption du traité de libre-échange avec le Canada (CETA), [que E.Macron soutien](http://www.lemonde.fr/les-decodeurs/article/2017/02/13/emmanuel-macron-seul-candidat-a-la-presidentielle-ouvertement-favorable-au-ceta_5078997_4355770.html), ne visent finalement qu'à amener plus d'ouverture et donc de dérégulation, y compris en matière d'attribution de marchés publics. Le problème vient de l'aversion de l'UE envers toute forme de protectionnisme, et il nous semble enfin qu'il faudrait surtout insister sur le respect de critères écologiques, sociaux et fiscaux pour l'attribution des marchés publics aux entreprises. Un autre grand problème est qu'[au sein de l'UE il y a de grandes différences : Les pays les plus importants sont beaucoup moins ouverts que les autres](http://confrontations.org/la-revue/ttip-la-bataille-de-lacces-aux-marches-publics
), et le programme d' EM ne parle pas du tout d'harmonisation des pays européens dans ce domaine. 


Un problème de fond est qu'avec les politiques d'austérité, les investissements publics, et donc les marchés publics se réduisent de plus en plus. Or l'investissement public, comme dans le secteur du bâtiment, nécessite peu d'importations. Alors que le programme d' EM propose « un instrument de contrôle des investissements étrangers en Europe pour préserver nos intérêts et secteurs stratégiques », il faut quand même rappeler qu'en 2015, E.Macron a participé à la [vente de l'aéroport de Toulouse-Blagnac à un consortium chinois](http://www.humanite.fr/le-coup-de-force-de-macron-pour-privatiser-les-aeroports-571715) , et qu'en 2016, alors qu'il était ministre de l'économie, [l'Etat privatisait les aéroports de Lyon et Nice](http://www.latribune.fr/economie/france/la-privatisation-des-aeroports-de-nice-et-lyon-est-bouclee-612223.html). Le candidat d'EM a aussi [autorisé la vente sans condition de la branche énergie d'Alstom](https://www.youtube.com/watch?v=dOnGH9v-oIA) (dans laquelle l'Etat était actionnaire minoritaire) à l'entreprise américaine General Electric, alors que A.Montebourg avait bloqué la vente de cette industrie stratégique."

**Comment by LVAI** [comment]
Committed
