### ISSUE TITLE
9.8 - « Nous doublerons le nombre de maisons de santé.»

### ISSUE THREAD

**Issue by ClaXus** [Insoumis/programme-macron#72]
9.8 - « Nous doublerons le nombre de maisons de santé.»
Pour lutter contre les déserts médicaux, ces maisons regrouperont des médecins, des infirmières, des orthophonistes, des kinésithérapeutes, des professionnels du sport...

C'est bien mais c'est insuffisant.

Tous les candidats ou presque sont d'accord sur le constat : les maisons de santé permettent de régler bien des problèmes. Mais le fait est qu'elles ne règlent pas tout. Et surtout pas, comme le programme d'Emannuel Macron le sous-entend, le problème des déserts médicaux. 

http://www.jim.fr/medecin/actualites/pro_societe/e-docs/louees_par_tous_les_candidats_les_maisons_de_sante_ne_seraient_pas_la_solution_miracle__164484/document_actu_pro.phtml
http://www.alternatives-economiques.fr/sante-un-diagnostic-partage-remedes-differents/00078056

LAEC : 
Médecins fonctionnaires en déserts médicaux : https://laec.fr/s67m3
Tiers-payant dans ces maisons de santé : https://laec.fr/s67m4

**Comment by lucasgautheron** [comment]
~~t'asfait les modifs en se basant sur le rapport du sénat ?~~ mauvais ticket

**Comment by ClaXus** [comment]
Nope, je relis vite fait et j'agrémente si y'a des choses en plus, mais ça me semblait juste et concis.

**Comment by sarah48** [comment]
Pourquoi elles ne règlent pas le problème des déserts médicaux?

**Comment by sarah48** [comment]
Je propose ça, à partir des deux excellentes sources que ClaXus a mis en bas de l'article, et que je n'avais pas regardé:

"Citons ce [très bon article d' « Alternatives Economiques » ](http://www.alternatives-economiques.fr/sante-un-diagnostic-partage-remedes-differents/00078056) sur les programmes des candidats en matière de santé, au sujet des déserts médicaux : « Le problème n’est pas d’encourager le développement des maisons de santé : c’est déjà le cas aujourd’hui et la tendance continuera. La difficulté est plutôt de trouver une solution pour les territoires où aucun médecin ne veut s’installer, que ce soit en exercice libéral solitaire, en libéral en maison de santé ou en salarié d’un centre de santé municipal. »

En effet, certains professionnels n'apprécient pas cette forme d'organisation, et [les Maisons de Santé Pluridisciplinaires (MSP) ont souvent des problèmes de financement](http://www.jim.fr/medecin/actualites/pro_societe/e-docs/louees_par_tous_les_candidats_les_maisons_de_sante_ne_seraient_pas_la_solution_miracle__164484/document_actu_pro.phtml) , qui touchent aussi les professionnels qui y exercent. Les collectivités locales devraient aussi participer aux financements, mais le programme d' « En Marche » prévoit la [suppression d'une de leurs principales source de revenu, la taxe d'habitation](http://analysons-macron.fr/#c12m1). Aussi, [les démarches administratives sont souvent très lourdes](http://www.jim.fr/medecin/actualites/pro_societe/e-docs/louees_par_tous_les_candidats_les_maisons_de_sante_ne_seraient_pas_la_solution_miracle__164484/document_actu_pro.phtml) pour arriver à créer ces MSP.

Ce problème est aussi [lié à celui des dépassements d'honoraires](http://www.alternatives-economiques.fr/sante-un-diagnostic-partage-remedes-differents/00078056) : Les médecins qui les pratiquent ne sont pas accessibles à tout le monde. Le programme d' « En marche » ne prévoit rien pour les limiter, et ne prévoit pas non plus de mesures nouvelles pour contraindre les médecins à exercer dans ces déserts médicaux. Le programme d'EM prévoit de relever le numerus clausus, [ce qui ne résoudra rien à court terme](http://www.alternatives-economiques.fr/sante-un-diagnostic-partage-remedes-differents/00078056), et à plus long terme, cela n'incitera pas plus les médecins à exercer dans ces zones."

**Comment by LVAI** [comment]
C'est très bien.
Je corrigerai juste MSP = maison de santé pluridisciplinaires

**Comment by Scalpi** [comment]
ça me va aussi

**Comment by sarah48** [comment]
C'est corrigé !

**Comment by LVAI** [comment]
Commited
