### ISSUE TITLE
Lisibilité des liens

### ISSUE THREAD

**Issue by LVAI** [Insoumis/programme-macron#74]
Mettre mieux en valeurs les liens cliquables dans la partie "Qu'en dit l'avenir en commun ?"

![laec](https://cloud.githubusercontent.com/assets/25056691/24634522/a887b072-18ce-11e7-9edd-6e1c2922addf.png)

**Comment by lucasgautheron** [comment]
Le soulignement suffit ? (voir la version actuelle)
