### ISSUE TITLE
6.10 : « Nous construirons 80 000 logements pour les jeunes.»

### ISSUE THREAD

**Issue by Scalpi** [Insoumis/programme-macron#76]
GRANDE MÉFIANCE
Le programme propose la construction de 80 000 logements pour les jeunes, 60 000 pour les étudiants et 20 000 pour les jeunes actifs. Quels types de logements, sociaux, publics, privés ? Nous prévoyons la construction de 1 million de logements publics en 5 ans (budget : 18 milliards) ce qui nous fait le logement à 180 000 €. Les modes de financement sont diverses et prévus, il y a également une part d’investissement. Comment finance-t'il ses 80 000 logements ? Nous n’avons pas vu, sauf erreur, quelconque chiffrage sur ce projet et rien du tout dans les 50 milliards. Le projet d'En Marche coûterait 10,8 milliards sur la base de notre calcul. Ils n’y sont tout simplement pas dans son budget.

**Comment by sarah48** [comment]
Le problème c'est qu'il ne faut pas avancer les propositions de la FI dans le texte, puisque c'est la fonction de la partie "que propose la FI" en dessous du texte.
La dernière phrase pose aussi problème. Tu parles de l'ensemble du programme? Je pense qu'il vaut mieux en rester sur la mesure en question, la critique d'ensemble concerne plus l'intro ou la conclu. Après je suis pas contre, mais je crois que l'ensemble de son programme coute beaucoup plus cher, si on tient compte des investissements et surtout des baisses de charges.
Donc en enlevant ces deux phrases ça donnerait:

"Le programme propose la construction de 80 000 logements pour les jeunes, 60 000 pour les étudiants et 20 000 pour les jeunes actifs. Quels types de logements, sociaux, publics, privés ? Comment finance-t'il ses 80 000 logements ? Nous n’avons pas vu, sauf erreur, **un** quelconque chiffrage sur ce projet, et rien du tout dans les 50 milliards." 

En attendant peut être d'enrichir la critique.

**Comment by Scalpi** [comment]
Pas trop d'accord, il faut non seulement indiquer que cette mesure n'est pas chiffrée dans son budget mais en plus dire ce que ça coûterait parce que nous on l'a chiffrée.

**Comment by sarah48** [comment]
Nouvelle version proposée après discussion:

"Le programme propose la construction de 80 000 logements pour les jeunes, 60 000 pour les étudiants et 20 000 pour les jeunes actifs. Quels types de logements, sociaux, publics, privés ? En se basant sur un coût moyen par logement de 180 000 euros (ce qui est le montant prévu par le programme de la France Insoumise), d'après notre calcul, cette mesure coûterait 10,8 milliards. Nous n’avons pas vu, sauf erreur, un quelconque chiffrage sur ce projet et rien non plus dans les 50 milliards d'investissements prévus." 


En attendant peut être d'enrichir la critique.

**Comment by LVAI** [comment]
Zedhyn commented 16 days ago
lien LAEC :
https://avenirencommun.fr/livret-de-lenseignement-de-recherche/

P.S : il n'y pas pas d'encart spécifique sur le site de LAEC, le contenu du programme de JLM concernant les logements étudiant est uniquement inscrit dans le livret thématique "Le choix du savoir", lien ci-dessus.

**Comment by LVAI** [comment]
Commited
