### ISSUE TITLE
1.2 : « Nous augmenterons le pouvoir d’achat des ouvriers, des employés et des salariés les moins bien payés. »

### ISSUE THREAD

**Issue by Scalpi** [Insoumis/programme-macron#77]
INSUFFISANT !
Nous portons le SMIC à +15% soit 173 € de plus par mois. Nous engageons une revalorisation des salaires des fonctionnaires gelés depuis 2010 et portons les pensions de retraite au niveau du SMIC et les minima vieillesse au seuil de pauvreté (1008 €).

**Comment by LVAI** [comment]
Scalpi, j'ai fait l'analyse ici : #61 

Ton texte ne convient pas parce que tu détailles ce que propose la France Insoumise au lieu d'analyser la mesure d' "En Marche" en tant que telle.

**Comment by Scalpi** [comment]
D'accord avec toi, un peu léger de mon côté...

2017-04-05 11:14 GMT+02:00 LVAI <notifications@github.com>:
