### ISSUE TITLE
2.4 [to update] « Nous redéfinirons le dialogue social.»

### ISSUE THREAD

**Issue by LVAI** [Insoumis/programme-macron#78]
## 2.4 « Nous redéfinirons le dialogue social.»
Les principes fondamentaux (durée légale du temps de travail, égalité professionnelle, salaire minimum...) resteront dans la loi. Mais, par exemple, les horaires effectifs ou l’organisation du travail seront négociés au plus près du terrain. Ils seront définis par accord majoritaire ou par référendum d’entreprise sur la base d’un accord.

## C'EST UNE TRÈS MAUVAISE IDÉE
En clair, « En Marche » se prononce pour le maintien de la loi El Khomri, dite « loi travail », et de son principe central de l'inversion de la hiérarchie des normes. Cet engagement n'apporte donc aucun changement.
« La primauté sera donnée aux accords d'entreprises sur les accords de branche », indique clairement le complément du programme, alors que c'était l'inverse qui était en vigueur avant l'adoption de cette loi, c'est à dire que la loi et les accords de branche primaient sur les accords d'entreprises. Dans la « loi travail », la primauté est accordée d'abord aux accords d'entreprises sur les accords de branches, et aux accords de branches (et d'entreprises) sur la loi. C'est donc une remise en cause de pans entiers de la loi. 
En particulier ce sera le cas pour le taux de majoration des heures supplémentaires (les accords peuvent faire baisser la hausse de la rémunération de ces heures de 25 à 10%). 
Cette loi a aussi étendu la possibilité ouverte à l’employeur·euse de négocier un accord d’entreprise imposant l’augmentation du temps de travail sans contrepartie salariale (jusqu'à 46h par semaine), ou la réduction du salaire pour un temps de travail équivalent sans que l’entreprise soit en difficulté économique, cela au nom du « maintien de l'emploi ». 
Par ailleurs, cette loi facilite les licenciements boursiers ou économiques, qui se sont multipliés depuis plus de 15 ans. Autrement dit, les accords d'entreprises ou de branche pourront déroger à la loi, et l'énoncé de cette mesure est particulièrement trompeur. En réalité, c'est une véritable remise en cause du principe des 35 heures, qui aura pour effet d'accentuer le dumping social entre les entreprises françaises, c'est à dire la course à l'abaissement des droits sociaux des salariés dans les entreprises, notamment sur les salaires.

## Qu'en dit l'«Avenir en Commun» ?

- Abroger la loi El Khomri
- Appliquer réellement et immédiatement les 35 heures :

- Majorer les heures supplémentaires (25 % pour les 4 premières et 50 % et plus au-delà)
- Revenir sur la flexibilisation, l'annualisation, l'intensification et les horaires fractionnés
- Revenir sur le forfait-jour et le limiter aux seuls cadres dirigeants
- Revenir sur les élargissements du travail du dimanche
- Interdire les licenciements boursiers

- Renforcer le pouvoir d'intervention des salariés contre les licenciements économiques par un droit de veto suspensif des comités d'entreprise

## Contribution requise

Ajouter un renvoi sur une présentation d'un outil de simulation WORKSIM qui montre ce que donne la loi ELK au bout de 4 ans d'application

**Comment by Scalpi** [comment]
Nous vous suggérons d'approfondir sur les effets de la loi ELK en regardant ce qu'a fait WorkSim qui a mis au point un modèle basée sur l'intelligence artificielle et qui permet de simuler tous les effets de cette loi sur une projection de 4 ans.

**Comment by lucasgautheron** [comment]
@Scalpi un lien ?

**Comment by Scalpi** [comment]
Voilà :
https://www.youtube.com/watch?v=VuymUdVHheE

2017-04-04 12:01 GMT+02:00 Lucas Gautheron <notifications@github.com>:
