### ISSUE TITLE
2.1 : « Nous simplifierons la vie des entrepreneurs.»

### ISSUE THREAD

**Issue by Scalpi** [Insoumis/programme-macron#79]
INCOMPRÉHENSION DE LA MESURE DONC MÉFIANCE
Commençons par commenter le texte ci-dessus. La suppression du RSI et la réintégration des bénéficiaires dans le régime général, nous en sommes d’accord mais que ne l’ont-ils pas fait avant alors que c’était une promesse de campagne de HOLLANDE. Ensuite, « nous doublerons les plafonds pour que les entrepreneurs puissent accéder au régime fiscal de la micro entreprise ». Nous supposons qu’on parle ici des plafonds en CA HT dont pour les commerçants est limité à 82 800 € et 33 100 € pour les prestataires de service. Maintenant, regardons ce que permet ce régime : plus de TVA dans les échanges (donc moins de recettes pour l’état) et d’autres avantages sur lesquels il n’est pas pertinent d’y revenir pour la présente analyse. Nous connaissons bien la passionaria du candidat pour l’ubérisation sous toutes ses formes. Cette mesure y répond directement c’est pourquoi il n’est pas étonnant qu’elle y figure en tête de chapitre dans son programme sur le sujet, car la mesure est somme toute anodine tant il est bien évident qu’il y a par ailleurs tant de choses à faire dans le domaine. Ensuite nous n’avons pas trouvé de lien clair entre la concurrence déloyale et le fait que ce régime y mettrait fin. Plus généralement sur le chapitre du candidat concernant l’entreprise, nous retrouvons sans surprise l’état d’esprit néo ? libéral que nous lui connaissons, baisse des charges patronales voire suppression pour le SMIC, un PFU taxé à 30 % sur les revenus mobiliers, ce qui permettrait je cite : « Il simplifiera   considérablement le choix des investisseurs qui se détermineront uniquement en fonction du rendement ». Nous y voilà, le critère le plus important pour le candidat est que les investisseurs maximisent encore et toujours plus le rendement de leurs investissements. Pour finir, il veut créer un Fonds pour l’Industrie et l’Innovation, 10 milliards. Où va-t-il chercher l’argent ? Dans les actions encore détenues par l’état dans certaines grandes entreprises. Plus aucun contrôle de l’état donc ? Nous vous laissons juges.

**Comment by ClaXus** [comment]
Hello, la réponse ne répond pas totalement à la mesure du programme complet, il y a aussi l'histoire du CICE en abaissement de charges, + sur la fin on empiétait sur d'autres mesures.

"Nous simplifierons la vie des entreprises, en transformant le CICE en allégement permanent de cotisations sociales de 6 points.
Cela permettra de faire gagner du temps aux employeurs des petites entreprises."
https://en-marche.fr/emmanuel-macron/le-programme/travail-emploi

Je propose une refonte :

MEFIANCE

Tout d'abord, la suppression du RSI et la réintégration des bénéficiaires dans le régime général nous parait une bonne chose, mais on peut se demander pourquoi Emmanuel Macron ne l'a pas fait en sa qualité de ministre. Ensuite, concernant le doublement des plafonds, nous supposons qu’on parle ici des de ceux chiffre d'affaires hors taxe. Pour les commerçants, la limite est de 82 800 € et 33 100 € pour les prestataires de service. Le problème de ce statut de micro-entreprise, c'est qu'il exempt ces indépendants de TVA, donc cela réduit considérablement les recettes de l'Etat. 
Cette mesure est dans la continuité de sa politique pour les indépendants, indépendants qui sont moins protégés contre les aléas. La facilitation du passage en micro-entreprise risque de faire grimper le nombre d'indépendants en situation de salariat déguisé, tout en rendant complexe le fait de recruter du fait de la nature du régime de micro-entreprise. La concurrence déloyale qu'il prétend donc effacer sera donc toujours bien présente, mais risque d'être plutôt au détriment des micro-entrepreneurs, qui risquent de devenir toujours plus des indépendants dépendants des autres entreprises (ce qu'on observe déjà avec le RSI). 
La mesure détaillée sur le programme complet nous parle de "transformer le CICE en allègement permanent de cotisations sociales de 6 points", ce qui revient à une baisse des cotisations patronales, forcément au détriment des cotisations des salariés.

**Comment by ClaXus** [comment]
Quelques liens : 
http://droit-finances.commentcamarche.net/contents/614-micro-entreprise-guide-pratique
http://www.lemonde.fr/les-decodeurs/article/2015/03/11/pourquoi-les-travailleurs-independants-fustigent-le-rsi_4591124_4355770.html
http://www.alternatives-economiques.fr/reste-a-charge-paie-quoi/00012310

**Comment by sarah48** [comment]
Quelques petites remarques sur la proposition de ClaXus:
-Dire que c'était une promesse de campagne de Hollande me paraissait bien
-Est ce que le statut de la micro-entreprise n'implique pas aussi un fort allègement de charges par rapport au statut de salarié? donc baisse des recettes etc.
-mettre quelques liens pour illustrer serait bien
Sur la forme:
-"on parle ici des de ceux chiffre d'affaires hors taxe"
-"pour les indépendants, indépendants qui sont moins protégés contre les aléas." Répétition de "indépendants", et "les aléas" de quoi?

**Comment by Scalpi** [comment]
D'accord sur cette refonte mais tu as enlevé une partie de mon texte
importante, en relation avec le sujet et surtout très révélatrice de
l'idéologie du type. Je reprends ci-dessous et histoire de la création de
son FPI dont je ne trouve aucune trace dans son cadrage budgétaire...

Plus généralement sur le chapitre du candidat concernant l’entreprise, nous
retrouvons sans surprise l’état d’esprit néo ? libéral que nous lui
connaissons, baisse des charges patronales voire suppression pour le SMIC,
un PFU taxé à 30 % sur les revenus mobiliers, ce qui permettrait je
cite : « *Il simplifiera   considérablement le choix des investisseurs qui
se détermineront uniquement en fonction du rendement *». Nous y voilà, le
critère le plus important pour le candidat est que les investisseurs
maximisent encore et toujours plus le rendement de leurs investissements.
Pour finir, il veut créer un Fonds pour l’Industrie et l’Innovation, 10
milliards. Où va-t-il chercher l’argent ? Dans les actions encore détenues
par l’état dans certaines grandes entreprises. Plus aucun contrôle de
l’état donc ? Nous vous laissons juges.

**Comment by Scalpi** [comment]
Et j'ajoute que je connais très bien le RSI, comment ça fonctionne etc
puisque j'en ai été une des victimes.

**Comment by ClaXus** [comment]
Synthèse : (avec corrections)

MEFIANCE

Tout d'abord, la suppression du RSI et la réintégration des bénéficiaires dans le régime général nous parait une bonne chose, mais on peut se demander pourquoi Emmanuel Macron n'a pas honoré cette promesse de campagne de François Hollande en sa qualité de ministre. Ensuite, concernant le doublement des plafonds, nous supposons que l’on parle ici des chiffre d'affaires hors taxe. Pour les commerçants, la limite est aujourd'hui de 82 800 € et 33 100 € pour les prestataires de service. Le problème de ce statut de micro-entreprise, c'est qu'il exempt ces indépendants de TVA, donc cela réduit considérablement les recettes de l'Etat.
Cette mesure est dans la continuité de sa politique pour les indépendants, indépendants qui sont moins protégés contre les aléas de la vie personnelle et professionnelle. La facilitation du passage en micro-entreprise risque de faire grimper le nombre d'indépendants en situation de salariat déguisé, tout en rendant complexe le fait de recruter du fait de la nature du régime de micro-entreprise. La concurrence déloyale qu'il prétend donc effacer sera donc toujours bien présente, mais risque de se faire plutôt au détriment des micro-entrepreneurs, qui risquent de devenir encore plus des indépendants dépendants des autres entreprises (ce qu'on observe déjà avec le RSI). A nouveau, cela risque de diminuer toujours plus les recettes de l'Etat.
La mesure détaillée sur le programme complet nous parle de "transformer le CICE en allègement permanent de cotisations sociales de 6 points", ce qui revient à une baisse des cotisations patronales, forcément au détriment des cotisations des salariés. 


http://www.lemonde.fr/les-decodeurs/article/2015/03/11/pourquoi-les-travailleurs-independants-fustigent-le-rsi_4591124_4355770.html
http://droit-finances.commentcamarche.net/contents/614-micro-entreprise-guide-pratique
http://www.alternatives-economiques.fr/reste-a-charge-paie-quoi/00012310

**Comment by Scalpi** [comment]
Ben t'as rien changé en fait.. Petite coquille ici :  toujours plus des
indépendants dépendants des autres entreprises

**Comment by sarah48** [comment]
Propositions de corrections de forme sur la 2ème proposition de ClaXus:
-"Cette mesure est dans la continuité de sa politique pour les **indépendants, indépendants** qui sont moins protégés"-> "Cette mesure est dans la continuité de sa politique pour les indépendants, **lesquels** qui sont moins protégés"

-"mais **risque** de se faire plutôt au détriment des micro-entrepreneurs, qui **risquent** de devenir encore plus **des indépendants dépendants** des autres entreprises"->"mais risque de se faire plutôt au détriment des micro-entrepreneurs, qui **pourraient** devenir encore plus **des dépendants** des autres entreprises"

**Comment by LVAI** [comment]
@ClaXus pour la mesure je vais reprendre ton texte avec les corrections de Sarah et quelques reformulations perso.
Par contre pour j'ai besoin de sources et je ne peux pas aller moi-même fouiller dans les liens que tu as mis. Est-ce que tu pourrais me faire un récap avec les passages de ton textes et les sources d'info ?
Il faudrait au moins 2 sources, 3-4 seraient mieux.
************
### Analyse reformulée
Tout d'abord, la suppression du RSI et la réintégration des bénéficiaires dans le régime général nous parait une bonne chose, mais on peut se demander pourquoi Emmanuel Macron n'a pas honoré cette promesse de campagne de François Hollande en sa qualité de ministre. Ensuite, concernant le doublement des plafonds, nous supposons que l’on parle ici des chiffres d'affaires hors taxe. Pour les commerçants, la limite est aujourd'hui de 82&nbsp;800&nbsp;€ et de 33&nbsp;100&nbsp;€ pour les prestataires de service. Le problème de ce statut de microentreprise, c'est qu'il exempte ces indépendants de TVA, donc cela réduit considérablement les recettes de l'Etat.
Cette mesure est dans la continuité de sa politique pour les indépendants, lesquels sont moins protégés contre les aléas de la vie, personnels et professionnels. La facilitation du passage en microentreprise risque de faire grimper le nombre d'indépendants en situation de salariat déguisé, tout en complexifiant le recrutement du fait de la nature du régime de microentreprise. La concurrence déloyale qu'il prétend donc effacer sera restera donc bien présente et risque de se faire au détriment des micro-entrepreneurs qui pourraient devenir encore plus dépendants des autres entreprises (ce qu'on observe déjà avec le RSI). A nouveau, cela risque de diminuer toujours plus les recettes de l'Etat.
La mesure détaillée sur le programme complet indique une volonté de "transformer le CICE en allègement permanent de cotisations sociales de 6 points", ce qui revient à une baisse des cotisations patronales, forcément au détriment des cotisations des salariés.

**Comment by sarah48** [comment]
Lègere modification, avec un petite correction et l'ajout d'une petite conclusion et d'un lien:

"Tout d'abord, la suppression du RSI et la réintégration des bénéficiaires dans le régime général nous parait une bonne chose, mais on peut se demander pourquoi Emmanuel Macron n'a pas honoré cette promesse de campagne de François Hollande en sa qualité de ministre. Ensuite, concernant le doublement des plafonds, nous supposons que l’on parle ici des chiffres d'affaires hors taxe. Pour les commerçants, la limite est aujourd'hui de 82 800 € et de 33 100 € pour les prestataires de service. Le problème de ce[ statut de microentreprise](
http://droit-finances.commentcamarche.net/contents/614-micro-entreprise-guide-pratique), c'est qu'il exempte ces indépendants de TVA, donc cela réduit considérablement les recettes de l'Etat.
Cette mesure est dans la continuité de sa politique pour les indépendants, lesquels sont moins protégés contre les aléas de la vie, personnels et professionnels. La facilitation du passage en microentreprise risque de faire grimper le nombre d'indépendants en situation de salariat déguisé, tout en complexifiant le recrutement du fait de la nature du régime de microentreprise. La concurrence déloyale qu'il prétend donc effacer **restera** donc bien présente et risque de se faire au détriment des micro-entrepreneurs qui pourraient devenir encore plus dépendants des autres entreprises (ce qu'on observe déjà avec le RSI). A nouveau, cela risque de diminuer toujours plus les recettes de l'Etat.
La mesure détaillée sur le programme complet indique une volonté de "transformer le CICE en allègement permanent de cotisations sociales de 6 points", ce qui revient à une baisse des cotisations patronales, forcément au détriment des cotisations des salariés. **Une mesure finalement très coûteuse pour l'Etat.**"

**Comment by LVAI** [comment]
Commited
