### ISSUE TITLE
7.6 emplois francs

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#8]
Cette mesure, les [« emplois francs » est simplement la poursuite d'une mesure prise en 2013 par François Lamy](http://alternatives-economiques.fr/blogs/abherve/2017/03/02/emmanuel-macron-et-le-retour-des-emplois-francs-ou-lart-de-reprendre-un-programme-qui-a-echoue/#more-16048), et [arrêtée en 2014 ](http://alternatives-economiques.fr/blogs/abherve/category/emplois-francs/).
Elle a eu un impact extrêmement faible, comme le montre [l'exemple de Calais, ou aucun contrat n'a été signé](http://www.lavoixdunord.fr/region/experimentes-a-calais-les-emplois-francs-font-un-flop-ia33b0n2931791).

Avec cette mesure, « En Marche » poursuit une politique entamée il y a déjà plus de 20 ans (en 1996 sous le gouvernement Juppé), qui a clairement échoué, ce qu'on appelle les « zones franches ». La différence étant qu'au lieu d'accorder des exonérations de charges pour les entreprises, celles-ci bénéficient donc directement d'une prime.
Cette politique s'inscrit dans le cadre plus général des concessions faites aux entreprises dans le but de relancer l'activité économiques dans les « banlieues ». Depuis 1996, plus d'une centaine de Zones Franches Urbaines (ZFU) se sont créées. La [hausse de l'activité économique a été globalement assez faible](http://www.lecese.fr/content/le-cese-dressera-un-bilan-du-dispositif-des-zones-franches-urbaines-en-matiere-deconomie-et-demploi), d'autant plus qu'une large majorité des emplois créés ne profitent pas aux habitants des quartiers en question. [Entre 2003 et 2014, le taux de chômage dans les Zones Urbaines Sensibles est passé de 17 à 24% !](http://www.inegalites.fr/spip.php?article312)

**Comment by lucasgautheron** [comment]
Merci
