### ISSUE TITLE
2.3 : « Nous combattrons la précarité en responsabilisant les employeurs.»

### ISSUE THREAD

**Issue by Scalpi** [Insoumis/programme-macron#82]
# 2.3 Nous combattrons la précarité en responsabilisant les employeurs
Nous créerons un bonus-malus sur l’assurance-chômage. Les employeurs qui entretiennent la précarité en recourant exagérément aux contrats courts paieront plus de charges, ceux qui créent des emplois stables en paieront moins.

## GRANDE MÉFIANCE

Comme souvent, les propositions d'EN MARCHE sont imprécises et interprétables. 
Bonus/Malus sur l’assurance chômage, par quel mécanisme ? Quelle est la relation faite entre assurance chômage et l’abus des employeurs recourant à la précarité ? Il ne dit pas combien de fois on autorise le recours exagéré. « Ils paieront plus de charges », combien ? Notons que par ailleurs EM propose une baisse des charges patronales ce qui rendrait la présente mesure quelque peu efficace...

**Comment by lucasgautheron** [comment]
méfiance OK, moi ce qui m'intrigue c'est la baisse des charges patronales // qui rendrait cette mesure peu efficace

**Comment by Scalpi** [comment]
Pas faux, un peu contradictoire en effet. Tu peux le mentionner.

2017-04-04 11:51 GMT+02:00 Lucas Gautheron <notifications@github.com>:

**Comment by LVAI** [comment]
@Scalpi une contre-proposition :

"En Marche" souhaite pénaliser les entreprises qui ont recours à des contrats précaires en augmentant le montant de leur cotisations chômage dans le but de les inciter à limiter cette pratique. A l'inverse, les contrats stables seront récompensés par des baisses de cotisation.
On peut tout d'abord s’interroger sur les détails de cette mesure : qu'est-ce qu'un contrat précaire selon "En Marche" ? Dans quelle proportion les cotisations seront réduites et/ou augmentées ?
Mais plus encore, on peut se demander l'efficacité de cette proposition, qui fonctionne par l'incitation financière alors qu' "En Marche" propose de baisser un grand nombre des charges qui pèse sur les entreprises ([réduction des cotisations sociales par exemple](https://en-marche.fr/emmanuel-macron/le-programme/travail-emploi)). Ces dernière auront donc le loisir d'absorber le surplus des cotisations lié à leurs salariés en situation de précarité.
Ensuite, il y a une incohérence à nouveau, concernant le chômage qu' "En Marche" souhaite étendre et qu'il aura du mal à financer s'il vise à réduire les cotisations chômage.

**Comment by Scalpi** [comment]
ça me va sauf la dernière phrase, je propose "Ensuite, il y a une
incohérence à nouveau concernant le chômage. Il souhaite visiblement le
diminuer mais nous avons une belle contradiction avec cette mesure visant à
réduire les cotisations chômage". dernière avec un s

**Comment by sarah48** [comment]
Petites corrections sur l'avant dernière phrase: "Ces **dernières** auront donc le loisir d'absorber le surplus des cotisations **liées** à leurs salariés en situation de précarité."
Je suis pas d'accord sur la critique de la dernière phrase. Il ne dit pas ici qu'il veut réduire les cotisations chômages. En baissant certaines et en augmentant d'autres, ça peut s'équilibrer, en tout cas c'est comme ça que je le comprend. A mon avis cette critique doit plutot s'adresser à d'autres mesures d'EM.

**Comment by LVAI** [comment]
Sarah,

L'objectif est d'encourager les entreprises à limiter leur contrats
précaires et du coup tendre vers une situation avec plus de contrats
stables donc plus d'allégements que d'augmentation, non ?
Si tu confirmes que ça réduira peu probablement les cotisations, j'enlève.
Sinon j'essaye de faire une contreproposition pour clarifier.

**Comment by sarah48** [comment]
Lutine, en effet, j'avais pas vu les choses comme ça. Je propose donc de reformuler, en essayant de clarifier un peu, meme si du coup c'est plus long:
"Enfin il nous semble qu'il y a une incohérence: "En marche" [souhaite d'un côté élargir le bénéfice des allocations chômages à de nouvelles professions](http://analysons-macron.fr/#c2m5), ce qui mènerait à une hausse des dépenses dans ce domaine. Mais de l'autre, si la mesure dont nous parlons ici atteint son objectif affiché, il y aurait donc plus de contrats stables, et donc plus d'allégements de cotisations. Ce qui pose un problème budgétaire, d'autant plus que le programme d'"En Marche" propose beaucoup d'autres allègements de charges."

**Comment by LVAI** [comment]
Version finale ?

"En Marche" souhaite pénaliser les entreprises qui ont recours à des contrats précaires en augmentant le montant de leur cotisations chômage dans le but de les inciter à limiter cette pratique. A l'inverse, les contrats stables seront récompensés par des baisses de cotisation.
On peut tout d'abord s’interroger sur les détails de cette mesure : qu'est-ce qu'un contrat précaire selon "En Marche" ? Dans quelle proportion les cotisations seront réduites et/ou augmentées ?
Mais plus encore, on peut se demander l'efficacité de cette proposition, qui fonctionne par l'incitation financière alors qu' "En Marche" propose de baisser un grand nombre des charges qui pèse sur les entreprises ([réduction des cotisations sociales par exemple](https://en-marche.fr/emmanuel-macron/le-programme/travail-emploi)). Ces dernières auront donc le loisir d'absorber le surplus des cotisations liées à leurs salariés en situation de précarité
Enfin il nous semble qu'il y a une incohérence: "En marche" [souhaite d'un côté élargir le bénéfice des allocations chômages à de nouvelles professions](http://analysons-macron.fr/#c2m5), ce qui mènerait à une hausse des dépenses dans ce domaine. Mais de l'autre, si la mesure dont nous parlons ici atteint son objectif affiché, il y aurait donc plus de contrats stables, et donc plus d'allégements de cotisations. Ce qui pose un problème budgétaire, d'autant plus que le programme d'"En Marche" propose beaucoup d'autres allègements de charges.

**Comment by Scalpi** [comment]
ça me va.

**Comment by sarah48** [comment]
Ok pour moi

**Comment by LVAI** [comment]
Commited
