### ISSUE TITLE
3.8 : « Nous créerons une banque de données numériques.»

### ISSUE THREAD

**Issue by Scalpi** [Insoumis/programme-macron#83]
MÉFIANCE
Il est difficile de comprendre le sens et l’objectif de cette proposition. Nous avons fouillé dans son programme mais nous n’avons pas trouvé plus de détail sur ce volet. 
« Les administrations chargées d’autoriser des activités (l’ouverture d’un hôtel, ou l’obtention d’une licence de chauffeur privé, ...) devront mettre à disposition leurs données » : Mettre à disposition de qui ? Quel contrôle et quel objectif ? 
« Face aux géants étrangers, des nouvelles start-ups pourront ainsi s’adresser par exemple à tous les hôteliers pour leur offrir de nouveaux services » Des nouvelles start-ups éventuellement étrangères ? Offrir de nouveaux services, c’est du BtoB (business entre entreprises), ça existe largement sur internet aujourd’hui et nous ne voyons franchement pas la valeur ajoutée de cette « nouvelle » banque de données. Pas clair donc méfiance.

**Comment by lucasgautheron** [comment]
c'est du pinaillage non, quant à mettre leurs données à disposition à qui, et bien à n'importe qui est prêt à payer pour mais de façon organisée. je pense que le vrai risque c'est l'uberisation de certains services

**Comment by Scalpi** [comment]
Pinaillage, je trouve pas. On imagine à quoi ça peut servir mais je dis
juste que la mesure n'étant pas clairement fléchée, ça cache quelque chose.

2017-04-04 11:49 GMT+02:00 Lucas Gautheron <notifications@github.com>:

**Comment by sarah48** [comment]
Nouvelle proposition. J'ai rajouté et modifié beaucoup de choses, parce que j'ai pris un autre angle d'attaque.

C'est dangereux (orange)

"« En Marche » souhaite donc que les données récoltées par ces administrations soient mises à la disposition de « nouvelles start-ups ». Autrement dit, qu'elles soient vendues à ces start-ups. Sous quelles modalités? Quel contrôle et quel objectif ? Nous n'en savons rien. Les start-ups étrangères pourraient-elles acheter de cette manière des données personnelles collectées par les administrations françaises? Cette hypothèse semble dangereuse...

Surtout, cette mesure pose un gros problème en matière de respect de la vie privée et de protection des données personnelles. La [commercialisation de certaines données dites « sensibles » est interdite](http://www.ls-avocats.com/article-presse/53-donnee-perso), comme les données médicales. Et le reste des données personnelles, avec quelques exceptions, doit faire l'objet d'une[ déclaration préalable auprès de la Commission Nationale Informatique et Liberté (CNIL)](https://www.service-public.fr/professionnels-entreprises/vosdroits/F24270), qui doit donner son autorisation pour certains fichiers.

Il s'agit en fait d'ouvrir les données des administrations aux entreprises privées, alors que la[ loi numérique adoptée en 2015, encouragée par E.Macron](http://www.lemonde.fr/pixels/article/2015/09/26/la-loi-numerique-cible-les-donnees-personnelles_4772884_4408996.html), avait déjà prévu l'ouverture de ces données au public. Ceci, alors que[ la protection des données personnelles est déjà fortement remise en cause dans l' europe actuelle](
https://www.wsws.org/fr/articles/2013/nov2013/nsax-n05.shtml)..."

**Comment by LVAI** [comment]
commited
