### ISSUE TITLE
5.9 : « Nous créerons un état-major permanent des opérations de sécurité intérieure, de renseignement et de lutte contre le terrorisme.»

### ISSUE THREAD

**Issue by Scalpi** [Insoumis/programme-macron#85]
CONFUSION et MÉFIANCE
La confusion est dans l’organigramme. Un état-major (et son chef) qui serait rattaché directement et en permanence au président de la République, signifierait qu'il passe outre les fonctions du 1er ministre. Il serait amené à associer (coordonner ?) les ministères de la Défense et de l’Intérieur et accessoirement d’autres ministères comme l’Industrie, alors que ces ministres sont sous l’autorité du 1er ministre. Cela pose donc un vrai problème en matière de respect des prérogatives attribuées au président et au 1er ministre par la constitution, sur un sujet aussi régalien que celui-ci.

Ensuite, cette mesure pose beaucoup d’autres questions : EN MARCHE suggère-t-il de mélanger les genres entre police nationale, corps de gendarmerie et armée?
Sur un thème très voisin dans le programme d'EN MARCHE : « Nous créerons une cellule spéciale du renseignement anti-Daech, permanente, de 50 à 100 agents, associant les principaux services de renseignement, placée auprès du Président de la République ». Mais cette cellule existe déjà et comporte quelques dizaines de personnes (difficile d'en connaître exactement le nombre). On notera aussi que ce n’est pas le fait de passer à 50 ou 100 agents qui va révolutionner le Renseignement. Cette cellule placée auprès du président de la République passerait-elle outre l'Etat-major, qui passerait lui-même outre le 1er ministre? Tout cela est confus et quand c’est confus, méfiance.

**Comment by Scalpi** [comment]
Notre programme sur le volet de la sécurité a été jugé le plus pertinent par l’un des spécialistes publics de la criminologie. C’est une caution de plus pour notre programme.

**Comment by sarah48** [comment]
C'est de Alain Bauer dont tu parles je crois.

**Comment by Scalpi** [comment]
Oui mais je pense pas qu'on puisse le citer.

2017-04-05 17:20 GMT+02:00 sarah48 <notifications@github.com>:

**Comment by sarah48** [comment]
Oui, de toutes façons je crois qu'il ne vaut mieux pas en parler

**Comment by sarah48** [comment]
Je propose une nouvelle version:

"La confusion est dans l’organigramme. Un état-major (**et son chef**) qui **serait** rattaché **directement et en permanence** au président de la République, **signifierait** qu'il **passe outre les fonctions** du 1er ministre. Il serait amené à associer (coordonner ?) les ministères de la Défense et de l’Intérieur et accessoirement d’autres ministères comme l’Industrie, alors que ces ministres sont sous l’autorité du 1er ministre. **Cela pose donc un vrai problème en matière de respect des prérogatives attribuées au président et au 1er ministre par la constitution,** sur un sujet aussi régalien que celui-ci.

Ensuite, cette mesure pose beaucoup d’autres questions : EN MARCHE suggère-t-il de mélanger les genres entre police nationale, corps de gendarmerie **et armée**? 
Sur un thème très voisin dans le programme d'EN MARCHE : « Nous créerons une cellule spéciale du renseignement anti-Daech, permanente, de 50 à 100 agents, associant les principaux services de renseignement, placée auprès du Président de la République ». **Mais** cette cellule existe déjà et comporte, sauf erreur, 35 personnes. On **note aussi** que ce n’est pas le fait de passer à 50 ou 100 agents qui va révolutionner le Renseignement. Cette cellule placée auprès du président de la République **passerait-elle outre l'Etat-major, qui passerait lui-même outre le 1er ministre**? Tout cela est confus et quand c’est confus, méfiance."

J'ai enlevé "en collateral", ça complique un peu je trouve.
J'ai enlevé "l’organisation matricielle", je ne savais pas ce que ça voulait dire, ça semble plutot correspondre à la situation mais je pense que c'est un concept un peu trop compliqué qui ne parlera pas à grand monde.

J'ai enlevé "Qu’y aurait-il à coordonner quand on parle de sécurité intérieure avec le ministère de l’industrie ?" parce que pour moi il y a une réponse, c'est que il y aurait une coordination pour la protection de nos industries et de nos industries stratégiques.

J'ai mis au conditionnel car c'est conditionnel (et heureusement :) ). Et j'ai enlevé le futur.

Sur cette partie: "EN MARCHE suggèrent-ils de mélanger les genres entre police nationale et corps de gendarmerie ?" Je crois que c'est plus que le "corps de gendarmerie", il s'agit d'associer l'Etat-major du ministère de la défense, donc pas seulement la gendarmerie mais aussi l'armée. Je pnese qu'on pourrait en dire plus la dessus, mais à voir plus tard peut être.

Enfin pour la cellule de 35 personnes, tu as un lien? Le nom de la cellule, ou l'organisme auquel elle est rattachée?

**Comment by Scalpi** [comment]
Tes modifs me vont. Sur la cellule à 35 personnes, je vais chercher mais je
sais que ça a été dit par A. Bauer. Ce type d'information par nature est
pas évident à trouver mais je cherche.

**Comment by sarah48** [comment]
Nouvelle proposition en enlevant le passage sur la cellule de 35 personnes, faute de sources, que j'ai remplacé par autre chose suite à une petite recherche:

"La confusion est dans l’organigramme. Un état-major (et son chef) qui serait rattaché directement et en permanence au président de la République, signifierait qu'il passe outre les fonctions du 1er ministre. Il serait amené à associer (coordonner ?) les ministères de la Défense et de l’Intérieur et accessoirement d’autres ministères comme l’Industrie, alors que ces ministres sont sous l’autorité du 1er ministre. Cela pose donc un vrai problème en matière de respect des prérogatives attribuées au président et au 1er ministre par la constitution, sur un sujet aussi régalien que celui-ci. Ensuite, cette mesure pose beaucoup d’autres questions : EN MARCHE suggère-t-il de mélanger les genres entre police nationale, corps de gendarmerie et armée?

Sur un thème très voisin, **EN MARCHE propose aussi de « créer** une cellule spéciale du renseignement anti-Daech, permanente, de 50 à 100 agents, associant les principaux services de renseignement, placée auprès du Président de la République ». **Mais comme le souligne le criminologue Alain Bauer, et comme le reconnait Patrick Calvar, le patron de la DGSI,[ le problème n'est pas tant le manque de renseignements que le manque de personnels compétents pour le traitement et l'analyse de ces renseignements](https://www.franceinter.fr/societe/secrets-d-info), en particulier de personnels spécialisés dans d'autres domaines, comme l’économie, la finance, la psychologie ou les langues.**

Enfin, cette cellule placée auprès du président de la République passerait-elle outre l'Etat-major, qui passerait lui-même outre le 1er ministre? Tout cela est confus et quand c’est confus, méfiance."

**Comment by Scalpi** [comment]
C'est bien

**Comment by LVAI** [comment]
Commited
