### ISSUE TITLE
2.5 Nous permettrons à tous les travailleurs d’avoir droit à l’assurance-chômage.

### ISSUE THREAD

**Issue by Zedhyn** [Insoumis/programme-macron#88]
[insert] from Zedhyn

# Nous permettrons à tous les travailleurs d’avoir droit à l’assurance-chômage.

### C'est contradictoire !

Mais comment va-t-il financer l'assurance chômage auprès des ayants-droits en supprimant les cotisations chômages qui servent, aujourd'hui, à financer cette assurance ? "Nous augmenterons le salaire net de chacun, en supprimant les cotisations chômage et maladie." [source](http://www.en-marche.fr/emmanuel-macron/le-programme/entreprises).
Cette proposition si alléchante pour les personnes concernées par cette mesure ne serait alors qu'un élément de langage ? Vous aurez droit à l'assurance chômage mais celle-ci ne sera plus financé....
Ainsi, en cherchant du côté des [orientations budgétaires du programme "En Marche"](https://storage.googleapis.com/en-marche-fr/E-MAILING/2017/images/Projet-eco-fin/EN-MARCHE-FICHE-SYNTHSE-ECO-BUDGET.pdf), nous découvrons avec stupeur une super économie de 10 milliards d'euros annuelle sur l'assurance chômage ([sur un coût global du chômage estimé en 2015 à 76 Mds/an](http://www.lefigaro.fr/vox/economie/2015/04/27/31007-20150427ARTFIG00329-le-cout-insoutenable-du-chomage.php)) alors même que Mr. Macron ouvre le chômage à tous les entrepreneurs, agriculteurs, artisans et professions libérales...
Pour montrer la clarté du programme "En Marche" nous avons eu beau chercher comment serait financé l'assurance chômage étant donné que les cotisations chômages seront supprimées et, figurez-vous, qu'il n'y a rien à ce sujet dans ces mêmes orientations budgétaires. 
Par ailleurs, Emmanuel Macron souhaite également que les salariés démissionnaires puissent également avoir droit à l'assurance chômage ce qui est qualifié d'être potentiellement "[une bombe financière](http://www.lefigaro.fr/conjoncture/2017/03/17/20002-20170317ARTFIG00356-assurance-chomage-les-failles-de-macron.php)" selon  Anne de Guigné, journaliste au Figaro.

Alors le chômage pour tous, info ou intox ?

ajouter aux liens LAEC : https://laec.fr/s26m3

**Comment by LVAI** [comment]
## Proposition

On peut se demander comment "En Marche" compte financer l'assurance chômage.
En effet, d'une part son programme prévoit d'élargir les conditions d'éligibilité non seulement aux artisans, commerçants indépendants, entrepreneurs, professions libérales et agriculteurs, mais également salariés démissionnaires ([source](http://www.en-marche.fr/emmanuel-macron/le-programme/emploi-ch%C3%B4mage-securites-professionnelles)).
En parallèle, il prévoit de supprimer les cotisations chômage ([source](http://www.en-marche.fr/emmanuel-macron/le-programme/entreprises)), d'économiser 10 milliards d'euros annuel sur l'assurance chômage (soit 13%).
Ces mesures sont particulièrement contradictoires et il ne semble pas y avoir d'autres financements des allocations chômage de prévues.

**Comment by LVAI** [comment]
update done
à upload
