### ISSUE TITLE
5.4 Nous ne tolèrerons plus les incivilités

### ISSUE THREAD

**Issue by LVAI** [Insoumis/programme-macron#89]

**Comment by LVAI** [comment]
[Premiers éléments]

Dans l'objectif 3 de son [programme détaillé sur l'égalité hommes-femmes](https://en-marche.fr/emmanuel-macron/le-programme/%C3%A9galit%C3%A9-hommes-et-femmes), "En Marche" prévoie un plan de lutte contre le harcèlement et les agressions qui touchent les femmes en trois points 
- campagne nationale de communication et de sensibilisation sur le harcèlement et les violences faites aux femmes.
- augmentation du montant des amendes pour incivilité avec paiement immédiat.
- la généralisation du téléphone d’alerte 

Dans l'objectif 1 de son [programme détaillé sur la sécurité](https://en-marche.fr/emmanuel-macron/le-programme/securite), "En Marche" indique sa volonté de mettre en place une police de la sécurité quotidienne 
- Nous diminuerons la bureaucratie et imposerons un retour au coeur du métier de policier pour plus de présence sur le terrain.
- Nous mettrons en place des outils répressifs au plus proche du terrain et mieux adaptés.
- Nous intégrerons davantage les forces de sécurité dans les quartiers.
- L’échelon du quartier doit être préféré à celui de la commune.
- Nous susciterons des partenariats locaux innovants entre policiers et habitants.
- Nous accroîtrons la déconcentration des responsabilités au sein des services de police et de gendarmerie, et donc les marges d’autonomie, pour permettre aux échelons les plus bas une meilleure prise en charge des problèmes spécifiques locaux.
- Nous conditionnerons l’attribution de moyens supplémentaires au fonctionnement efficace des contrats locaux de sécurité et de prévention de la délinquance.

**Comment by Scalpi** [comment]
Je pense pas qu'il soit nécessaire de trop détailler cette partie du programme de Macron, il faut critiquer

**Comment by Scalpi** [comment]
Ce thème est compliquée car il y a pas mal de mesures que nous partageons. Nous pourrions en citer quelques unes en disant "c'est bien mais...". Je pense que le bon angle de critique c'est de dire : "Tant qu'on n'aura pas résolu le problème d'inégalité Femmes / Hommes dans les domaines du social et du professionnel - l'égalité des salaires -, toutes les autres mesures, même de bonne volonté, ne sont que fariboles. EM n'aborde pas clairement ces 2 questions fondamentales"

**Comment by sarah48** [comment]
Je propose ça, j'en suis restée à la proposition en elle meme sans élargir à la question de l'égalité homme-femme.

Méfiance (orange)

"Cette mesure s'inscrit dans la doctrine sécuritaire de la ["tolérance zéro]( https://fr.wikipedia.org/wiki/Tol%C3%A9rance_z%C3%A9ro)"  car elle vise à raccourcir au maximum le délai entre le délit et la sanction, en donnant une réponse systématique à tous les faits pénaux, aussi mineurs soient-ils, comme les crachats. 

Concernant les crachats,[ qui sont déjà interdits par la loi](https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=9A1B29F0AB552155AD3A82F1299CEEE0.tpdjo16v_3?idArticle=LEGIARTI000006880311&cidTexte=LEGITEXT000006074984&dateTexte=20081211) , certaines municipalités ont déjà pris des[ "arrêtés anti-crachats", comme la ville de Béziers et son maire, Robert Ménard](http://www.20minutes.fr/politique/1446551-20140920-beziers-robert-menard-prend-arrete-anti-crachats), proche du FN. [Les insultes peuvent aussi déjà être punies par des contraventions](https://www.service-public.fr/particuliers/vosdroits/F32077), quand elles sont d'ordre privées.

Quant au harcèlement des femmes, hormis des cas évidents, il semble souvent important d'effectuer une enquête judiciaire. On peut dire la même chose concernant la dégradation de mobilier urbain. 
Si cette mesure permettra de réduire la charge de travail des tribunaux judiciaires, elle augmentera celle des tribunaux administratifs."

**Comment by LVAI** [comment]
C'est bien mais ça me parait léger, non ?
Vous trouvez que ça suffit ?
Sinon j'essayerai de compléter.

**Comment by Scalpi** [comment]
Pourquoi vous reprenez pas des suggestions que j'ai faites plus haut. En gros, l'idée est de dire que les incivilités sont la résultante de déséquilibres sociaux entre les gens et aussi entre les femmes et les hommes. Rappelez-vous les incivilités commises à l'assemblée nationale par des hommes envers des femmes députées

**Comment by sarah48** [comment]
« Nous ne tolèrerons plus les incivilités.»
Le harcèlement des femmes, les insultes, la dégradation du mobilier urbain, les crachats... Ces incivilités seront punies d’amendes immédiates et dissuasives. 

C'est peut etre un peu court, mais j'ai essayé d'en rester à la mesure en question, et je vois rien d'autre à dire. J'ai essayé de creuser sur la différence entre tribunaux judiciaires et tribunaux administratifs, mais j'ai rien trouvé de concluant.

Je trouve que partir sur l'égalité homme/femmes, c'est un peu s'éloigner du sujet, alors que ça ne concerne vraiment qu'un des 4 exemples cités dans la mesure. 
Les mesures détaillées en matière de sécurité, je trouve qu'elles concernent plus d'autres mesures, comme celle sur la mise en place d'une sorte de police de proximité.

Pourquoi pas mettre une phrase plus générale si vous voulez, ou dire d'une manière plus générale qu'il faut sortir d'une logique purement répressive. A vous de voir

**Comment by Scalpi** [comment]
Ok alors disons ça : "Les incivilités ont aussi beaucoup à voir avec la
condition sociale. Tant qu'on continuera à maltraiter les gens sur le plan
social, les incivilités seront de plus en plus violentes".

**Comment by sarah48** [comment]
Ok, ça me va, après si vous voulez plus développer, pas de problèmes

**Comment by Scalpi** [comment]
Non, c'est bon.

2017-04-14 11:57 GMT+02:00 sarah48 <notifications@github.com>:

**Comment by LVAI** [comment]
commited
