### ISSUE TITLE
8.4 Erasmus

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#9]
"Erasmus+" est le nouveau nom du programme Erasmus à l'échelle de l'Union Européenne, dont le montant a augmenté de 40% par rapport aux précédents budget, avec 14,7 milliards d'euros sur la période 2014-2020. Ce nouveau programme a pour spécificité d'étendre la mobilité aux [« collégiens, lycéens, étudiants, apprentis, formateurs, jeunes diplômés et demandeurs d'emploi, jeunes avec ou sans diplômes, personnels éducatifs ou associatifs »](http://www.touteleurope.eu/les-politiques-europeennes/education-et-formation/synthese/le-programme-de-mobilite-erasmus.html). Il permet donc déjà les [échanges pour les apprentis](http://www.generation-erasmus.fr/bourse-erasmus-stage-apprenti/) !    

Quant au chiffre avancé de 200 000, il est vrai qu'actuellement il semble que nous soyons très loin de ce chiffre ([environ 73 000 étudiants à l'étranger au total en 2015](http://www.lemonde.fr/campus/article/2016/03/23/un-etudiant-francais-sur-trois-a-etudie-en-partie-a-l-etranger_4888327_4401467.html)). 
Mais avec la hausse du budget de l'Union Européenne (UE), et l'élargissement des publics susceptibles de 
participer à ce programme,[ il est évident qu'une hausse considérable du nombre d'échanges est déjà en cours](https://www.agence-erasmus.fr/docs/2244_rapport-2014.pdf). Comment la France contribuera à cette augmentation? Et surtout, y contribuera-t-elle, au-delà de sa participation au budget de l'UE ? Rien n'est précisé, donc l'impression est que sur ce point, « En Marche » compte surtout sur l'UE pour réaliser cet engagement....

Enfin cette mesure ne répond pas au problème des ressources données aux étudiants pour ces échanges internationaux. En effet, parmi eux, « [quatre étudiants sur dix bénéficient d’une aide publique, laquelle couvre environ 40 % des frais](http://www.lemonde.fr/campus/article/2016/03/23/un-etudiant-francais-sur-trois-a-etudie-en-partie-a-l-etranger_4888327_4401467.html) », ce qui est largement insuffisant, et qui renforce les inégalités entre étudiants.

**Comment by lucasgautheron** [comment]
Merci

**Comment by sarah48** [comment]
J'ai supprimé un paragraphe ou y'avait une erreur et pas utile finalement, et corrigé les petites fautes dont je t'ai parlé hier, si tu peux réintégrer tout le texte sur le site.

**Comment by LVAI** [comment]
@lucasgautheron sur le site il y a une parenthèse en trop :  Il permet donc déjà les échanges pour les apprentis **)** !
+ phrase à reformuler : Quant au chiffre avancé de 200 000, il est vrai qu'actuellement il semble que nous soyons très loin *de ce chiffre* > que nous **en** soyons très loin
