### ISSUE TITLE
9.7 « « Nous renforcerons le droit à l’oubli pour les personnes ayant été malades.»

### ISSUE THREAD

**Issue by Scalpi** [Insoumis/programme-macron#91]
ARNAQUE ET TRÈS INSUFFISANT
Précisons que dans le programme d’EM, cette mesure se limite aux personnes ayant été atteintes de cancers ou de l’hépatite C, le droit à l’oubli étant ramené de 10 à 5 ans. L’intention future serait de l’étendre à d’autres maladies, lesquelles ? Rappelons également que le 24 mars 2015 a été signé un accord entre l’état et les assureurs concernant les cancers et le droit à l’oubli, lequel s’applique différemment en fonction de la pathologie et…des assureurs. Donc c'est une arnaque de présenter cette mesure comme si c’était une nouveauté. Bien sûr, cet accord reste très insuffisant puisque le droit à l’oubli reste dépendant de la volonté des assureurs, suivant les grilles qu’ils définissent eux-mêmes.
Ensuite, dans le cadre d'un emprunt, il faut parler du prix de cette convention, pourcentage qui peut aller de 0,25 à 0,7 du montant du crédit. Dans le cas d’une personne souscrivant un prêt de 250 000 € sur 20 ans, la « couverture » peut coûter jusqu’à 145 € par mois soit un total de près de 35 000 € soit 14% du montant emprunté au bout du compte ! Le champs des maladies entrant dans ce dispositif doit être étendu et le dispositif lui-même revu car en l’état actuel, il est une véritable rente pour les assureurs."
Source : Le Monde du 13/07/2015

**Comment by sarah48** [comment]
J'ai changé le début, parce que sur la page de notre site, la mesure est affichée, donc pas besoin de répeter.

J'ai enlevé "et en plus de la limiter à la seule Hépatite C et aux cancers", c'était déjà dit.

Pour le "prix de cette convention pour l’assuré", si je comprends bien, ça ne concerne pas "l'assuré" puisque ton exemple est celui d'un emprunt auprès d'une banque, donc plutot le souscripteur de l'emprunt. Ce sont deux choses différentes.
Et ce que je ne comprends pas, c'est pourquoi le souscripteur de l'emprunt devrait payer une "couverture" supplémentaire, alors que de ce que j'ai compris, il n'est pas sensé dire qu'il a eu le cancer ou l'hépatite C? La banque n'est pas sensée le savoir non?

J'ai pas retrouvé d'article du monde du 13/07/2015. Tu peux retrouver l'article, et intégrer le lien dans le texte? Pour l'intégrer, tu choisis le passage ou tu veux mettre le lien, puis tu cliques sur la chaine dans la barre d'édition en haut ("Add a link") et la, à la place de "url", tu mets le lien.

Je propose donc quelques modifs pour l'instant:

"Comme indiqué, cette mesure se limite aux personnes ayant été atteintes de cancers ou de l’hépatite C, le droit à l’oubli étant ramené de 10 à 5 ans. L’intention future étant de l’étendre à d’autres maladies. Signalons également que le 24 mars 2015 a été signé un accord entre l**’Etat** et les assureurs concernant les cancers et le droit à l’oubli, **qui** s’applique différemment en fonction de la pathologie et…des assureurs. 
**Donc c'est une arnaque de présenter cette mesure comme une nouveauté**. Bien sûr, cet accord reste très insuffisant **puisque le droit à l’oubli** reste **dépendant** de la volonté des assureurs, **suivant les** grilles qu’ils définissent eux-mêmes. 
Ensuite, **dans le cadre d'un emprunt**, il faut parler du prix de cette convention, pourcentage qui peut aller de 0,25 à 0,7 du montant du crédit. Dans le cas d’une personne souscrivant un prêt de 250 000 € sur 20 ans, la « couverture » peut coûter jusqu’à 145 € par mois soit un total de près de 35 000 € soit 14% du montant emprunté au bout du compte ! Le champs des maladies entrant dans ce dispositif doit être étendu et le dispositif lui-même revu car en l’état actuel, il est une véritable rente pour les assureurs."

**Comment by Scalpi** [comment]
OK, je vais retravailler le texte ce week end.

**Comment by sarah48** [comment]
Donc, après une petite recherche, je ne pense pas que les personnes bénéficiant du droit à l'oubli devront payer plus cher, comme dit ici:

https://www.service-public.fr/particuliers/vosdroits/F20520

**"la convention intègre un droit à l'oubli pour les personnes guéries d'un cancer dont le traitement est terminé, sans rechute, depuis 10 ans au moins (ou 5 ans s'il avait été diagnostiqué avant ses 18 ans). Vous n'avez pas à le signaler à l'assureur, qui ne doit pas vous appliquer de surprime ni vous exclure de la garantie."**

Il est question d'une surprime, mais c'est pour les gens qui ne bénéficient pas au droit à l'oubli.

"En cas d'accord, l'assureur vous informe et peut vous proposer un tarif intégrant une surprime d'assurance qui ne peut pas dépasser 1,4 points de plus que le taux effectif global de l'emprunt (TEG)."

La Grille de référence AERAS donne juste les délais à partir desquels on peut bénéficier du droit à l'oibli pour chaque maladie: http://www.aeras-infos.fr/files/live/sites/aeras/files/contributed/documents/GRILLEREFERENCE4FEVRIER2016.pdf

Aussi, je ne crois pas que ce soit les assureurs eux-mêmes qui définissent les grilles, puisque la convention est signée par:  "l’Etat, les fédérations professionnelles des organismes d’assurance et des établissements de crédit, les associations représentant les personnes malades et les consommateurs." comme dit ici:

http://www.aeras-infos.fr/cms/sites/aeras/accueil/la-convention-aeras/les-signataires.html

Aussi, on ne peux pas dire que "c'est une arnaque de présenter ça comme une nouveauté", parce qu'il ne le presénte pas comme une nouveauté mais comme un renforcement: " Nous renforcerons le droit à l’oubli pour les personnes ayant été malades"

Je propose donc d'enlever ces deux phrases et le dernier paragraphe, et de garder juste la dernière idée. Et de rajouter un dernier paragraphe qui fait lien avec les propositions LAEC que j'ai trouvé:


C'est bien, mais...

"Comme indiqué, cette mesure se limite aux personnes ayant été atteintes de cancers ou d'hépatite C, le droit à l’oubli étant ramené de 10 à 5 ans. L’intention future étant de l’étendre à d’autres maladies. Signalons également que [le 24 mars 2015 a été signé un accord entre l’Etat et les assureurs](http://www.lemonde.fr/sante/article/2015/04/10/le-droit-a-l-oubli-pour-les-malades-du-cancer-adopte_4614125_1651302.html) concernant les cancers et le droit à l’oubli, qui s’applique différemment en fonction de la pathologie et…des assureurs.
Il faut signaler que ce droit à l'oubli est [déjà de 5 ans pour les personnes ayant été atteintes de cancer avant leurs 18 ans](http://www.aeras-infos.fr/cms/sites/aeras/accueil/aeras-en-pratique/les-points-cles/le-droit-a-loubli.html).
Aussi, le champs  des maladies entrant dans ce dispositif devrait être étendu car[ il ne concerne actuellement que les  personnes ayant été atteintes de cancers et de l’hépatite C](http://www.lemonde.fr/sante/article/2017/02/14/prets-le-droit-a-l-oubli-entre-en-vigueur-pour-les-anciens-malades-du-cancer_5079556_1651302.html).
**Enfin, il nous semble que le fait de faire payer plus cher leurs emprunts ou leurs assurances à des personnes malades u ayant été malades est une discrimination qu'il faut combattre, en responsabilisant les banques et les assurances, et en sortant d'une logique de pure rentabilité pour aller vers moins de discrimination et plus d'humanité.**"

Liens LAEC:


.[Création d'un Pôle public bancaire, qui n’aura pas d’activités spéculatives et sera l’un des acteurs centraux de notre politique de crédit.](https://avenirencommun.fr/le-livret-banques/)

.[Nouvelle « Loi bancaire » qui redéfinira les missions publiques de toutes les banques. Elles
seront obligées de prendre en charge une part des clientèles peu « rentables » qui ne seront de la sorte pas uniquement accueillies par le Pôle bancaire public.](https://avenirencommun.fr/le-livret-banques/)


.[Assurer l'égalité réelle et combattre les discriminations fondées sur le genre, le handicap, l'apparence, la couleur de peau, l'âge, l'orientation sexuelle, la religion ou la croyance, l'origine sociale ou la fortune](https://laec.fr/s6m2)


.[Création d'un commissariat de l’égalité et de lutte contre les discriminations qui sera notamment doté d’un pouvoir de contrôle, d’alerte, de saisie et de sanction, d’un corps d’inspecteur·trice·s et d’antennes territoriales.](https://avenirencommun.fr/livret-racisme-discriminations/)

**Comment by Scalpi** [comment]
Ok Sarah. Désolé mais pas eu le temps de creuser. Donc on part sur ta
propale

**Comment by LVAI** [comment]
Committed
