### ISSUE TITLE
8.8 marché unique du numérique

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#93]
"Méfiance" orange

Comme pour d'autres mesures, [cet engagement est aussi celui de la commission européenne](https://ec.europa.eu/commission/priorities/digital-single-market_fr), qui a publié en mai 2015 sa [stratégie à l'horizon 2020 pour un marché unique du numérique](https://www.laquadrature.net/fr/la-commission-europeenne-doit-prendre-en-compte-les-droits-fondamentaux-dans-le-domaine-numerique). La presse en général n'en parle que pour souligner les aspects positifs de cette stratégie ([suppression des tarifs de « roaming », connexion de tous les foyers européens au très haut débit, couverture 5G ...)](https://www.lesechos.fr/21/09/2016/LesEchos/22281-044-ECH_pour-un-marche-unique-du-numerique.htm).

Mais cette volonté vise avant tout à « [faire tomber les barrières réglementaires](
https://ec.europa.eu/commission/priorities/digital-single-market_fr) », [à développer les exportations entre les pays membres, et à amener « de meilleurs services à des prix plus avantageux » ](
https://ec.europa.eu/commission/priorities/digital-single-market_fr). Elle cherche notamment à [« promouvoir des services de livraison transfrontalière », en harmonisant les différentes réglementations, comme sur la TVA](https://ec.europa.eu/commission/priorities/digital-single-market_fr). On peut s'inquiéter de cette volonté d'exacerbation de la concurrence entre les entreprises, d' « harmonisation » qui se fera sans aucun doute par le bas, et de déréglementation en matière fiscale, mais aussi sociale ou environnementale. 

L'autre grand danger de ce projet concerne la «[ lutte contre les atteintes aux droits de propriété intellectuelle](https://ec.europa.eu/commission/priorities/digital-single-market_fr) », avec surtout une « [obligation de filtrage automatisé](http://www.numerama.com/politique/194704-droit-dauteur-commission-presente-directive-tres-critiquee.html) » des contenus, comme sur les plateformes de partage de vidéos. Outre l'utilisation de technologies de filtrage automatisées « [idiotes et binaires](http://www.numerama.com/politique/194704-droit-dauteur-commission-presente-directive-tres-critiquee.html) », cela rejoint le [problème de la généralisation des accords public-privés, pour réguler internet par de puissants acteurs économiques](https://www.laquadrature.net/fr/la-commission-europeenne-doit-prendre-en-compte-les-droits-fondamentaux-dans-le-domaine-numerique), en leur confiant certaines prérogatives de police ou de justice. La commission européenne à d'ailleurs lancé en juillet 2016 un [nouveau partenariat de ce type en matière de cybersécurité](https://ec.europa.eu/commission/priorities/digital-single-market_fr), alors que la protection des données personnelles est [déja largement mise à mal dans l'UE actuelle](https://www.wsws.org/fr/articles/2013/nov2013/nsax-n05.shtml), qui a [récemment remis en cause](https://www.laquadrature.net/fr/la-commission-europeenne-doit-prendre-en-compte-les-droits-fondamentaux-dans-le-domaine-numerique) le principe de « [neutralité du net](https://www.laquadrature.net/fr/elements-pour-la-reforme-du-droit-dauteur-et-des-politiques-culturelles-liees) ».

**Comment by Scalpi** [comment]
ça me va

**Comment by LVAI** [comment]
Commite, à publier
