### ISSUE TITLE
2.4 loi travail (nouvelle version)

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#96]
En clair, « En Marche » se prononce pour le maintien de la loi El Khomri, dite « loi travail », et de son principe central de l'inversion de la hiérarchie des normes. « La primauté sera donnée aux accords d'entreprises sur les accords de branche », indique le complément du programme. Dans la « loi travail », la primauté est donnée d'abord aux accords d'entreprises sur les accords de branches, et aux accords de branches (et d'entreprises) sur la loi. C'est donc une remise en cause de pans entiers de la loi. Les accords d'entreprises ou de branche pourront déroger à la loi, et l'énoncé de cette mesure est particulièrement trompeur.

Surtout, E. Macron à déjà indiqué qu'il voulait une [version «beaucoup plus radicale» de cette loi](http://www.20minutes.fr/politique/1940719-20161012-loi-travail-macron-veut-version-beaucoup-plus-radicale). Alors qu'il déclarait en novembre dernier qu'il [ne croyait « pas une seule seconde aux cent jours et à la réforme par ordonnances »](http://www.lemonde.fr/le-club-de-l-economie/article/2016/11/25/emmanuel-macron-en-france-on-confond-liberal-et-conservateur_5037874_4795074.html), il annonce maintenant qu'il souhaite [recourir aux ordonnances pour réformer le code du travail](http://www.lefigaro.fr/elections/presidentielles/2017/04/10/35003-20170410ARTFIG00288-macron-preconise-les-ordonnances-alors-qu-il-y-etait-oppose-cinq-mois-plus-tot.php) au pas de charge. C'est à dire passer outre l'avis du parlement, comme dans la procédure du 49-3. Il faut rappeler que pour adopter la [loi Macron en 2015, le gouvernement à utilisé le 49-3 à 3 reprises](
http://www.lemonde.fr/politique/article/2015/07/09/valls-annonce-un-nouveau-recours-au-49-3-pour-faire-adopter-definitivement-la-loi-macron_4677263_823448.html)...

Il faut rappeler aussi que cette « loi travail » a aussi étendu la possibilité ouverte à l’employeur de négocier un accord d’entreprise imposant l’augmentation du temps de travail sans contrepartie salariale (jusqu'à 46h par semaine), ou la réduction du salaire pour un temps de travail équivalent. Par ailleurs, elle facilite les licenciements boursiers ou économiques, qui se sont multipliés depuis plus de 15 ans. Elle permet aussi de baisser le taux de majoration des heures supplémentaires (de 25 à 10%). En réalité, c'est une véritable remise en cause du principe des 35 heures, qui va accentuer la course à l'abaissement des droits sociaux des salariés dans les entreprises, notamment sur les salaires. Enfin, [ d'après leur projection, deux chercheurs ont conclu que d'ici 4 ans, cette loi fera exploser la précarité et augmenter considérablement le chômage](https://www.youtube.com/watch?v=VuymUdVHheE).

**Comment by Scalpi** [comment]
Merci de remettre la référence à WorkSim et l'explication que j'en avais donnée.

**Comment by Scalpi** [comment]
Ok pour moi

**Comment by LVAI** [comment]
Commited
