### ISSUE TITLE
Liens LAEC

### ISSUE THREAD

**Issue by sarah48** [Insoumis/programme-macron#97]
1.2

.[Baisse des impôts pour les revenus de moins de 4000 euros.](https://impots.jlm2017.fr/)

.[Revaloriser les aides personnelles au logement et supprimer le mois de carence avant la perception des premières APL.](https://avenirencommun.fr/le-livret-logement/)

.[Encadrer véritablement les loyers à la baisse.](https://avenirencommun.fr/le-livret-logement/)

.[Plafonner les loyers dans le secteur HLM pour ne pas dépasser 20 % du revenu des ménages.](https://avenirencommun.fr/le-livret-logement/)

.[Réduire la TVA sur les produits de première nécessité, revenir sur les hausses récentes et réinstaurer une TVA grand luxe pour financer ces baisses.](https://laec.fr/s36m6)

.[Gratuité réelle de l’éducation publique y compris des cantines, du transport (transports collectifs urbains gratuits pour les moins de 18 ans) et des activités périscolaires.](https://avenirencommun.fr/le-livret-pauvrete/)

.[Gratuité des formations universitaires, et les frais scolaires des universités dès la rentrée 2017. ](https://avenirencommun.fr/le-livret-pauvrete/)

.[Tarification progressive sur l’eau en pénalisant les mésusages et gaspillages.](https://avenirencommun.fr/le-livret-pauvrete/)

1.7

[.Appuyer l'enseignement professionnel public, arrêter les fermetures de classes et de lycées professionnels et augmenter le nombre d'établissements](https://laec.fr/s74m1)

.[Rétablir le bac professionnel en quatre ans.](https://laec.fr/s74m2)

.[Développer les cursus courts dans l'enseignement supérieur et encourager la poursuite d'études après un bac professionnel ou technologique (BTS, DUT, licences professionnelles…)](https://laec.fr/s74m3)

.[Ouvrir un lycée professionnel maritime dans chaque département littoral.](https://avenirencommun.fr/le-livret-education/)

.[Supprimer les aides à l’apprentissage de manière à développer la formation
professionnelle sous statut scolaire.](https://avenirencommun.fr/le-livret-education/).

2.1

.[Donner la liberté aux artisans, commerçants, indépendants, chefs d'entreprises et auto-entrepreneurs de s'affilier au régime général de la Sécurité sociale plutôt qu'au Régime social des indépendants (RSI).](https://laec.fr/s26m5)

.[Financer l'escompte des PME à taux zéro par le pôle financier public.](https://laec.fr/s21m3)

.[Créer un fonds de solidarité interentreprises pour mutualiser la contribution sociale entre toutes les entreprises et les groupes, pour soulager les PME et assurer la solidarité financière entre donneurs d'ordre et sous-traitants, financé grâce à une contribution des entreprises selon un barème progressif.](https://laec.fr/s21m6)

.[Renverser la présomption d’indépendance au profit d’une présomption de salariat. (...) Tout·e travailleur·euse réalisant sa prestation de travail dans une situation de dépendance économique (par exemple avec un client unique, ou sous le contrôle d’une plate-forme numérique) doit être présumé·e salarié·e, et ainsi jouir des droits qui s’y rattachent. ](https://avenirencommun.fr/le-livret-uberisation/)

.[Baisse de l'Impôt sur les sociétés à 25%.](https://avenirencommun.fr/livret-produire-france/)

2.3: Déjà fait.

3.3

.[Mettre en place une commission d'enquête parlementaire sur le pillage économique et industriel des dernières années (abandons de fleurons comme Alstom, Alcatel, EADS…).](https://laec.fr/s16m4)

.[Injecter 100 milliards d'euros supplémentaires dans l'économie pour des investissements écologiquement et socialement utiles.](https://laec.fr/s18m1)

.[Transformer les 41 milliards d'euros annuels du pacte de responsabilité et du crédit d'impôt compétitivité  pour financer la transition énergétique et les activités socialement utiles.](https://laec.fr/s18m2)

.[Réindustrialiser le pays par l'investissement, le rétablissement de plans de filières pour coordonner donneurs d'ordres et sous-traitants, clients et fournisseurs, la création de pôles publics dans l'énergie ou les transports, la défense des industries stratégiques et la reconstruction de conglomérats combinant plusieurs activités.](https://laec.fr/s18m4)

.[Le Crédit d’impôt recherche (CIR) sera supprimé (...). L’aide publique, s’appuyant notamment sur le pôle public bancaire, sera dirigée exclusivement sur les vrais acteurs de la R&D, et en priorité les PME qui consacrent aujourd'hui énormément de temps et d’argent à la recherche de financements.](https://avenirencommun.fr/livret-produire-france/)

.[Mettre en commun connaissances et brevets qui, grâce aux outils de la planification, deviendront un patrimoine productif collectif.](https://avenirencommun.fr/livret-produire-france/)

3.4

.[
Refuser les OGM, bannir les pesticides nuisibles en commençant par une interdiction immédiate des plus dangereux (glyphosate, néonicotinoïdes, etc.)](https://laec.fr/s45m2)

.[Gérer durablement l'eau, bien commun essentiel à toute forme de vie : lancer des programmes de dépollution des cours d'eau et océans, favoriser la création de régies publiques de l'eau au niveau local pour une gestion démocratique](https://laec.fr/s45m3)

.[Élaborer un plan de santé environnementale (lutte contre la pollution, interdiction des pesticides…).](https://laec.fr/s67m2)

.[Plan national visant à accompagner l’ensemble des agriculteurs et agricultrices dans la transition écologique de l’agriculture.](https://avenirencommun.fr/livret-planification-ecologique-regle-verte/)

.[Intégration pour tout projet ou proposition de loi, d’un volet santé dans l’étude d’impact préalable.](https://avenirencommun.fr/le-livret-sante/)

.[Faire de la prévention et de l'éducation à la santé dès le plus jeune âge, en renforçant la médecine scolaire et la Protection maternelle et infantile](https://laec.fr/s67m2)

.[Refuser les traités de libre-échange : le traité trans-atlantique TAFTA entre l'UE et les États-Unis, CETA avec le Canada et le traité TISA de libéralisation des services.](https://laec.fr/s49m4)

3.6

.[Injecter 100 milliards d'euros supplémentaires dans l'économie pour des investissements écologiquement et socialement utiles.](https://laec.fr/s18m1)

.[Transformer les 41 milliards d'euros annuels du pacte de responsabilité et du crédit d'impôt compétitivité pour financer la transition énergétique et les activités socialement utiles.](https://laec.fr/s18m2)

.[Porter l’effort de recherche et développement (R&D) à 3 % du PIB, avec 1,5 % du PIB pour le secteur
public en 2022 (doublement du budget de l’Enseignement Superieur et de la Recherche) en cinq ans.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Recrutement d'au moins 5 000 chercheur·euse·s, enseignant·e·s-chercheur·euse·s et personnels techniques en trois ans dans l'Enseignement Supérieur et la Recherche.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Suppression de l'ANR et des structures liées aux Investissements d’Avenir, pour affecter les fonds au CNRS et aux autres EPST (INRA, INSERM, INRIA...)..](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Remise en cause du processus d'autonomie des universités: Abrogation des lois Pécresse, Fioraso et Sauvadet.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Suppression du crédit d’impôt recherche (CIR).](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

3.8

.[Garantir la neutralité du net et lutter contre le profilage en ligne, comme le défend l'association La Quadrature du Net.](https://laec.fr/s83m1)

.[S'opposer aux logiques de privatisation des services liés au numérique, lutter contre l'évasion fiscale et la création de nouvelles rentes privées par les plateformes lucratives.](https://laec.fr/s83m4)

.[Protéger les données personnelles contre leur utilisation mercantile.](https://laec.fr/s83m4)

.[Evaluation de l’efficacité des solutions techniques utilisées par les services de renseignement par une commission d’enquête parlementaire, et abrogation des mesures inefficaces, disproportionnées ou contre-productives.](https://avenirencommun.fr/le-livret-numerique/)

.[Remise en question des pratiques et dispositifs de surveillance de masse sur Internet et les réseaux téléphoniques, inefficaces et liberticides.](https://avenirencommun.fr/le-livret-numerique/)

.[Amélioration de la transparence des plateformes pour lutter contre le trafic des données personnelles](https://avenirencommun.fr/le-livret-numerique/)

5.3

.[Renforcement des politiques de prévention en évitant les phénomènes de mises en danger qu’ils soient sociaux, économiques, scolaires ou urbains. ](https://avenirencommun.fr/le-livret-securite/)

.[Recrutement dans la police et la gendarmerie de 5 000 agents administratifs, 3000 agents, doublement des effectifs de la police technique et scientifique (2 000 embauches), formation et titularisation d'adjoints de sécurité.](https://avenirencommun.fr/le-livret-securite/)

.[Renforcement du renseignement territorial et humain, remise en cause de la fusion de la DST et des RG.](https://avenirencommun.fr/le-livret-securite/)

.[Augmentation du budget de la justice en cinq ans (+ 2,5 milliards d’euros en 2017) afin de parvenir en 2022 au niveau des principaux pays de l’Union européenne (UE).](https://avenirencommun.fr/le-livret-justice/)

.[Légalisation contrôlée et encadrée du cannabis pour désengorger les activités policières.](https://avenirencommun.fr/le-livret-securite/)

5.7

.[Formation des personnels aux enjeux de cyber-sécurité et augmentation des moyens de l’Agence nationale de la sécurité des systèmes d’information (Anssi).](https://avenirencommun.fr/notre-revolution-numerique/)

.[Augmentation des moyens de cyberdéfense du pays.](https://avenirencommun.fr/notre-revolution-numerique/)

.[Sortie de l'Otan](https://laec.fr/s54m2)

.[Remise en question des pratiques et dispositifs de surveillance de masse sur Internet et les réseaux téléphoniques.](https://avenirencommun.fr/le-livret-numerique/)

.[Mise en place de sanctions automatiques contre les États et entreprises qui surveillent nos élus, citoyens et industries.](https://avenirencommun.fr/notre-revolution-numerique/)

.[Protection des données personnelles de nos citoyens lorsqu'elles sont hébergées à l'étranger.](https://avenirencommun.fr/le-livret-numerique/)

.[Aide au chiffrement des données et des correspondances.](https://avenirencommun.fr/le-livret-numerique/)

.[Amélioration de la transparence des plateformes pour lutter contre le trafic des données personnelles.](https://avenirencommun.fr/le-livret-numerique/)

5.9

.[Renforcement et diversification du renseignement territorial et humain, remise en cause de la fusion de la DST et des RG, recrutement d'analystes et de traducteurs.](https://avenirencommun.fr/le-livret-securite/)

.[Sortie de l’état d’urgence à l’initiative du Parlement et le refus de l’État d’urgence permanent par l’abrogation des dispositions de la loi Urvoas du 3 juin 2016.](https://avenirencommun.fr/le-livret-securite/)

.[Arrêt progressif des opérations « Sentinelle » (type Vigipirate) et le passage à une surveillance ciblée des lieux publics par les effectifs renforcés de la police, la gendarmerie, la garde nationale et non l’armée.](https://avenirencommun.fr/le-livret-securite/)

.[Focalisation du renseignement sur les menaces sécuritaires et économiques hexagonales, et non sur la surveillance des mouvements sociaux.](https://avenirencommun.fr/le-livret-securite/)

.[Restauration de l’indépendance nationale en matière de renseignement, via la fin de la tutelle de fait exercée par les agences anglo-saxonnes, et la défense de l’échange d’information dans les discussions pour constituer une coalition universelle contre Daesh.](https://avenirencommun.fr/le-livret-securite/)

6.9

.[Arrêt du processus d'autonomie des universités : Abrogation des lois Pécresse, Fioraso et Sauvadet.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Suppression du Haut Conseil à l’évaluation (HCERES). Les modalités de l’évaluation des unités seront discutées par concertation entre les différent·e·s acteur·trice·s.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Suppression de l’ANR et des structures liées aux Investissements d’Avenir.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Dissolution des ComUE et démantèlement progressif des Initiatives d’excellence.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

. [Construction de lycées professionnels dotés d’équipements de qualité afin d’augmenter les capacités d’accueil, de garantir un maillage fin de lycées polytechniques sur l’ensemble du territoire et de véritables choix d’orientation aux élèves.](https://avenirencommun.fr/le-livret-education/)

. [Ouverture d'un lycée professionnel maritime dans chaque département littoral et intégrer des lycées agricoles au ministère de l’EN.](https://avenirencommun.fr/le-livret-education/)

7.4

.[Lancement un programme ambitieux de maîtrise de la langue française écrite et parlée, intégrant la transmission des principes républicains et l’information sur l’ensemble des droits sociaux.](https://avenirencommun.fr/le-livret-migrations/)

.[Augmentation du nombre de classes et les moyens alloués pour les enfants nouvellement arrivés en France.](https://avenirencommun.fr/le-livret-migrations/)

.[Renforcement des dispositions de la loi Toubon, notamment en matière (…) d’enseignement en français.](https://avenirencommun.fr/livret-francophonie-politique/)

.[Développement et diversification des moyens de diffusion et de connaissance de la langue française sur tous les supports de communication disponibles : sites Internet dédiés, réseaux sociaux, plateformes collaboratives universitaires.](https://avenirencommun.fr/livret-francophonie-politique/)

.[Développement des Centres internationaux d’études françaises (CIEF) afin d’étendre l’usage du français dans l’enseignement supérieur pour les étudiant·e·s des pays membres de l’OIF.](https://avenirencommun.fr/livret-francophonie-politique/)

.[Renforcement du réseau des instituts et alliances français dans les pays non francophones
et planifier des échanges d’étudiant·e·s et de lycéen·ne·s.](https://avenirencommun.fr/livret-francophonie-politique/)

.[Renforcement des établissements d’enseignement français à l’étranger, ainsi que pour le Centre international d’études pédagogiques (CIEP) de Sèvres.](https://avenirencommun.fr/livret-francophonie-politique/)

7.5

.[Rétablir l’unicité de la loi sur le territoire en soumettant l’octroi des titres de séjour à des critères objectifs ne souffrant aucune différence d’interprétation d’une Préfecture à l’autre, en finir avec l’arbitraire préfectoral et les lenteurs administratives. ](https://avenirencommun.fr/le-livret-migrations/)

.[Rattacher l’Office français de protection des réfugiés et apatrides (Ofpra) au ministère des Affaires étrangères (et non au ministère de l’Intérieur) afin de rétablir un droit d’asile déconnecté des politiques migratoires et d’augmenter son budget de fonctionnement.](https://avenirencommun.fr/le-livret-migrations/)

.[Mise en oeuvre d'un accueil digne des migrants avec une répartition sur l’ensemble du territoire européen en mettant fin aux hot spots.](https://avenirencommun.fr/le-livret-migrations/)

.[Augmenter le nombre de places en Centre d’accueil pour demandeurs d’asile (Cada).](https://avenirencommun.fr/le-livret-migrations/)

.[Construction des centres d’accueil aux normes internationales sur le modèle de celui
de Grande-Synthe, pour proposer aux migrants des conditions dignes.](https://avenirencommun.fr/le-livret-migrations/)

.[Rompre avec les directives européennes et abroger les lois successives ayant eu pour objectif de restreindre le droit d’asile en France.](https://avenirencommun.fr/le-livret-migrations/)

.[Autoriser les demandeurs d’asile à travailler pendant la période d’attente d’examen de leur dossier.](https://avenirencommun.fr/le-livret-migrations/)

.[Construire un programme pour l’aide au retour des réfugiés qui le souhaitent lorsque la situation de leur pays de départ le permet.](https://avenirencommun.fr/le-livret-migrations/)

8.7

.[Organiser le processus de sortie du Royaume-Uni de l'Union européenne sans esprit de vengeance ou de punition, dénonciation des accords du Touquet. ](https://laec.fr/s50)

.[Sortir des traités européens.](https://laec.fr/chapitre/4/sortir-des-traites-europeens)` 

.[S'exonérer du pacte de stabilité et des règles européennes encadrant les déficits et dénoncer le Traité sur la stabilité, la coordination et la gouvernance (TSCG).](https://laec.fr/s49m1)

.[Mettre fin au dumping à l'intérieur de l'UE par une politique volontariste et rapide d'harmonisation sociale et fiscale par le haut dans toute l'UE avec inscription d'une clause de non-régression des droits sociaux.](https://laec.fr/s51m7)

.[Refuser les traités de libre-échange : le traité trans-atlantique TAFTA entre l'UE et les États-Unis, CETA avec le Canada et le traité TISA de libéralisation des services.](https://laec.fr/s49m4)

.[Interdire aux banques françaises toute activité dans les paradis fiscaux en retirant les licences bancaires des établissements récalcitrants.](https://laec.fr/s37m3)

.[Agir contre l'évasion fiscale au niveau international, notamment en organisant le blocus des paradis fiscaux.](https://laec.fr/s37m4)

.[Renforcer les moyens humains et techniques de l'administration fiscale et des douanes dans la lutte contre la fraude et l'évasion fiscales.](https://laec.fr/s37m5)

8-8

.[Mettre fin au dumping à l'intérieur de l'UE par une politique volontariste et rapide d'harmonisation sociale et fiscale par le haut dans toute l'UE avec inscription d'une clause de non-régression des droits sociaux.](https://laec.fr/s51m7)

.[Inscription du droit d’accès à Internet dans la Constitution.](https://avenirencommun.fr/le-livret-numerique/)

.[Défendre la neutralité du net aux niveaux national, européen et international.](https://avenirencommun.fr/le-livret-numerique/)

.[Plan d'investissement des infrastructures pour atteindre un objectif d'accès au Très haut débit sur tout le territoire sous 5 ans et une couverture totale 4G sous 10 ans.](https://avenirencommun.fr/le-livret-numerique/)

.[Remise en question des pratiques et dispositifs de surveillance de masse sur Internet et les réseaux téléphoniques, inefficaces et liberticides.](https://avenirencommun.fr/le-livret-numerique/)

9.2: déjà fait.

9.10

.[Augmenter l'allocation aux adultes handicapés (808 euros de base aujourd'hui) au niveau du smic pour les personnes en situation de handicap dans l'incapacité totale de travailler.](https://laec.fr/s68m3)

.[Revaloriser le taux des pensions d’invalidité dans les mêmes proportions et selon les mêmes modalités.](https://avenirencommun.fr/le-livret-handicap/)

.[Favoriser l’emploi des travailleur·se·s handicapé·e·s aux compétences reconnues.](https://avenirencommun.fr/le-livret-handicap/)

10.1

.[Renforcement des moyens humains et techniques de l'administration fiscale et des douanes dans la lutte contre la fraude et l'évasion fiscales.](https://laec.fr/s37m5)

.[Augmentation les effectifs des services publics comme  Pôle emploi, les départements, les caisses d’allocation familiales ou les centres communaux d’action sociale pour un réel accompagnement des personnes.](https://avenirencommun.fr/le-livret-pauvrete/) 

10.5

.[Augmentation les effectifs des services publics comme  Pôle emploi, les départements, les caisses d’allocation familiales ou les centres communaux d’action sociale pour un réel accompagnement des personnes.](https://avenirencommun.fr/le-livret-pauvrete/) 

.[Restauration de services publics de qualité, qui exige la recréation de plus de 400 000 emplois publics, en particulier d’enseignant·e·s, de personnels soignants et de garant·e·s de notre sûreté collective, mais aussi le recrutement d’employé·e·s public·que·s ou parapublic·que·s dans le secteur de la petite enfance et dans les maisons de retraite.](https://avenirencommun.fr/livret-emploi-rtt/)

.[Enseignement Supérieur: Suppression du Haut Conseil à l’évaluation (HCERES). Les modalités de l’évaluation des unités seront discutées par concertation entre les différent·e·s acteur·trice·s.](https://avenirencommun.fr/livret-de-lenseignement-de-recherche/)

.[Ecoles : abrogation de la réforme de l’évaluation et pleine maîtrise de l’évaluation en interdisant toute immixtion hiérarchique.](https://avenirencommun.fr/le-livret-education/)

.[Police et gendarmerie : Amélioration de l’accueil du public par la diminution du temps d’attente pour les dépôts de plainte.](https://avenirencommun.fr/le-livret-securite/)

**Comment by LVAI** [comment]
6.10
[livret enseignement supérieur](https://avenirencommun.fr/app/uploads/2017/03/Livret-ESR-web_vdef.pdf)
- Le plan d’investissement de début de mandat dégagera 2 Mds € pour rénover les universités et construire
des logements étudiants.
- La construction de résidences universitaires occupera une grande place avec pour objectif 15 000 mises en chantier de logements sociaux étudiants par an (contre 6 600 par an entre 2012 et 2016)

**Comment by LVAI** [comment]
Commited
